core/sourcemm_api.cpp, core/sourcemm_api.h
(We don't use it and it doesn't exist on most.)
=> Don't look for IServerTools on ep1 games.

core/logic/PluginSys.cpp, core/logic/smn_core.cpp
When a plugin calls SetFailState it is paused and all natives it
registered are unavailable. Other plugins, which depend on those natives
keep running and error whenever they try to call those natives.
This correctly sets the dependent plugins to an error state and also calls OnLibraryRemoved correctly for all libraries as if the
plugin which called SetFailState was unloaded.
As a sideeffect OnPluginPauseChange is called again, when a plugin changes its pause state.
=> Pause dependent plugins on SetFailState (bug 6120)

plugins/include/sdkhooks.inc
Looks like the |weapon| parameter went missing during the switch to the
transitional syntax.
There was no -Post typedef including the |damagecustom| bit at all too.
=> Fix missing params in OnTakeDamagePost typedef

plugins/include/usermessages.inc
Alright, take 2. It's surprisingly easy to forget that CS:GO exists.
Two separate commits to make cherrypicking to 1.7 easier.
=> Use BfRead or Protobuf tags in umsg hook callbacks, rather than a generic Handle.

core/logic/AdminCache.cpp
Revamping Steam Id handling in AdminCache.cpp led to "BOT" no longer being valid. Some people were apparently relying on this functionality to give bots certain immunities.
I think that it's best that we just make it work again.
=> Fix regression causing "BOT" to no longer be valid in adminsys for Steam identities.

public/asm/asm.c, public/smsdk_ext.cpp, public/smsdk_ext.h
I had to do this for SteamWorks, Drifter hit it with enabling SDK independence with DHooks2.
=> Enable SDK independence with MM:S enabled extensions.

extensions/mysql/mysql/MyDriver.cpp
Users presently experience dead locks from how we lock our DB structures, and how MySQL establishes a connection to a foreign server. If there's a blip of packet loss, the server is almost always toast on level change.
This bundles ideas together from https://github.com/alliedmodders/sourcemod/pull/165 into something we can hopefully merge.
=> Establish a default timeout for MySQL connectivity.

core/logic/HandleSys.h
The tf2itemsinfo plugin uses 10332 handles but does not leak them.
Whenever another plugin leaks handles, sourcemod will kill tf2itemsinfo first because it always takes more than half the current maximum number of handles.
"HANDLESYS_HANDLE_MASK needs to be changed."
Why does it need to be changed? isn't 16 bits correctly masked by 0xFFFF?
"why does this plugin keep so many handles live?"
Because it parses the item schema into ADT data structures for fast access.
=> Increased handles to 32k

sourcepawn/compiler/sc1.cpp
As described in [bug 6226](https://bugs.alliedmods.net/show_bug.cgi?id=6226).
When a function implementing a forward has a return type that doesn't match, the line in the error message is the line of the forward declaration, rather than the implementing function. This is a regression in 1.7+.
This seems to fix it.
=> Fix incorrect error line show for incorrect return value on forwards (bug 6226).

plugins/adminmenu.sp, plugins/adminmenu/dynamicmenu.sp
To keep myself familiar with the new syntax and classes, as well as get more of the incs converted to newdecls, I ported the adminmenu plugin to the transitional syntax, including using ArrayList and DataPack methodmaps.
It now can compile with #pragma newdecls required (although I did not add the pragma). Despite this, the hacky enum structs were left with the old colon syntax (not affecting the pragma) as converting them seemed to generate errors.
=> Convert adminmenu to use newdecls and new classes/methodmaps.

sourcepawn/compiler/sc3.cpp
Silly bug caused by SP1's decoupling of value state and l-value state. When we encounter an accessor, we must set the l-value bit back to `true` since if we resolved the `this` from an expression it will be `false`.
=> Fix chained field expressions losing lvalue-ness. (bug 6298)

sourcepawn/compiler/sc3.cpp
This code is all horseshit, but whatever, the show it must go on. There are two bugs here.
1. The compiler has a special case for `x[y]` where if `y` is a constexpr produced by an enumeration value, the tag of the l-value is the tag specified on the enumeration value. I.e., this is what makes enum structs sort-of work. That means if the enum symbol is free-floating (not part of an enum struct), the tag will always be empty. I fixed this with a `sym->parent` check.
2. When restarting the accessor matching loop after parsing an array access, we don't reset `lvalue` to `true`. Before field accessors that wasn't a problem, since we just immediately returned. Now, however, we must make sure the l-valueness is maintained.
As a special totally unworthy-of-note bonus to (1), the check for enum …
=> Don't special case hierarchy-free enumeration constants when used as array indices. (bug 6302)

core/logic/PluginSys.cpp
RefreshAll is normally only called in LevelShutdown to unload any plugins loaded for that map only (obsolete) or any that have been change since load. LevelInit then calls DoGlobalPluginLoads.
By adding the RefreshAll call in "sm plugins refresh", we replicate this. Tested and it seems to work as documented now.
=> Fix "sm plugins refresh" not refreshing changed plugins.

extensions/cstrike/forwards.cpp, extensions/cstrike/natives.cpp, extensions/cstrike/util_cstrike.cpp, extensions/cstrike/util_cstrike.h, gamedata/sm-cstrike.games/game.csgo.txt, public/CDetour/detours.cpp, public/CDetour/detours.h, tools/gdc-psyfork/symbols.txt
This fixes GetWeaponPrice for CS:GO after valves latest update. For windows there is no way to create a unique signature so the function address is grabbed from another function that calls it. In doing this I had to change CDetour to be able to pass a address instead of a gamedata string. I added some safety measures and also added a method for GDC to check that the offset within the function is correct.
=> GetWeaponPrice fix for CS:GO

core/logic/AdminCache.cpp
As suggested by @Fyren in [bug 6248](https://bugs.alliedmods.net/show_bug.cgi?id=6248), this removes the g_FlagSet array all together.
=> Remove faulty g_FlagSet array in adminsys (bug 6248).

sourcepawn/compiler/sc.h, sourcepawn/compiler/sc1.cpp, sourcepawn/compiler/sc2.cpp, sourcepawn/compiler/sc3.cpp, sourcepawn/compiler/tests/fail-newdecls.txt, sourcepawn/compiler/tests/fail-sizeof-default-arg.sp, sourcepawn/compiler/tests/fail-sizeof-default-arg.txt
This craptacular feature has been a minor thorn in my side. I don't like it, it doesn't reflect where we want the API to be, and it's not usable in situations where the array size is indeterminate or controlled by a dynamic value. It also computes its value wrong for character arrays.
From a language design perspective, it's very odd that the `sizeof` in this context is magic and binds to the callsite rather than the in-scope argument. 
As far as I know, it's rare for SourceMod code to use this, so let's try removing it. Other special cases removed as well are `tagof` and `countof` - the former being particularly useless, and we can get rid of a bunch of code as a result.
=> Remove sizeof() as a special-case default argument value.

extensions/topmenus/TopMenu.cpp
Added NULL check on m_Clients like exists elsewhere in the class due to it only being initialized in ctor if ServerActivated or upon ServerActivate.
=> Fix crash when creating and destroying a TopMenu before map start (bug 6303).

core/logic/smn_filesystem.cpp
This exists in the File methodmap, but there is no implementation for it.
=> Add missing impl for File.ReadUint16.

core/MenuStyle_Radio.cpp, core/MenuStyle_Radio.h, core/MenuStyle_Valve.cpp, core/MenuStyle_Valve.h
Totally wrong plugins can crash SourceMod quite easily unfortunately during our menu drawing process. We maintain the pointer to the menu and still use it. During the draw process, pawn plugins can close the handle on us, resulting in a free'd handle. The solution in other areas of SM is to "root" (clone) the handle. To my knowledge, there's at least one bug on BZ related to this, along with a ton of people always hitting this when first using the menu API (including myself, ages ago).
Before:
Segmentation fault
After:
L 02/21/2015 - 20:11:40: [SM] Native "CloseHandle" reported: Handle 63e0357 is invalid (error 3)
L 02/21/2015 - 20:11:40: [SM] Displaying call stack trace for plugin "MenuCrash.smx":
L 02/21/2015 - 20:11:40: [SM]   [0]  Line 53, …
=> Root Menu Handles during Display (Bug 5620).

plugins/include/tf2_stocks.inc
Continues #201, which added `TF2_GetClientTeam`.  This PR adds `TF2_SetClientTeam` in order to provide full symmetry.  I was thinking about doing `TF2_ChangeClientTeam`, since it wraps around `ChangeClientTeam`, but I decided against it because of `TF2_{Get|Set}PlayerClass`.
Was also thinking about updating `tf2_stocks.inc` to new-style syntax but I have no idea how to do the C++ side of methodmaps.
And...removes some trailing whitespace.
=> Add TF2_SetClientTeam to provide symmetry to TF2_GetClientTeam

core/logic/smn_adt_array.cpp, plugins/include/adt_array.inc
I'm not sure what is going on with trailing whitespace/line endings in this file, my apologies for making that diff crazy.
I guess there's no easy way to test, but I did a small test myself:
```
public OnPluginStart()
{
Handle arr = CreateArray(2);
PushArrayCell(arr, 10);
PushArrayCell(arr, 20);
PushArrayCell(arr, 30);
PushArrayCell(arr, 40);
SetArrayCell(arr, 0, -10, 1);
SetArrayCell(arr, 1, -20, 1);
SetArrayCell(arr, 2, -30, 1);
SetArrayCell(arr, 3, -40, 1);
LogMessage("result = %d", FindValueInArray(arr, -999));    // should be -1
LogMessage("result = %d", FindValueInArray(arr, -999, 0)); // should be -1
LogMessage("result = %d", FindValueInArray(arr, -999, 1)); // should be -1
LogMessage("result = %d", FindValueInArray(arr, -30));    // should be -1 …
```
=> Add block parameter to FindValueInArray native.

sourcepawn/jit/AMBuilder, sourcepawn/jit/code-stubs.h, sourcepawn/jit/debug-trace.cpp, sourcepawn/jit/debug-trace.h, sourcepawn/jit/environment.cpp, sourcepawn/jit/interpreter.cpp, sourcepawn/jit/interpreter.h, sourcepawn/jit/jit_shared.h, sourcepawn/jit/plugin-context.cpp, sourcepawn/jit/plugin-context.h, sourcepawn/jit/plugin-runtime.h, sourcepawn/jit/x86/code-stubs-x86.cpp, sourcepawn/jit/x86/jit_x86.cpp, sourcepawn/jit/x86/jit_x86.h
This is a holdover from SourceMod 1.0, when the VM was in core and the JIT was a closed-source implementation. sp_context_t allowed the two to share vital VM state. These days, it's confusing and irrelevant.
Once again this is largely a syntactic refactoring. Anything that accessed sp_context_t now accesses PluginContext instead. Many functions that had to take in some horrible combination of pointers now is a helper function directly on PluginContext.
=> Remove sp_context_t.

extensions/tf2/conditions.cpp, extensions/tf2/conditions.h, extensions/tf2/extension.cpp, extensions/tf2/extension.h
For many TF2-specfiic plugins, it's useful to know when a "player condition" is added or removed. We don't/can't hook the functions for add/removing them directly due to them getting inlined in places. We, instead, currently have a loop over all player condition variables (5 of them any counting) for each player, every frame.
Instead, we can insert ourselves as a sendproxy for these sendprops, letting use know when the variable has changed (as the proxies are called when it serializes the data to send to the client).
This is still pending some final testing, but it's ready to be looked at.
@VoiDeD @asherkin :japanese_goblin:
=> Replace frameloop for player condition checks in TF2 ext with sendproxies

sourcepawn/compiler/AMBuilder
Obviously this isn't ideal, but this should allow newer versions of g++ to successfully compile the SourceMod compiler once again.
=> Add Wno-error=sign-compare for gcc to Compiler.

sourcepawn/compiler/sc.h, sourcepawn/compiler/sc1.cpp, sourcepawn/compiler/sc5-in.scp
Currently, as forwards are being slowly ported to the new transitional syntax, there is a situation where new transitional code is being written against non-ported forwards, ex:
```c
forward OnPluginStart();
// in order for this newdecl function to compile
// it must be declared as returning int because the old syntax always implicitly returned cells
public int OnPluginStart()
{
}
```
Now later in the future when the forward is ported (and the return type changes to `void`), the following occurs:
```c
forward void OnPluginStart();
// error 025: function heading differs from prototype
public int OnPluginStart()
{
}
```
This PR improves the diagnostic message to be: `error 180: function return type differs from prototype. expected 'void', but got 'int'`.
Additionally, it improves the error …
=> Improve the diagnostic given when a function prototype doesn't match an existing definition

plugins/include/functions.inc
See changes for details, should be obvious. What also strikes me as odd is that there is only one cpflag atm. Has this always been the case? Will there be more in the future? Or why is this designed to be a flagstring?
=> Documentation oddities for Call_PushStringEx

sourcepawn/compiler/sc.h, sourcepawn/compiler/sc2.cpp, sourcepawn/compiler/sc3.cpp, sourcepawn/compiler/sc4.cpp, sourcepawn/compiler/sc5-in.scp, sourcepawn/compiler/sc6.cpp, sourcepawn/compiler/smx-builder.h, sourcepawn/compiler/tests/fail-callback-returns-array.sp, sourcepawn/compiler/tests/fail-callback-returns-array.txt, sourcepawn/compiler/tests/fail-newdecls.txt, sourcepawn/include/smx/smx-v1-opcodes.h
This patch allows using non-public functions as callbacks. The JIT is pretty heavily designed around the public function table as an entry point, so the trick here was to just repurpose that table: it now contains all functions that were generated, regardless of whether or not they're public. Non-public ones get some name decoration so they won't cause name collisions (for example, with `static`).
The tricky part is that Pawn is fairly gross, as usual, and it's hard to tell what the final public index will be during codegen. To make this work I added a pseudo-opcode that references the function by name. During assembly this gets rewritten to a normal `const.pri`, after we've computed all the public indices.
As a result, function values no longer result in constant expressions (which is …
=> Allow capturing non-public functions as values.

extensions/tf2/natives.cpp
The vstk for some of the function calls is missing some of the sizes of some of the params. I think this is a bug as far as I know everything else has the size of all params.
=> FIx some TF2 natives not having the correct vstk size.

tools/gdc-psyfork/MemoryUtils.cpp
Error:
MemoryUtils.cpp: In member function ‘void* MemoryUtils::ResolveSymbol(void*, const char*)’:
MemoryUtils.cpp:249:43: error: ‘fstat’ was not declared in this scope
if (dlfile == -1 || fstat(dlfile, &dlstat) == -1)
Fixed by adding missing include: #include <sys/stat.h>
=> Fixed missing include in psyfork/memoryutils.cpp

core/MenuStyle_Radio.cpp
Fix regression in ad7d920ce0f57cfec0a35bc942d2a6a8583498e7
GetMenuStyleHandle(MenuStyle_Radio) crashes games, which don't support
the radio menu style. The style is never added to the menu manager, if
it's not supported, so GetMenuStyleHandle tries to call IsSupported on a
nullptr.
=> Fix crash regression in games that don't support radio style menus

extensions/cstrike/forwards.cpp, plugins/include/cstrike.inc
It appears that CS_OnCSWeaponDrop has always been broken and it was impossible to actually block the function even though the include said it could be done :smiley: The bug report https://bugs.alliedmods.net/show_bug.cgi?id=6334. I've also changed the wording in the include file as it  wasnt that clear what "deny" exactly meant.
=> Fix not being able to block CS_OnCSWeaponDrop and clarify include file.

extensions/sdktools/extension.cpp, extensions/sdktools/extension.h, extensions/sdktools/vnatives.cpp, gamedata/sdktools.games/engine.bgt.txt, gamedata/sdktools.games/engine.blade.txt, gamedata/sdktools.games/engine.contagion.txt, gamedata/sdktools.games/engine.csgo.txt, gamedata/sdktools.games/engine.css.txt, gamedata/sdktools.games/engine.darkm.txt, gamedata/sdktools.games/engine.dota.txt, gamedata/sdktools.games/engine.ep1.txt, gamedata/sdktools.games/engine.ep2.txt, gamedata/sdktools.games/engine.ep2valve.txt, gamedata/sdktools.games/engine.eye.txt, gamedata/sdktools.games/engine.insurgency.txt, gamedata/sdktools.games/engine.l4d.txt, gamedata/sdktools.games/engine.l4d2.txt, gamedata/sdktools.games/engine.sdk2013.txt, gamedata/sdktools.games/engine.swarm.txt, gamedata/sdktools.games/game.nucleardawn.txt, plugins/include/sdktools_functions.inc, plugins/playercommands.sp, plugins/playercommands/rename.sp, translations/playercommands.phrases.txt
Our current method for changing names (SetUserInfo), as implemented in the sm_rename command, does not work on the top three games by SM install count - TF2 (temporarily due to game bug, this works around), CS:S, and CS:GO. There may be others as well.
By implementing a new SetClientName native to wrap CBaseClient::SetName, we gain better game compatibility as well as bypass name change cooldown restrictions in the engine. SetName is one function earlier in the same vtable as SetUserInfo for every supported game, so there's very little extra support burden.
I've also updated the playercommands plugin to use the new native for sm_rename. I removed the old, ep1-specific logic and message for name changes while dead, too. The game logic it was considering was actually specific to CS:S, not …
=> Add SetClientName native.

extensions/tf2/conditions.cpp
@VoiDeD had seen some crashes on his TF2 servers after the new TF2 player conditions change detection was implemented. The crashes were in CHalfLife2::EntityToBCompatRef, called from PlayerConditionsMgr::ProcessCondChange.
This change makes it so that we pass an entity handle around instead of the raw player pointer, and checking it for validity before use in an attempt to quash the crash from the player no longer being valid.
=> Pass a handle instead of entptr to ProcessCondChange for stability.

core/logic/smn_filesystem.cpp
Apparently some (very few) plugins were relying on some undocumented behavior regarding passing an empty string to DirExists. SM was returning true, assuming that it referred to the current directory.
This change causes an error to be thrown in the case of an empty string being passed, similar to what we do for OpenDirectory. "." is still valid to explicitly work with the current directory.
=> Make DirExists("") throw an error.

plugins/include/menus.inc
Basically, this fixes a warning with the `MENU_ACTIONS_ALL` define triggered by commit 154d846.
=> Stop MENU_ACTIONS_ALL from tossing warnings with #pragma newdecls required

core/sourcemod.cpp
This fixes OnSourceModConfigChanged not being called for logic classes when
config is first read, matching behavior for core classes. The function is still called
before each class's OnSourceModStartup func.
This fixes [Bug 6304](https://bugs.alliedmods.net/show_bug.cgi?id=6304) where the initial Logging and LogMode settings on core.cfg are ignored until manually set to a different value later.
The BlockBadPlugins setting in PluginSys and ServerLang setting in Translator have the same issue and are fixed by this.
I also cannot find any case where this change would have a bad side effect, where there are config values used before StartSourcemod.
=> Fix CoreConfig init to happen after SMGlobalClasses from logic bin are added.

core/logic/PluginSys.cpp
Following #93, `SetFailState` was changed to put plugins in the `Plugin_Failed` state rather than `Plugin_Error`.
Unfortunately this had the side effect of not notifying plugin listeners when the failed plugin was then later unloaded which is described in [bug 6347](https://bugs.alliedmods.net/show_bug.cgi?id=6347).
#93 also introduced some cases where some conditional paths were enabled for plugins that are in `Plugin_Failed`, and this patch adds that for notifying plugin listeners.
=> Notify plugin listeners of SetFailState'd plugins on unload. (bug 6347)

public/asm/asm.c
This is mainly motivated to bring the 1.7 and 1.8+ versions back together, plus this message was probably here for a reason (and it doesn't look like things will do anything other than crash if this case is hit, hence the abort). I have no way of hitting the error case so that hasn't actually been tested, but it compiles and works fine normally. 1.7 changes will be separate because it still has the error using Msg.
@psychonic
=> Restore check_thunks error message.

core/HalfLife2.cpp, core/smn_halflife.cpp, plugins/include/halflife.inc
Increased PrintToChat & PrintToChatAll buffer size from 192 to 254; works in CSS/CSGO; dunno for the rest
=> Increased PrintToChat, PrintCenter & PrintHint w/ "all" version, buffer sizes from 192 to 254

AMBuildScript
This fixes the "undefined symbol: floorf" error that some people were getting in sourcemod.logic.so.
=> Link libm in all bin, not just engine-specific ones.

plugins/include/sourcemod.inc
We have this defined in core for error checking, but it's useless in sp since unsigned comparisons are not supported.
=> Remove Address_MinimumValid entry from sp incs

core/logic/smn_maplists.cpp
Alternatively, we can just remove the engine checks as it probably will not hurt to enable the logic for all.
=> Enable finding mapcycle in cfg dir on sdk2013 and bms.

core/PlayerManager.cpp, core/PlayerManager.h, core/sourcemod.cpp, plugins/include/clients.inc
Now gets set in hook on LevelInit (and before plugins are initialized) rather than in hook on the later ServerActivate.
Also made players array initialized sooner for subsystems that relied on it being populated when max was set.
=> Populate MaxClients before OnPluginStart is called.

plugins/basetriggers.sp, plugins/rockthevote.sp
Followup to #343, fixes a couple more map buffer sizes where `GetNextMap` is called.
=> Fix more buffer sizes for map names.

core/logic/smn_string.cpp
isalpha, isdigit, isupper, and islower do not return 0/1. They return 0 or anything-else. Since the bool tag in pawn only supports exactly 0 and 1, we need to return 1 for all truthy returns in the natives that wrap these.
=> Fix some ctype misuses (bug 6377).

core/PlayerManager.cpp
If a client is already connected, instead of double connecting them we should disconnect them instead, and then proceed onwards. There are a couple bugs on BZ where this may be related.
=> Call OnClientDisconnect(_Post) if the client has already connected.

public/sample_ext/AMBuildScript, public/sample_ext/AMBuilder, public/sample_ext/PackageScript, public/sample_ext/configure.py
This adds an AMBuildScript, configure.py, and PackageScript to the Sample Extension.
This is adapted from SourceMod 1.8's AMBuildScript and PackageScript.
This AMBuildScript is also smart enough to notice if smsdk_ext.cpp is located in the project.  This was added for compatibility with SM 1.5 and below extensions.
NOTE:  This always requires MM:S to be present even for non-MMS extensions.  I should probably fix that, but afaict it only affects the include paths.
=> Add AMBuild2 script to Sample Extension

core/HalfLife2.cpp, core/HalfLife2.h, core/smn_halflife.cpp, plugins/include/halflife.inc, plugins/testsuite/findmap.sp
Similar goal as #348 - exposes the fuzzy map matching to plugins.
The biggest difference is that we attempt to expose as much as the FindMap functionality from TF2 (and eventually CS:S, DoD:S, etc.) as we can in other games.
@powerlord Can you give this a look and let me know if you have any concerns with the implementation?
Also, @VoiDeD
=> Expose FindMap/ResolveFuzzyMapName to plugins.

extensions/mysql/mysql/MyDatabase.cpp
SQL_SetCharset wasn't thread safe and could race with other threaded
queries causing a crash.
=> Lock database before setting character set

plugins/include/clients.inc
Changing MAX_NAME_LENGTH from 32 to 128 due to CSGO having 128 bytes buffer-size.
See related commit : https://github.com/alliedmodders/sourcemod/commit/9e0dbfcf6807c0782a6a8eea079bd14afe24c74d where a Duck says that CSGO uses 128 bytes name buffer.
=> Changing MAX_NAME_LENGTH from 32 to 128 due to CSGO having 128.

plugins/include/clients.inc
Reverts alliedmodders/sourcemod#355
=> Revert "Changing MAX_NAME_LENGTH from 32 to 128 due to CSGO having 128."

core/HalfLife2.cpp, core/HalfLife2.h, core/smn_entities.cpp, plugins/include/entity.inc
This adds support for identifying Prop_Send string_t values for the DPT_String type (as opposed to char arrays), as well as getting values for Prop_Send string_t fields (Prop_Data was already supported) and setting values for both Prop_Send and Prop_Data string_t fields.
For setting, we have to allocate a string in the game's stringpool. The method here for it is a bit sketch, but it works and should not easily break.
This is not tested yet (other than the concept used for the AllocPooledString), but I plan to test in the near future.
=> Better string_t support for Get/Set EntPropString

core/CDataPack.cpp, core/CDataPack.h, core/logic/smn_datapacks.cpp
See individual commits.
The size reporting is a big hack, I'm not against shelving that until the iface can be trashed.
A slightly less hacky method would be to add something to the logic bridge.
Both changes have had light testing, although the alloc logic could do with some eyes to double-check.
@psychonic @Fyren
=> Improve DataPack memory allocation & Report size for DataPack Handles

core/PlayerManager.cpp, core/PlayerManager.h, core/smn_console.cpp, core/smn_keyvalues.cpp, core/smn_keyvalues.h, plugins/include/clients.inc, plugins/include/console.inc
Adds forwards:
// Pre-hook, blockable, can edit values on kv
Action OnClientCommandKeyValues(int client, KeyValues kv)
// Post-hook, only if not blocked
void OnClientCommandKeyValues_Post(int client, KeyValues kv)
And native:
// Bypasses hook if called within hook
void FakeClientCommandKeyValues(int client, KeyValues kv)
Supported by all games that have CCKVs (all newer orangebox games and later, with the exception of Dota 2).
Editing the kv in OnClientCommandKeyValues will currently cause a crash on Windows, but I have a fix for that coming to tier1 in the SDK.
=> Add support for listening to, blocking, changing, and faking ClientCommandKeyValues

.travis.yml, tools/checkout-deps.sh
So... The new travis environment doesn't allow you to sudo. So I've added a virtual arch environment using juju ( https://github.com/fsquillace/juju ). The Ubuntu 12.04 image that Travis uses is still ancient. Benefit here is we can maintain our build environment completely, and our own repository if we're going this route...
It's actually pretty nice to work with in general.
=> Use the new Travis-CI Container environment.

plugins/include/datapack.inc
Lots of users appear to be misusing the datapack position APIs and are making incorrect assumptions about what kind of values can be used as the position value.
This change aims to hide the value of a datapack's position behind a tag, thus requiring users to use the tagged value retrieved from a previous call to `GetPackPosition`, otherwise they'll encounter a compiler warning. This also updates the documentation to clarify how the functions should be used.
Hopefully using `enum` is still the usual way of declaring a tag in the new syntax.
@psychonic
=> Introduce a datapack position tag.

public/sample_ext/PackageScript
PackageScript used a bunch of commented-out CopyFiles examples without actually including the CopyFiles function.
=> sampleext PackageScript: Add missing CopyFiles function.

core/smn_entities.cpp
This var is only used when setting a direct string, rather than a string_t. Some flawed
logic was causing it to only be set if the sendprop didn't have a proxy function (although
all strings should; that's how we detect whether it's a string_t or not). The var only needs
to be set if it's not a string_t, but does not hurt anything if it is.
=> Fix maxlen in SetEntPropString not being initialized (bug 6391).

core/logic/smn_timers.cpp
Don't try to call the timer callback, if it's not runnable.
Error wasn't reported before the exception refactoring. This reproduces the old behavior of just keeping the timer running and trying to call the callback until it's available again.
A better approach would be to stop all timers completely, if the plugin isn't going to change to running again from that paused state or just remove that pause state completely :+1:
=> Fix calling timer callback in paused plugins

core/logic/smn_filesystem.cpp
This only affects plugins compiled before the param existed in the includes. NULL defaults to "GAME"
on some engine versions, but is invalid on others, causing any file to not be found.
=> Make path id default to "GAME" instead of NULL for FileExists and FileSize if param missing.

AMBuildScript
On Clang 3.6, a warning is thrown if you use the override keyword on some virtual members in a class but not all. While consistency is great, I don't think that having this break the build is worth it. (Alternatively, we can update the code in all cases were this matters).
=> Fix build on Clang 3.6.

core/NextMap.cpp
I've had a plugin that iterates GetMapHistory for quite a while, seeing the list limited to 20 entries when the server is running for over a month saddens me :(
=> Allow GetMapHistorySize to return numbers greater than 20.

core/HalfLife2.cpp, core/HalfLife2.h, core/smn_halflife.cpp, plugins/include/halflife.inc
I dislike the FindMap API we have greatly because we're asking users to create a new buffer, fill it, and then pass it to FindMap to determine if the user input is valid. We don't have any other APIs like this, and it turns into a whole thing everytime this native is to be used. Internally we have the exact same pattern and we throw away the result...
The alternative I'm proposing is the top, bottom being present.
```native FindMapResult FindMap(const char[] map, char[] foundmap, int maxlen);```
```native FindMapResult FindMap(char[] map, int maxlen);```
This is only compile tested.
=> Change FindMap to take a const char* for searching instead of char*.

core/sourcemm_api.cpp
This gross slab of hackeroni ensures that we get the latest (for now) engine iface available on TF2-branch games (including CS:S, DoD:S, HL2:DM, and SDK 2013 mods), so that we don't grab some older shim of an iface (causing our hooks to not fire).
This should allow seamless functionality now for TF2, both before and after the impending updates for CS:S, DoD:S, and HL2:DM, as well as both SDK 2013 mods that have updated to the newer iface and those that haven't.
=> Shim for TF2-branch games to find latest, non-shimmed engine iface.

core/ConCmdManager.cpp
Can't use RETURN_META when no hooks are on the stack. No hooks will ever be on the stack here. I don't know why I added these.
=> Fix a regression from the ConCmdManager refactoring that causes a crash using SourceMod commands in the server console.

extensions/tf2/extension.cpp
I had a null pointer crash in FindEntityByNetClass
https://github.com/Thordin/sourcemod/blob/3a59baab2c899a749d3d6d7f1d0906f75a8ad53d/extensions/tf2/extension.cpp#L429
I found the same function here except they added an IsFree() check on the edict, so maybe that was the problem.
https://github.com/alliedmodders/sourcemod/blob/master/extensions/sdktools/gamerulesnatives.cpp#L43
=> Added IsFree() edict check to FindEntityByNetClass

public/smsdk_ext.cpp
We already did this in core, and it's not relevant to any supported games yet except for any 2013 mods that have updated to the new SDK since we haven't updated our hl2sdk-sdk2013 yet.
On TF2-branch games, always look for engine v23, and fallback to v22 if not available. Their vtable layouts are compatible with the only differences being 23 possibly having more functions at the end, and the behavior of IsMapValid being different. This ensures continued compatibility with CS:S, DoD:S, and HL2:DM are their sync happening soon, as well as with any SDK 2013 mods that have or have not updated to the latest 2013 SDK, before or after we update our copy of it.
=> Update metamod-attached extensions to use same engine ptr lookup as core

core/HalfLife2.cpp
This slimey hunk of hackeroni ensures that we get the "classic" IsMapValid behavior for games (other than TF2) that are on the TF2 branch, including CS:S, DoD:S, HL2:DM, and SDK 2013 mods.
The newer behavior is to have a relative (or maybe full?) map path as input, rather than just the map name. Since the rest of our logic only expects the map name, including on all other games, this normalizes that. It would also be necessary for TF2 if we weren't bypassing IsMapValid altogether and going through FindMap.
=> Fix IsMapValid call on non-TF2 TF2-branch games to use old behavior requiring only map name

core/smn_console.cpp
This is a fix for [Bug 6405](https://bugs.alliedmods.net/show_bug.cgi?id=6405)
Simply put, this patch gets rid of `ConVar_BoolValue_set`, `ConVar_FloatValue_set`, and `ConVar_IntValue_set`.
Instead, it uses `sm_SetConVarNum` and `sm_SetConVarFloat` directly.
However, so we don't cause issues with pre-OrangeBox games,  the above two functions and `sm_SetConVarString` now check if `params[0]` (the parameter count) is >= the parameter number before using params 3 (replicate) and 4 (notify).
=> Fix ConVar .IntValue, .BoolValue, and .FloatValue assignments (Bug 6405)

core/logic/NativeOwner.cpp, core/logic/NativeOwner.h, core/logic/PluginSys.cpp, core/logic/PluginSys.h, core/logic/ShareSys.cpp, core/logic/ShareSys.h, core/logic/Translator.cpp, core/logic/Translator.h, core/logic/smn_fakenatives.cpp
This is a general cleanup, separated into a few commits for reviewability.
1. UnloadPlugin is now split up into an outer function and inner. The outer function just determines whether or not the unload can actually occur yet.
2. Dependency links were not formed correctly. The cache to optimize their creation was bogus in multiple ways, which has been fixed.
3. Dependency links were not created for library-only dependencies. That has been fixed.
4. The CPlugin class got some visual cleanup (organizing member variables, using AutoPtr, etc).
5. Plugin info is now stored in SH::String for safety. Requesting the info struct now taps into those strings instead of the runtime. This will let us persist info across unloads.
=> Cleanup some PluginSys idiosyncracies.

extensions/cstrike/forwards.cpp, extensions/cstrike/natives.cpp, plugins/include/cstrike.inc
This simply adjusts the reason to match real value to the include one and vice versa for values coming from plugins.
=> Add shim for TerminateRound for  CS:GO

core/HalfLife2.cpp, core/HalfLife2.h, core/smn_halflife.cpp, plugins/basetriggers.sp, plugins/basevotes.sp, plugins/basevotes/votemap.sp, plugins/include/halflife.inc, plugins/mapchooser.sp, plugins/nextmap.sp, plugins/nominations.sp, plugins/randomcycle.sp, plugins/rockthevote.sp, plugins/testsuite/mapdisplayname.sp
This replaces Pull Request #350.
This adds a new native named GetMapDisplayName.
Its purpose is to get the base name of a workshop map for display in various plugins.
At the present time, only CS:GO and TF2 actually do anything.
Its signature is 
native bool GetMapDisplayName(const char[] map, char[] displayName, int maxlen);
This function returns false if a map can not be found or resolved, but true in all other circumstances (even for non-workshop maps).
No matter what it returns, displayName will always be populated, even if it is just by copying map to displayName.
The return type can be modified from its current behavior if needed.  Its current behavior was me being lazy.
The changes to core plugins are to implement both GetMapDisplayName and FindMap.
The plugins updated are:
* …
=> GetMapDisplayName and associated core plugin changes

AMBuildScript
The Source 1 version of Dota 2 is no longer downloadable or supported by Valve.
I don't know if we're ready to rip out the special-cased code for it or not yet, but we can at least stop spending build time on it.
=> Stop building Source 1 Dota 2 build.

core/ConCmdManager.cpp, core/ConCmdManager.h, core/ConVarManager.cpp, core/ConVarManager.h, core/ConsoleDetours.cpp, core/CoreConfig.cpp, core/GameHooks.cpp, core/HalfLife2.cpp, core/HalfLife2.h, core/NextMap.cpp, core/PlayerManager.cpp, core/concmd_cleaner.cpp, core/concmd_cleaner.h, core/smn_console.cpp, core/smn_halflife.cpp, core/sourcemm_api.cpp, core/sourcemm_api.h, extensions/sdktools/vglobals.cpp
Our SourceMod builds require Metamod:Source 1.8 or higher.
Until now, it was still possible for users to build their own SourceMod against Metamod:Source 1.6 or 1.7. Quite a lot of code is dedicated to making this work, since the legacy API in those versions is missing a ton of stuff (notably, SourceHook VP hooks). Let's just kill all that off, since MM:S 1.8 was released in 2009.
=> Remove code that handles long-dead Metamod:Source versions.

extensions/tf2/holiday.cpp, gamedata/sm-tf2.games.txt, plugins/include/tf2.inc
Valve added a new holiday in the Invasion update.
It's Holiday 4, CommunityUpdate.
This is the update s_HolidayChecks:
.rodata:010A92C0 _ZL15s_HolidayChecks dd offset _ZL19g_Holiday_NoHoliday, offset _ZL21g_Holiday_TF2Birthday
.rodata:010A92C0                                         ; DATA XREF: _Z28EconHolidays_IsHolidayActiveiRK6CRTime+Br
.rodata:010A92C0                                         ; _Z32EconHolidays_GetHolidayForStringPKc:loc_659C80r ...
.rodata:010A92C0                 dd offset _ZL19g_Holiday_Halloween, offset _ZL19g_Holiday_Christmas
.rodata:010A92C0                 dd offset _ZL25g_Holiday_CommunityUpdate, offset _ZL22g_Holiday_EndOfTheLine
.rodata:010A92C0                 dd offset _ZL23g_Holiday_ValentinesDay, offset _ZL21g_Holiday_MeetThePyro
.rodata:010A92C0 …
=> Add Community Update holiday

plugins/include/dbi.inc
DBResultSet.IsFieldNull has an extra parameter that shouldn't be there(That parameter is the one that should be the automatically inserted first "this" param)
Also exists in SM 1.7
=> Fixed DBResultSet.IsFieldNull

AMBuildScript, core/logic/thread/PosixThreads.cpp, core/logic/thread/WinThreads.cpp
Just moving things into helper function so configure() isn't like 500 lines long. Also droped special cases for long-dead compiler versions.
And updated AMTL since the pinned version didn't build on gcc-4.8.
=> Refactor and cleanup the AMBuildScript a bit.

plugins/include/dbi.inc
Basically, this changes SQLTxnSuccess to be a typeset that allows DBResultSet[] in addition to Handle[] so that the compiler doesn't toss tag mismatches at you when you try doing this.
While I haven't done runtime tests on it, the documentation seems pretty clear that the Handle array is full of DBResultSets.
=> Allow SQLTxnSuccess to use DBResultSet[] in addition to Handle[]

tools/buildbot/upload_symbols.py
Parse FILE records to find on-disk git repos, include root/remote/rev as an INFO record.
```
INFO REPO 60f878f132b3167efda42bd9400282f707918291 https://github.com/alliedmodders/metamod-source /home/asherkin/Code/metamod-source
INFO REPO 4be998c4dc3185b80e716c7b44fb30b4c221fcb6 https://github.com/alliedmodders/sourcemod /home/asherkin/Code/sourcemod
INFO REPO c35532ced5e7e4f882106857bfae8f3db0fbacf0 https://github.com/alliedmodders/amtl /home/asherkin/Code/sourcemod/public/amtl
INFO REPO c4237cc89cd769e999357300e57e4f53fef6983e https://github.com/alliedmodders/hl2sdk /home/asherkin/Code/hl2sdk-tf2
INFO REPO 8dd90b35890786441931dfe6622ea97fa99dbc27 https://github.com/alliedmodders/sourcepawn /home/asherkin/Code/sourcemod/sourcepawn
```
I fully admit that this code is horrible, but it is …
=> Include repo information in symbol files

tools/ida_scripts/makesig.idc
https://github.com/alliedmodders/sourcemod/commit/56339ed43aa137f841b884da2f6e5987cdda560d
This resolves makesig.idc printing 0x mistakenly before 0F when an instruction is prefixed with 0F.
=> NPOTB: Remove 0x prefix from two-byte instructions.

core/logic/Database.cpp, core/logic/Database.h, core/logic/PluginSys.cpp, plugins/include/core.inc, public/IPluginSys.h
IPluginsListener::OnPluginUnloaded API runs *after* plugins receive OnPluginEnd(). Since that's supposed to be the last callback in the plugin, it is an unspoken rule that extensions and listeners should not call into plugins at this stage.
Database.cpp of course breaks this rule: it can callback into plugins that think they're finished, which can cause unexpected state in the plugin and within SourceMod. This is particularly dangerous if a callback does something strange like adds a new ConVar: state that was removed in a different OnPluginUnloaded callback could now be revived, leaving leaks or danging pointers around SourceMod.
The easy fix for this, of course, is to just add a callback that fires *before* OnPluginEnd(). (Arguably, a partial fix is that OnPluginDestroyed is a better …
=> Fix race between plugin unload and asynchronous query completion.

plugins/include/entity.inc
These have had sane alternatives for ages now that still cover any use case they were actually useful for (via the optional local_offset param) and are consistently misused by people that really want the computed offset.
Also toss in a HasEntProp stock to cover the most common use case for all 4 of these functions.
Actually useful diff:
```
diff --git a/plugins/include/entity.inc b/plugins/include/entity.inc
index a1603b1..7592a96 100644
--- a/plugins/include/entity.inc
+++ b/plugins/include/entity.inc
@@ -403,17 +403,13 @@ native SetEntDataString(entity, offset, const String:buffer[], maxlen, bool:chan
* @param prop			Property name.
* @return				An offset, or -1 on failure.
*/
+#pragma deprecated Use FindSendPropInfo() instead. The local_offset if you actually want the local offset. …
```
=> Deprecate FindSendPropOffs and FindDataMapOffs

core/HalfLife2.cpp, plugins/testsuite/findmap.sp
On CSGO, workshop maps use the path separator.  GetMapDisplayName didn't take this into account.
TF2 always uses `/`
While I was at it, I converted ke::SafeSprintf calls to ke::SafeStrcpy for items that just used the %s pattern.
This has been tested and appears to be working correctly in the following environments: TF2 Linux, CSGO Linux, TF2 Windows, and CSGO Windows.
I also fixed a few issues in the testsuite/findmap.sp as it was still using the old FindMap syntax and didn't quite have a long enough resultName.
=> Update GetMapDisplayName to use platform separator on CSGO

extensions/sdktools/hooks.cpp
This corrects a potential oops if a file is being sent to another client when a packet is received from a different client. Last minute rejigging caused this unfortunately.
=> Use present netchannel instead of cached netchannel in CHookManager::SendFile.

core/logic/smn_players.cpp
While we could use blank which will solve the worst of the problems without the perf hit, I think it is worth directly addressing this. Hopefully respecting the STEAM_ID_PENDING / STEAM_ID_BOT format will play nice with other code.
@psychonic
=> Pre-fill buffer for GetClientAuth*

core/logic/ExtensionSys.cpp
This one is kind of nasty - it still leaves the failed ext in the libs, but is the sanest way to fix the crash without actually implementing `CExtensionManager::AddDependency` properly.
ShareSys has a couple of things that are designed to cleanup automatically on unload (rather than having a deregistration function that the extension is meant to call on unload) - this was not being done for autoloaded dependencies that failed to load, which could result in bad interface ptrs being left around. Instead, clean up immediately whenever any ext fails to load rather than waiting until unload time.
AFAICT, there is no downside to this change.
=> Fix crash on failing to load dependent extension.

plugins/include/sdktools_sound.inc
New prototype was added in PR #247 
This fixes compilation of plugins that are using pre-1.8 sound hook prototypes.
=> Converted NormalSHook to typeset and added old prototype.

extensions/sdkhooks/extension.cpp, extensions/sdkhooks/extension.h, gamedata/sdkhooks.games/engine.ep2v.txt, gamedata/sdkhooks.games/game.fof.txt, plugins/include/sdkhooks.inc
Not many games support this, but it is in the SDK (and thus likely in many mods). This is also already an often used feature in TF2, provided by an unsupported extension that breaks often (using a different method to hook).
I don't know offhand of other games/mods that support this, but it's trivial to add the offset when finding one.
=> Add support for hooking CanBeAutobalanced to SDKHooks.

core/logic/GameConfigs.cpp
Print a message to console when there is a gamedata file loaded from the
|custom| folder.
This can act as a reminder, that there is a custom gamedata file which currently overrides some values.
=> Add info message when loading custom gamedata

plugins/include/adt_trie.inc
Seems like it's been missing for years. The methodmap is fine.
=> Add missing |bool| return tag to RemoveFromTrie native

plugins/include/testing.inc
Not sure if the args to AssertEq would be better off with a ``any:`` tag instead of as an int.
Also made them stocks so users don't get warnings about unused functions when then ``#include <testing>``.
=> Update sourcepawn testing include to new syntax.

AMBuildScript
@asherkin 
Partial fix for https://github.com/Source-Python-Dev-Team/Source.Python/issues/101
(Source.Python will need the same or similar fix applied as well)
=> Don't export (all) symbols from included static lib on Linux/Mac.

plugins/include/menus.inc
The methodmap method got a bad return tag. The old function is fine.
=> Change Panel.DrawItem return tag to |int| (bug 6463)

core/PlayerManager.cpp
See bug 5529.
The Source SDK 2013 and Black Mesa Source engines need the same fix as TF2 & friends, due to being on a similar engine branch.
@Fyren
=> Fix SourceTV bot detection on Source SDK 2013 mods and BM:S.

extensions/sdktools/gamerulesnatives.cpp
This gave us a lot of grief with our stop that tank mod. Eventually a TF2 update made the crashes reliable enough that I was able to track down the root of the problem:
`GameRules_SetProp("m_bPlayingHybrid_CTF_CP", true, 4, 0, true);`
`*(bool *)((intptr_t)pProxy + offset) = (params[2] == 0) ? false : true;`
It makes no sense to directly set the value on CTFGameRulesProxy. Anytime the game makes a change to CTFGameRules, it calls CGameRulesProxy::NotifyNetworkStateChanged which then runs the equivalent of CBaseEdict::StateChanged(). It should be sufficient enough to mark the offset as changed so I left that portion unchanged. I've tested this and my client gets the change immediately.
I've looked at both the CTFGameRules and CTFGameRulesProxy pointers in memory and their class structure …
=> Fix for crashes related to the GameRules_Set* natives.

plugins/include/tf2.inc
I don't know the other conds before, but 114 is for the spawn outline.(added in gun mettle update).
=> Update tf2.inc TFCond enums

plugins/include/clients.inc
I encountered a 
>  Native "GetClientSerial" reported: Client index 0 is invalid
With the clients.inc not saying it could throw errors.
=> GetClientSerial does not have @error documentation

core/logic/ExtensionSys.cpp
Typo which will print the name of the extension being unloaded instead
of the one which would be unloaded as well because of it.
=> Fix printing dependent extension name on unload

core/logic/PluginSys.cpp, core/logic/PluginSys.h
When unloading a plugin no plugin is allowed to execute code. There's
been some flawed logic in the scheduling, leading it to bail out if the
plugin was marked for scheduled unloading..
Also change the "error" message of `sm plugins unload` to something
nice.
=> Fix scheduled plugin unloading

configs/core.cfg, core/HalfLife2.cpp, core/HalfLife2.h, core/smn_entities.cpp, extensions/sdktools/extension.cpp, extensions/sdktools/extension.h, extensions/sdktools/vnatives.cpp
There's room to make this more robust, performant, stringent, etc., however I would like to get _something_ in place sooner than later as more users are receiving account-wide Game Server Login Token bans and having trouble figuring out why.
From testing, this appears to work as desired.
Please let me know if you see any glaring bugs or deal-breakers here.
@asherkin 
@Drifter321 
Further improvements are welcome after the initial version has landed.
=> Add initial version of safety checks for CS:GO to attempt to avoid user GSLT bans.

extensions/sdktools/gamerulesnatives.cpp, plugins/include/sdktools_gamerules.inc
This is a follow up to https://github.com/alliedmodders/sourcemod/pull/473#issuecomment-179506496.
Essentially, it forces changeState to true for all the GameRules_SetProp* natives. This brings the behavior in line with that of the SetEntProp* natives. I can't find a use case for not marking the offsets as changed. That just means that clients won't see the change until the game logic happens to change another game rules property, calling StateChanged().
=> Always send changes when using the GameRules_SetProp* natives.

core/HalfLife2.cpp, core/HalfLife2.h, core/logic/AMBuilder, core/logic/smn_halflife.cpp, core/logic/smn_players.cpp, core/sm_globals.h, plugins/include/halflife.inc, public/IGameHelpers.h
This has been requested a few times and isn't too bad to add.
It could have been done simpler, but this leaves a segue to move more natives to the logic bin.
=> Add support for retrieving game server Steam Id (bug 6404).

AMBuildScript
Most supported games don't even support this case, but at least CS:GO does. WIthout
this fix, some filesystem calls can fail, or in the case of readdir, fail to return all/any files.
This was first observed when using an XFS-formatted volume on CentOS 7 x64.
@asherkin
=> Allow support for running on filesystems that use 64-bit inodes on Linux.

core/EventManager.cpp
This avoids issues from confusion that users have, returning Plugin_Changed
after altering event data, when Plugin_Changed isn't required and wasn't supported
in that scenario, and instead acted like Plugin_Handled.
=> Allow Plugin_Changed return on event PreHooks to not block.

core/EventManager.cpp, core/EventManager.h, core/PlayerManager.cpp, core/PlayerManager.h, core/smn_events.cpp, plugins/include/events.inc
I also initially planned on adding support for blocking existing events, per client on-the-fly, but API was getting complex and potentially inefficient. (This can still be added at some point). The net effect of that can still be achieved by blocking existing events with a prehook, saving event data, and then resending to the desired clients (not ideal, but doable).
Only tested on TF2 in Windows
=> Add support for sending gameevent to specific client.

extensions/sdktools/trnatives.cpp
When the global trace handle is used for this, the containted entity pointer can be stable. This adds separate storage of an SM entity reference. Also fixed it to return -1 as documented when there is no entity and using trace handle, rather than returning 0/world.
=> Fix late/incorrect calls to TR_GetEntityIndex potentially causing crash.

core/logic/PluginSys.cpp, core/logic/PluginSys.h
It's not too different from P-M's patch in the end.  Does a little better with some edge cases of multiple reloads of the same thing or an unload and then reload at the same time.  Also prints the load error if there is one where SM didn't before.
=> Better plugin reloads.

core/logic/stringutil.cpp
UTIL_ReplaceEx returns a pointer to the character after the newly-replaced stuff.  While maxlength is the size of the original buffer, the remaining space left needs to get reduced by how far forward we jumped after a replace happens.
=> Fix UTIL_ReplaceAll not properly tracking length (6472)

plugins/playercommands/rename.sp
**Before the change:**
sm_rename @all "Random Name" - this would rename everyone but the names would be randomized (random characters and numbers)
**After the change:**
sm_rename @all "Random Name" - this would rename everyone to: Random Name 1, Random Name 2, Random Name 3 ...  etc.
**Description:**
sm_rename can only rename 1 player at a time, when you specify a name. If you use this command on multiple players (like sm_rename @bots "A random bot"), their names get randomized(just like when you dont specify a name). So I propose this change, so you can rename multiple people.
**PS:**The funny thing is that there was a comment in the code about not wanting everyone to have a same name, but sm_rename doesnt a have check for this so you could use sm_rename to rename everyone, one by one, …
=> Renaming multiple players

extensions/topmenus/TopMenu.cpp, extensions/topmenus/TopMenu.h
The buffer for menu options was 64 chars. That limit can easily be
reached by some utf8 string which would get truncated. Double the buffer
size to 128 chars.
=> Increase topmenu display buffer size

core/logic/NativeOwner.cpp, core/logic/ShareSys.cpp
Bug 6518
Starting from no plugins loaded, after the final step of the following,
basetriggers will be marked as errored because mapchooser is missing:
Load basetriggers
Load mapchooser
Unload mapchooser
Load mapchooser
Unload mapchooser
We lose the SP_NTVFLAG_OPTIONAL when removing a WeakNative. The
__pl_mapchooser_SetNTVOptional() is only called in basetriggers when it
is loaded. It adds the OPTIONAL flag to the mapchooser natives the
basetrigger plugin uses.
When mapchooser is loaded, the native is overwritten and the OPTIONAL
flag consumed (WeakNative registered), but not preserved. Later when
mapchooser is unloaded the WeakNative is removed in
CNativeOwner::UnbindWeakRef, but the OPTIONAL flag isn't added again.
The next time mapchooser is loaded, the natives aren't optional anymore …
=> Keep optional natives optional after reloading

plugins/nominations.sp
sm_nominate (/nominate and !nominate) was returning Plugin_Continue when a map was successfully nominated.
This should be Plugin_Handled.
=> Fix /nominations returning Plugin_Continue on success

core/logic/smn_database.cpp, core/logic/smn_string.cpp, core/logic/sprintf.cpp, core/logic/sprintf.h, core/logic/stringutil.cpp, core/logic/stringutil.h, extensions/sqlite/driver/SqDatabase.cpp, plugins/include/dbi.inc
Probably best to look at this one commit-by-commit.
Will need some doc work on the wiki after landing.
The gist of it is that if formatting via the new native, "%s", "%N", "%L" etc are automatically escaped unless a new "!" flag is set (i.e. "%!s"), and an error is thrown if the string is going to be truncated (to avoid leaving a trailing escape character).
Old:
```
char name[MAX_NAME_LENGTH];
if (!GetClientName(client, name, sizeof(name))) {
return false;
}
int safeNameLen = (strlen(name) * 2) + 1;
char[] safeName = new char[safeNameLen];
db.Escape(name, safeName, safeNameLen);
char steamId[32];
if (!GetClientAuthId(client, AuthId_Steam2, steamId, sizeof(steamId))) {
return false;
}
int safeSteamIdLen = (strlen(steamId) * 2) + 1;
char[] safeSteamId = new char[safeSteamIdLen]; …
```
=> Implement an auto-escaping Format native for SQL query construction

core/logic/DebugReporter.cpp
This fixes a hard blocker for 1.8 from https://github.com/alliedmodders/sourcemod/pull/448.
=> Fix erroneous () in DebugReport:: printouts.

extensions/clientprefs/query.cpp, extensions/clientprefs/query.h, extensions/sqlite/driver/SqDatabase.h, extensions/sqlite/driver/SqDriver.cpp, extensions/sqlite/driver/SqDriver.h
When the server crashed and the process got terminated, the SqDriver
instance was killed first (e.g. by atexit). SqDatabase tries to access
SqDriver in its destructor.
This patch tells SqDatabase to not use anything from SqDriver anymore
after SqDriver got destroyed.
Next to that, the clientprefs extension relied on the IDatabase pointer
being valid to get the driver pointer. Cache the pointer, so the dbi
system still knows the IDBThreadOperation belonged to the now gone
driver, even after the database object is gone.
=> Fix use-after-free crash in SQLite extension

core/logic/ForwardSys.cpp, core/logic/smn_database.cpp
This avoids spam of "Plugin not runnable" exceptions on shutdown or
plugin unload.
When re/unloading a plugin which has other ones depending on it, like
the adminmenu, It pauses the depending plugins putting them in an
"Depends on plugin: %s" error state. ForwardSys doesn't remove them from
the forward lists on pause, specially the global forwards, and still
tries to call all the global forwards like OnPlayerRunCmd and
OnLibraryAdded etc. on the paused plugins. Executing functions in paused
runtimes has been ignored in the VM before introducing the "Exception"
mechanism, but now they're all logged.
This adds checks to make sure the plugin is runnable before calling a
function. (Stolen from #438)
=> Don't try to call functions in paused plugins

configs/core.cfg, core/ChatTriggers.cpp, core/ChatTriggers.h
Special characters only, minus a couple of potentially-problematic characters.
Technically this is a breaking change - but anyone using multi-char triggers is probably crazy anyway and has been driven off by now.
Not tested yet, here for feedback, etc, etc.
=> Allow setting multiple chat trigger characters

plugins/include/usermessages.inc
Fixed wrong return type in UserMessageToBfRead
=> Fixed wrong return type in UserMessageToBfRead

core/PlayerManager.cpp, core/PlayerManager.h
This was always an issue, if the CSteamID was updated by the game, and the engine string hadn't changed; we wouldn't update our values. This was triggered by yesterday's CS:GO update which, similar to ashers work from years ago in SM, added a validate param to GetClientSteamID.
=> Check multiple engine sources for updated AuthIDs.

plugins/compile.sh
The only "confusing" part now is that extra newline between the copyright and header size.
Formatting has also been updated to match the majority of the file (no `;`).
Some output (ignore the fact that I'm using 1.5.1-this is a testing directory just to make sure things compile):
>Compiling basechat.sp ...
SourcePawn Compiler 1.5.1
Copyright (c) 1997-2006, ITB CompuPhase, (C)2004-2008 AlliedModders, LLC
>Header size:           3044 bytes
Code size:            10684 bytes
Data size:             3460 bytes
Stack/heap size:      16384 bytes; Total requirements:   33572 bytes
>Compiling basecomm.sp ...
SourcePawn Compiler 1.5.1
Copyright (c) 1997-2006, ITB CompuPhase, (C)2004-2008 AlliedModders, LLC
>Header size:           4296 bytes
Code size:            17004 bytes
Data size: …
=> Actually add spacing to compile.sh

core/logic/DebugReporter.cpp
SourceMod itself and thirdparty extensions call functions in plugins
without making sure it is runnable. The plugin pausing feature isn't
supported anymore and is set to get nuked #438 which will reduce the
amount of not-runnable error reports.
We can't fix every third party extension, so suppressing the error from
the logs will stop the spam until pausing is removed.
#489 can be reverted after this.
=> Suppress logging of "Plugin not runnable" errors

public/CDetour/detours.h
Add more macros for up to 8 parameters, because DETOUR_DECL_MEMBER8 is
the highest one yet.
=> Add DETOUR_DECL_* marcos for more parameter counts

tools/ida_scripts/makesig.idc
This fixes the error: `makesig.idc:47: No such attribute: object.Op0`
Apparently this scripting language doesn't support short-circuit evaluation, so the not-null check in this (`pInfo.n == 1`) case has to be nested in `if` statements.
=> Update IDA makesig script

extensions/cstrike/timeleft.cpp
Round end reasons in CS:GO are +1 from the ones in CS:S. The
CSRoundEnd_GameStart reason for when the OnMapTimeLeftChanged forward
should be called should be one higher than in CS:S.
=> Fix case of not calling OnMapTimeLeftChanged in CS:GO

core/logic/DebugReporter.cpp
This is a backport of #558 to the 1.8 branch.
Since we can't really easily change the VM in 1.8 anymore (right?), this does a string comparison against the error message to know what to suppress. Also tries to not suppress errors manually generated by plugins which happen to start with the same phrase.
=> Suppress logging of "Plugin not runnable" errors in SM 1.8

core/logic/smn_database.cpp
Plugins were able to close the results handle in the threaded query
callback causing a double free crash. The access rights are setup right
before the handle is created, but weren't used.
=> Fix threaded query's result handle access rights

core/logic/CellArray.h, core/logic/smn_adt_array.cpp
If there is not enough memory to clone an array, throw an error instead
of crashing the server.
=> Fix crash in CloneArray for too large arrays

plugins/basechat.sp
Fix for CS:GO not showing the sm_msay exit button
mSayPanel.CurrentKey = 10:
mSayPanel.CurrentKey = 9:
=> Change sm_msay behavior to use GetMaxPageItems instead of hardcoded values

core/HalfLife2.cpp
The source 2013 handler for TextMsg expects five strings in the message here: https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/client/hud_chat.cpp#L124
Because sourcemod doesn't send the last four strings along each message sent from sourcemod triggers an assert in tier1/bitbuf.cpp if the game is not built with RELEASE.
=> Fix incomplete TextMsg packet

core/smn_events.cpp
This removes a couple of checks that are IMO unnecessary. See commit messages for details and reasoning.
=> Event.FireToClient fixups

extensions/regex/extension.cpp
"x" is never deleted when compile fails.
=> Fix memory leak in Regex extension.

core/logic/smn_database.cpp
If one of the queries fails in a transaction, the DBI system would only
allocate an array of the size of the amount of all the successful
queries before the failed one.
It writes data for all the queries though effectively writing past the
array bounds leading to heap corruption.
Create the right sized array!
=> Fix crash when database transaction fails (bug 6531)

core/MenuManager.cpp
The "Back" slot was hidden even if the page had a "Next" button. Draw the spacer correctly!
=> Fix typo in menu manager not drawing a spacer

core/smn_entities.cpp, plugins/include/entity.inc
As discussed [here](https://forums.alliedmods.net/showthread.php?t=293554), there is no intuitive way to read an output's value. While the output object exists in the datadesc, it has a currently-unsupported type of FIELD_CUSTOM, as it is an object. The value is stored in a variant_t as the first variable on the object, making it easy to get at.
The code is admittedly a mess, but no more than the existing ent prop code. Welcome back to macro hell.
=> Add support for getting and setting output variables with Get/SetEntProp*

core/smn_entities.cpp
Regression in #583
The `CBaseHandle *` was compared to a `IHandleEntity **` always failing
instead of comparing the actual base handles.
Fixes a small typo in MatchTypeDescAsInteger too, where a FIELD_CUSTOM
could fall through badly.
=> Fix regression with GetEntPropEnt always returning -1

core/logic/smn_adt_array.cpp, core/logic/smn_adt_stack.cpp, plugins/include/adt_array.inc, plugins/include/adt_stack.inc
Add GetArrayBlockSize and GetStackBlockSize and equivalent properties to
the methodmaps to get the blocksize the array or stack was created with.
Useful when getting array handles from other plugins you didn't create
yourself.
=> Add ADT array blocksize getter

core/HalfLife2.cpp
Sometime during 2016, CS:GO was updated so that the long form of workshop paths work on Windows using either `/` or `\`  i.e.
changelevel workshop/125499116/de_inferno_se
will properly change to Inferno SE on a Windows machine, assuming the map is downloaded.
I haven't checked to see if `pHelperCmd->AutoCompleteSuggest` (called from FindMap) is also affected by this change, although it shouldn't actually matter.
This pull request changes GetMapDisplayName to stop looking just for the system's path separator.  Now it looks for / first and if that fails, looks for \ instead.
Side note: As I no longer have a Linux machine and only have VS2015 and 2017RC installed, I had no way to actually compile this to test it.  However, it's not a very complex change as it's just changing `(blah) != NULL` …
=> Make CS:GO recognize both / and \ for GetMapDisplayName

extensions/sdktools/extension.cpp
This makes it so sm_kick @spec and other commands don't target replay and sourcetv. This is a side effect from a change to calling disconnect for bots instead of kickid.
=> Ignore replay and sourcetv in @spec targeting.

extensions/sdktools/gamerulesnatives.cpp
If the gamerules proxy entity doesn't exist, don't try to generate the reference for it.
https://forums.alliedmods.net/showthread.php?t=294762
=> Fix crash when accessing gamerules during mapchange

plugins/basecommands/map.sp, plugins/mapchooser.sp
sm_map now makes use of GetMapDisplayName in the same way that sm_setnextmap did in #354 
sm_map and its menu now use PLATFORM_MAX_PATH for map name buffer size instead of 64
~~nominations has a new message for when a map is found, but not available in the nominations pool (to differentiate it from the map not being found at all)~~
sm_setnextmap now uses ShowActivity2
=> Update sm_map behavior to better reflect FindMap/GetMapDisplayName results

gamedata/core.games/common.games.txt
"engine" doesn't work here. It should be "game". #598
=> Fixed typo on previous PR

core/HalfLife2.cpp
This is a reworking of the issue identified in https://github.com/alliedmodders/sourcemod/pull/594/
Instead of doing specific character and string substitutions based on the game, we should just be defensive and do it for every game.
=> Change CHalfLife2::GetMapDisplayName to always check for string substitutions.

plugins/include/files.inc
Small typo I noticed when looking at the docs.
=> Fix typo in file.inc include

plugins/include/datapack.inc
The `int bytes` parameter is mentioned in the docs but was missing from the prototype.
Copy&Paste heros!
=> Add missing parameter to DataPack.IsReadable

AMBuildScript, core/AMBuilder, extensions/mysql/AMBuilder, public/sm_platform.h
Cherry picked commit 416abd8 from master, which never landed on 1.8-dev. Fixes building SM 1.8 on VS2015 and VS2017.
=> [1.8] Add support for compiling with VS2015.

core/PlayerManager.cpp, core/PlayerManager.h, core/logic/smn_players.cpp
Cache IClient pointer on clients, since it's also used for per-client events, not just when kicking.
Support bot IClient lookups for SDK 2013 mods that are on latest engine.
Remove unsafe kick queue bypass for bots.
=> Kick fixes

core/smn_keyvalues.cpp
In KeyValues.SetUint64, when reading the uint64 value from SP, we were only reading a cell_t worth of data, and then casting that as a uint64.
=> Fix KeyValues.SetUInt64 truncating value (#635).

core/logic/ForwardSys.cpp, core/logic/ForwardSys.h, core/logic/smn_core.cpp, core/logic/smn_fakenatives.cpp, core/logic/smn_functions.cpp, plugins/include/core.inc, plugins/include/functions.inc, public/IForwardSys.h
Until now the only use for the `NULL_VECTOR` and `NULL_STRING` pubvars was to pass them to C++ natives for them to be able to skip some work if the callee isn't interested in the results. Plugins themselves couldn't use them for that purpose or anything else at all.
These patches add support for plugins to use them in the same manner as an extension could.
`IsNullVector` and `IsNullString` can be used to check if the `NULL_VECTOR` or `NULL_STRING` was passed as a function/forward argument.
`IsNativeParamNullVector` and `IsNativeParamNullString` can be used to see if someone passed the NULL pubvars when calling your native.
`Call_PushNullVector` and `Call_PushNullString` allow you to call any function or forward and pass the NULL pubvars, which can be checked with the above natives. …
=> Add natives to check for NULL_VECTOR and NULL_STRING

core/logic/ForwardSys.cpp, core/logic/ForwardSys.h, core/logic/smn_core.cpp, core/logic/smn_fakenatives.cpp, core/logic/smn_functions.cpp, plugins/include/core.inc, plugins/include/functions.inc, public/IForwardSys.h
Reverts alliedmodders/sourcemod#606
This broke extension API due to `IChangeableForward` inheriting from `IForward`.
`IForwardManager::IsVersionCompatible` needs to be changed to mark bcompat as broken here to re-merge.
=> Revert "Add natives to check for NULL_VECTOR and NULL_STRING"

gamedata/sdktools.games/engine.csgo.txt, gamedata/sm-cstrike.games/game.csgo.txt
This should fix the HandleCommand_Buy_Internal detour, as well as most crashes.
GetWeaponInfo is still broken, might need some more work.
=> Fix (parts of) CS:GO gamedata

tools/buildbot/generate_headers.py
This is to avoid line breaks in sourcemod_version_auto.h which occur in rare cases when tag is empty.
At least I got this on compiling using Bash on Windows.
Without this fix, I got a sourcemod_version_auto.h which looks like this:
```
#ifndef _SOURCEMOD_AUTO_VERSION_INFORMATION_H_
#define _SOURCEMOD_AUTO_VERSION_INFORMATION_H_
#define SM_BUILD_TAG		"
"
#define SM_BUILD_CSET		"3d461ec"
#define SM_BUILD_MAJOR		"1"
#define SM_BUILD_MINOR		"9"
#define SM_BUILD_RELEASE	"0"
#define SM_BUILD_LOCAL_REV      "6152"
#define SM_BUILD_UNIQUEID       SM_BUILD_LOCAL_REV ":" SM_BUILD_CSET
#define SM_VERSION_STRING	"1.9.0.6152
"
#define SM_VERSION_FILE		1,9,0,6152
#endif /* _SOURCEMOD_AUTO_VERSION_INFORMATION_H_ */ 
```
This, of course, caused compile errors.
=> fix generate_headers.py to strip new lines

core/CoreConfig.cpp, core/HalfLife2.cpp
Valid core config options aren't cached to be retrieved using `GetCoreConfigValue` after they've been loaded from core.cfg or set through the `sm config` root console menu.
E.g. `sm config ServerLang` would return `[SM] No such config option "ServerLang" exists.` all the time.
Stop notifying other listeners if the config key was consumed, but don't skip adding it to the cache.
Also fix `FollowCSGOServerGuidelines` always showing as unhandled command when being changed through `sm config FollowCSGOServerGuidelines yes`.
=> Fix core config values not being cached

AMBuildScript, configure.py, core/AMBuilder, core/logic/AMBuilder, extensions/bintools/AMBuilder, extensions/clientprefs/AMBuilder, extensions/curl/AMBuilder, extensions/curl/curl-src/lib/AMBuilder, extensions/geoip/AMBuilder, extensions/mysql/AMBuilder, extensions/regex/AMBuilder, extensions/sdkhooks/AMBuilder, extensions/sdktools/AMBuilder, extensions/sqlite/AMBuilder, extensions/topmenus/AMBuilder, extensions/updater/AMBuilder, loader/AMBuilder, tools/buildbot/PackageScript, versionlib/AMBuilder
SourcePawn's build scripts were recently updated to the 2.1 API and SourceMod needs the same treatment to stay compatible.
=> Switch to AMBuild 2.1 API.

core/logic/smn_float.cpp, extensions/sdkhooks/extension.cpp
Fixing some warnings that were spit out due to unsafe double -> float comparisons, and some other easily-fixable warnings were corrected, as well.
~~Someone please double check that the change in MernsenneTwister.h is safe. The warning was~~ 
~~```\sourcemod\core\logic\MersenneTwister.h(128): warning C4146: unary minus operator applied to unsigned type, result still unsigned```~~
^Redacted from pr
=> Ditch C header/Fix build warnings

extensions/tf2/natives.cpp, gamedata/sm-tf2.games.txt
Fix the error:
`L 10/21/2017 - 19:05:10: [SM] Exception reported: Failed to locate function
L 10/21/2017 - 19:05:10: [SM] Blaming: sf2.smx
L 10/21/2017 - 19:05:10: [SM] Call stack trace:
L 10/21/2017 - 19:05:10: [SM]   [0] TF2_MakeBleed
`
I don't know if the recent two fix patches changed the signature or you've missed it, but here a fixed linux sig for MakeBleed
=> TF2 Makebleed function param fix

core/logic/ForwardSys.cpp, core/logic/ForwardSys.h, core/logic/smn_core.cpp, core/logic/smn_fakenatives.cpp, core/logic/smn_functions.cpp, plugins/include/core.inc, plugins/include/functions.inc, public/IForwardSys.h
Readds https://github.com/alliedmodders/sourcemod/pull/606 while fixing https://github.com/alliedmodders/sourcemod/pull/647
Unmanaged forwards broke in old extensions after adding `PushNullVector` and `PushNullString` to `IForward`, because `IChangeableForward` inherited from `IForward`. So extensions which were compiled against older SourceMod includes and using private forwards crashed when calling one of the `AddFunction`/`RemoveFunction` methods.
This was fixed by removing the two new functions from `IForward` and just allow passing `NULL` to `PushArray` and `PushString` which get replaced with the corresponding pubvar.
=> Add natives to check for NULL_VECTOR and NULL_STRING without breaking backwards compatibility

core/logic/GameConfigs.cpp, core/logic/GameConfigs.h
Allows for the last "read" offset for an Address to instead be "offset", which doesn't deref the addr pointer after applying the offset
Shortens the necessary coding to get a particular Address inside a function
(old method: store offset in a separate GameConf Offsets entry, apply the offset to the Address in SP)
It builds on OSX, but I don't have srcds on OSX to test with, nor any other environments to build on.
Any suggestions?
=> Add convenience logic for "offset" to Address definitions in GameConf

core/logic/PluginSys.cpp
Prior to this pull request, plugins could be loaded in twice & have two separate instances of the same plugin running simultaneously. This adds a check for each plugin loaded in, and ensures that the code hash of the new plugin doesn't equal a code hash of a plugin that's already loaded.
Here's the original bug report: https://bugs.alliedmods.net/show_bug.cgi?id=6491
=>  Lowercase windows/mac paths to avoid plugin duplicate loadings (Bug #6491)

core/smn_keyvalues.cpp, core/smn_keyvalues.h, plugins/include/keyvalues.inc
Before this pull request, in order for a plugin to get a string version of the KeyValues tree they'd have to export to a file and read it back in. That is the reason this was created. General use of this functionality looks something like this:
```cpp
int length = kv.ExportLength;
char[] buffer = new char[length];
kv.ExportToString(buffer, length);
```
=> Add KeyValues.ExportToString

extensions/cstrike/natives.cpp
This reverts commit 687db96b38112ba455d21fab5515e94600236942.
Creating a pr for this just in case I am missing something. When a plugin is made to work for both CS:S and CS:GO having natives not exist on both cause issues since the native has to either be marked as optional in the plugin or REQUIRE_EXTENSIONS undefined. The change possibly broke other plugins besides mine as well.
=> Revert "Make CS:GO specific natives exist only on CS:GO"

core/logic/ExtensionSys.cpp, core/logic/ExtensionSys.h
I might have missed something since first time really touching any of this. Also not sure if we should instead print a different message for optional instead of omitting it completely.
=> Only show extensions that failed to load if the extension is required.

bridge/include/BridgeAPI.h, core/logic/CDataPack.cpp, core/logic/CDataPack.h, core/logic/smn_datapacks.cpp, core/sourcemod.cpp, public/IDataPack.h
This lift and shifts CDataPack from a linear datatype to something using a vector with type mixed in. Iterators will change (again), so plugins manually using SetPackPosition without ReadPackPosition (against the API) will experience breakage; if this even builds.
=> Migrate CDataPack from a Compact Cassette tape.

core/logic/Logger.cpp, core/logic/Logger.h
Logger has a bunch of duplicated code in it, goto statements... This should simplify the pipeline significantly, reducing its footprint and make it easier to follow. This needs testing, though.
=> Simplify Logger internals (Fixes Issue #663).

plugins/basechat.sp, translations/common.phrases.txt
Also fixed colors, because it didn't work without `\x01` at begin of string.
=> Added more translation to basechat

core/logic/ExtensionSys.cpp
After discussing this with both asherkin and psychonic I think this is the best fix for now to the issue.
Example output
```
[SM] Displaying 10 extensions:
[01] CS:GO GNI Econ (1.0.2): Creates EconItemView for items.
[02] BinTools (1.8.0-manual): Low-level C/C++ Calling API
[03] <FAILED> file "game.cstrike.ext.2.csgo.dll": Could not read sm-cstrike.games: File could not be opened: The system cannot find the file specified.
[04] SDK Tools (1.8.0-manual): Source SDK Tools
[05] Top Menus (1.8.0-manual): Creates sorted nested menus
[06] Client Preferences (1.8.0-manual): Saves client preference settings
[07] SQLite (1.8.0-manual): SQLite Driver
[08] CS:S DM (2.1.6-dev): Deathmatch for CS:S
[09] <OPTIONAL> file "SteamWorks.ext.dll": The specified module could not be found.
[10] SDK Hooks …
```
=> Address issue #737

core/smn_entities.cpp, plugins/include/entity.inc
https://bugs.alliedmods.net/show_bug.cgi?id=5714
=> Add RemoveEntity native (5714).

plugins/basevotes.sp, plugins/funvotes.sp, plugins/include/float.inc
Apparently people use the float natives for actual float arithmetic; they're not _really_ intended to be used directly. I've added a note to deter people from using these instead of their respective operators.
=> Prevent use of primitive float operation functions

plugins/include/string.inc
Phrasing on this was still weird and since it was brought up by ddhoward in discord, we might as well make it right.
=> Fix description for CharToLower and CharToUpper v2

core/logic/GameConfigs.cpp, core/logic/GameConfigs.h
This adds support for platform specific custom key values in the `Keys` section in game config files. Now you can have different values for the same key per platform.
Previously you could only add general key values in gamedata files that were the same on all platforms like
```
"Keys"
{
"key"	"value"
}
```
This patch allows you to set the value per platform in a subsection like
```
"Keys"
{
"key"
{
"windows"	"value1"
"linux"	"value2"
"mac"	"value3"
}
}
```
Looking up the `key` will return the value matching the host platform.
=> Allow different values per platform in "Keys" gamedata section

extensions/regex/CRegEx.cpp, extensions/regex/CRegEx.h, extensions/regex/extension.cpp, plugins/include/regex.inc
Not sure how long this has been broken but currently MatchRegex doesn't actually return the number of matches. It instead returns 1 + the number of capture group matches. This simply fixes it to work how the docs currently say it should work. However, it is possible to add capture group support at some point but would require some effort along with new natives.
Some test outputs.
```
Matches 5
Match 0 is t
Match 1 is t
Match 2 is t
Match 3 is t
Match 4 is t
Matches 1
Match 0 is _
Matches 3
Match 0 is .
Match 1 is _
Match 2 is +
Matches 1
Match 0 is test
```
Test plugin
```
#include <regex>
{
Regex regex = CompileRegex("t", PCRE_UTF8);
int filter = MatchRegex(regex, "test.string_doesnt+match"); …
```
=> Add new regex natives.

plugins/include/admin.inc
More bad `const`s were found. Here's to two less 🍻 
Fixes #768
=> Un-const string retrievals (Fixes #768)

core/ConCmdManager.cpp, core/HalfLife2.cpp, core/MenuStyle_Radio.cpp, core/NextMap.cpp, core/PlayerManager.cpp, core/logic/ExtensionSys.cpp, core/logic/LibrarySys.cpp, core/logic/Logger.cpp, core/logic/PluginSys.cpp, core/logic/RootConsoleMenu.cpp, core/logic/TextParsers.cpp, core/logic/Translator.cpp, core/logic/smn_lang.cpp, core/logic/sprintf.cpp, core/logic_bridge.cpp, core/sourcemod.cpp
I've been going through looking for changes that I can sweep across the project to keep things consistent. This replaces every instance of `ke::SafeSprintf` which is only used for copying with `ke::SafeStrcpy`.
=> Replace ke::SafeSprintf with ke::SafeStrcpy

extensions/sqlite/sqlite-source/sqlite3.h
This includes numerous bug fixes, optimizations and new features from releases over the past 5 years.
The Amalgamation source code distribution isn't hosted in an official repository anywhere. SQLite uses `Fossil` as version control instead of git, so adding a sub module for this isn't possible.
Keep using up-to-date software!
http://sqlite.org/chronology.html
=> Update SQLite to version 3.22.0

gamedata/core.games/engine.ep2.txt, gamedata/core.games/engine.sdk2013.txt, gamedata/sdkhooks.games/game.zpanic.txt, gamedata/sdktools.games/engine.ep2.txt, gamedata/sdktools.games/game.zpanic.txt
This pull request updates the gamedata files for Zombie Panic! Source, it also tells SourceMod that ZPS is now using the SDK 2013 engine rather than EP2's.
Related issue: #771
=> [ZPS] Update gamedata and engine migration

extensions/sdktools/tenatives.cpp, extensions/sdktools/vsound.cpp
EmitSound currently errors out with a misleading error message when the client is not in game. Some discussion about it can be seen here: https://forums.alliedmods.net/showthread.php?t=306196
=> Improve error message for EmitSound

core/PlayerManager.cpp, core/logic/AdminCache.cpp, core/logic/ExtensionSys.cpp, core/logic/LibrarySys.cpp, core/logic/RootConsoleMenu.cpp, core/logic/smn_filesystem.cpp, core/logic/smn_players.cpp, core/sourcemm_api.cpp, extensions/clientprefs/extension.cpp, extensions/cstrike/extension.cpp, extensions/cstrike/util_cstrike.cpp, extensions/geoip/extension.cpp, extensions/mysql/mysql/MyDriver.cpp, extensions/sdktools/extension.cpp, extensions/sdktools/output.cpp, extensions/sdktools/vnatives.cpp, public/IExtensionSys.h, public/smsdk_ext.cpp, public/smsdk_ext.h
Very similar to #784, but with more extension edits
Edit: there’s a few more I’d like to throw in this pr, please hold off on merging it.
=>  More amtl safe string fixes

gamedata/sdkhooks.games/game.pvkii.txt, gamedata/sdktools.games/game.pvkii.txt
-Updates offsets
-Removes "Reload" as no corresponding function actually exists
Extra Notes:
- There does not seem to be any "Reload" function, and the offsets in this gamedata update seem to have gone up by 2, and the corresponding (Windows) offset 273+2 is CBasePlayer::RemovePlayerItem() which is probably not "Reload"
- GroundEntChanged points to a network state change. Windows and Linux were previously pointing to two different versions of this function, one that takes a void* and one that does not. They are now both the same HOWEVER I am not sure if this is desired behavior
I have attached a copy of the offset dump which should correspond to Linux offsets. (The dump was done with the Mac server.dylib binary)
[server_dump_linux.txt](https://github.com/alliedmodders/sourcemod/files/19628 …
=> Update Function Offsets For PVKII

core/logic/smn_players.cpp
`ShowActivity` and related functions are used to inform all clients about the usage of admin commands (such as bans or mutes). These messages are not sent to any fake clients, however they _should_ be sent to SourceTV/GOTV fake clients because messages they receive are actually visible to broadcast viewers and in demos recorded with `tv_record`. 
Player chat messages as well as SM functions like `PrintToChat`/`PrintToChatAll` broadcast to TV clients, but `ShowActivity` does not.
This fix could also be implemented by sending these messages to all fake clients, like `PrintToChat` does.
=> Send ShowActivity messages to TV clients

plugins/include/clients.inc
=> Deprecate GetMaxClients

extensions/regex/CRegEx.cpp, extensions/regex/CRegEx.h, extensions/regex/extension.cpp, extensions/regex/posix_map.h, plugins/include/regex.inc
CompileRegex is currently setting the error code to the offset of where the error occurred rather than the actual error.
To fix this pcre_compile was replaced with pcre_compile2 and a map used to convert the pcre error to a simpler (posix) error code but maintaining pcre's error string and adding the error codes to the enum. Also changed the internal member names since it was rather confusing. In the future we can also add in the offset so we can pass the offset where the error occurred.
The reason for mapping the errors is that pcre's error codes dont seem to be documented at all(?) From pcre_internal.h the errors are named ERR0, ERR1 etc... and i couldn't find any more information. There is also over 80 of them (due to the amount of detail) so I think the posix error codes are a simpler …
=> Fix CompileRegex not actually setting a valid error code.

AMBuildScript, extensions/mysql/AMBuilder, extensions/mysql/mysql/MyDriver.h
MySQL defines its own timespec_t. Official mysql builds are built using VS2013, so you still need to compile the client library yourself to be able to link it, but this change makes the dbi extension compatible with future versions already.
=> Fix MySQL extension build using vs2015

extensions/mysql/mysql/MyBoundResults.cpp, extensions/mysql/mysql/MyBoundResults.h, extensions/mysql/mysql/MyStatement.cpp, extensions/mysql/mysql/MyStatement.h
Prepared statements can return multiple result sets in MySQL 5.5. That can happen when calling stored procedures using `CALL x();`.
This change removes the previous caching of result bindings, since the number of fields in a result can differ from result set to result set. This could potentially have a negative impact on performance of prepared statements always only returning one result set, since the result binding buffers are recreated everytime the statement is executed instead of once. That difference should be negligible though.
Fixes #823.
Usage is just like with normal queries:
```sourcepawn
// From https://dev.mysql.com/doc/refman/5.5/en/c-api-prepared-call-statements.html
{
char error[255];
Database db = SQL_DefConnect(error, sizeof(error));
if (db == …
```
=> MySQL: Support multiple result sets in prepared queries

core/logic/DebugReporter.cpp, core/logic/DebugReporter.h, core/logic/smn_core.cpp
In order for this to be merged, [this pr](https://github.com/alliedmodders/sourcepawn/pull/140) for sourcepawn must be merged. 
Essentially this adds pull request adds LogStackTrace, which will serve as a debugging function that outputs a stack trace where the native is called, but does not halt execution. For more info: see #684
```cpp
{
SomeFunction();
}
void SomeFunction()
{
SomeFunction2();
}
void SomeFunction2()
{
LogStackTrace("LogStackTrace%i %.2f", 4, 10.0)
SetFailState("SetFailState %i %.2f", 4, 10.0)
}
```
will output in errors
```
L 09/17/2017 - 15:07:55: [SM] Stack trace requested: LogStackTrace 4 10.00
L 09/17/2017 - 15:07:55: [SM] Call stack trace:
L 09/17/2017 - 15:07:55: [SM]   [0] LogStackTrace
L 09/17/2017 - 15:07:55: [SM] …
```
=> Add LogStackTrace Native (#684)

gamedata/sdktools.games/game.zpanic.txt
This pull request is for the ZPS sdktools gamedata, which aims to update signatures and offsets. Below are the changes made to the ZPS sdktools gamedata file:
**Changes:**
- Updated signatures for FindEntityByClassname, FireOutput, and CBaseTempEntity/s_pTempEntities.
- Uncommented the CBaseTempEntity offsets (they were previously commented out due to lack of signatures).
- Updated SetEntityModel and WeaponEquip offsets (previously commented out and not updated).
- Reverted PlayerRunCommand offset name back to PlayerRunCmd.
Testing included running the updated gamedata on a live ZPS game server with plugins such as UMC, SMAC, Playervotes, etc. running and using the testsuite scripts to determine if the offsets/signatures were working correctly. If there are any further tests that should …
=> [ZPS] Update for sdktools gamedata (pr)

core/logic/smn_profiler.cpp, plugins/include/profiler.inc
Think this is one of the last Handle types without a method map, decided to piece together a small patch to change that.
=> Add Profiler methodmap

core/ConVarManager.h, core/EventManager.h, core/HalfLife2.h, core/logic/AdminCache.h, core/logic/GameConfigs.h, core/logic/HandleSys.h, core/logic/Native.h, core/logic/PluginSys.cpp, core/logic/PluginSys.h, core/logic/RootConsoleMenu.h, core/logic/smn_maplists.cpp, core/smn_console.cpp, extensions/clientprefs/cookie.h, extensions/topmenus/TopMenu.h, public/sm_namehashset.h
On #709, we forgot to convert the `NameHashSet<CPlugin *>`'s lookups to be lowercase. This will fix some casing issues people were experiencing trying to unload their (case-edited) plugins.
EDIT (12/27/17): 
Upon asherkin’s message below, I reverted the first commit of this PR & the #709 commit. The new solution to this entire problem, including the one #709 tried to solve, is to change the way `NameHashSet` hashes the key by forcing policies to also implement a `hash` method which will be used instead of the blanket implementation of `hash` that existed before.
Edit (6/17/2018):
Fixes #831
=> Individualize NameHashSet Hashing & Revisit #709

core/ConCmdManager.cpp, core/ConCmdManager.h, core/smn_console.cpp, plugins/include/console.inc
Closes #742 
Essentially this adds a methodmap for the existing command iterator, but in the more accepted iteration style that we're using nowadays which allows us to add more info as we see fit, without breaking older plugins. Related to this, I also added an `IPlugin*` to `ConCmdInfo` so we're able to track which plugin made what command, and this plugin handle is exposed through the iterator. 
My test script for this PR is as follows
```
{
CommandIterator it = new CommandIterator();
while (it.Next())
{
char name[128];
it.GetName(name, sizeof(name));
char desc[128];
it.GetDescription(desc, sizeof(desc));
int flags = it.Flags;
char plugin[128];		
GetPluginFilename(it.Plugin, plugin, sizeof(plugin));
PrintToServer("%s - %s (created by %s) - flagbits: %08b", …
```
=> Add base CommandIterator implementation

plugins/basebans.sp, plugins/basetriggers.sp, plugins/nominations.sp, plugins/rockthevote.sp
Just doing drive-bys on first-party plugins.
=> collection of plugin cleanups

plugins/adminhelp.sp
L 11/19/2017 - 16:37:02: [SM] Exception reported: Client 12 is not in game
L 11/19/2017 - 16:37:02: [SM] Blaming: adminhelp.smx
L 11/19/2017 - 16:37:02: [SM] Call stack trace:
L 11/19/2017 - 16:37:02: [SM]   [0] PrintToConsole
L 11/19/2017 - 16:37:02: [SM]   [1] Line 105, /home/builds/sourcemod/linux-1.9/build/plugins/adminhelp.sp::HelpCmd
=> Fix "Exception reported: Client 12 is not in game"

core/logic/CDataPack.cpp, core/logic/CDataPack.h, core/logic/smn_datapacks.cpp, plugins/include/datapack.inc
```cpp
DataPack dp = new DataPack();
dp.WriteCell(3);
dp.Reset();
dp.WriteCell(4);
delete dp;
```
Instead of the data being overwritten, the current behavior inserts 4 before 3. This is a problem because before #688 DataPacks would overwrite. This adds parameters to every native, default false, which determines whether the data should be inserted or overwritten that way old plugins wont break, and if someone really wants to insert they may.
=> Match old DataPack behavior when overwriting data

core/logic/CDataPack.cpp
Agh. We focused a little too heavily on the regression from https://github.com/alliedmodders/sourcemod/pull/688 and missed a memory leak from not properly freeing dynamic objects when they're overwritten in https://github.com/alliedmodders/sourcemod/pull/848. All good, shower thoughts drove this out.
=> Fix memory leak regression from #848.

.travis.yml
fix clang-3.9 failures, maybe; hopefully. I forget why this was broken.
=> Fix Clang-3.9 failures on Travis.

plugins/adminmenu.sp, plugins/include/functions.inc
Native callbacks currently require plugin authors to retag their returns to an `int`, but by adding `any` as another acceptable prototype we allow them to return without needing to retag.
```cpp
public any Native_Something(Handle plugin, int numParams)
{
float val =5.0;
return val; // no tag mismatch
}
```
Thanks asherkin for bringing this change to light
=> Allow any returns in native callbacks

core/PlayerManager.cpp
Asher pointed out almost immediately after this landed that the logging param should be 1 by default. This fixes that, however many years later now.
=> Flip sm_debug_connect to 1

core/logic/smn_core.cpp, plugins/include/sourcemod.inc
These changes should've been included in #685, but it appears my git client didn't stage them for commit. Not sure specifically what happened but this has already been r'd, re-ran tests and all still checkout okay. We should also cherry-pick this to 1.9.
=> Fix LogStackTrace Anomaly

plugins/include/helpers.inc
Modifying FormatUserLogText to allow client 0 to be passed.
=> Allow client 0 in FormatUserLogText

plugins/include/regex.inc, plugins/include/topmenus.inc
The `TopMenu` methodmap natives weren't marked as optional if the extension was optional like the other normal natives.
The `Regex` natives weren't marked as optional at all before if the regex extension was included optionally.
This makes the error message cleaner in case topmenus aren't loaded and won't prevent plugins from loading if they're supposed to have an optional dependency.
```
adminmenu.smx (Admin Menu): Required extension "TopMenus" file("topmenus.ext") not running
basebans.smx (Basic Ban Commands): Native "TopMenu.Display" was not found
```
=> Mark new methodmap natives as optional

core/logic/CDataPack.cpp
Some tests passed with the implementation prior to this commit, but those were edge cases. Good older behavior is now fully restored
=> Fix DataPack Overwrite Regression

plugins/basecommands/map.sp, plugins/basevotes/votemap.sp
These two base plugins are using the `MAPLIST_FLAG_NO_DEFAULT` when they shouldn't, which causes much user (and SM developer) confusion as it is completely counter to the documentation.
Raised by @DoctorOcsid on Discord.
=> Remove `MAPLIST_FLAG_NO_DEFAULT` misuses

public/sample_ext/extension.h
As stated in the [SourceHook Development wiki page](https://wiki.alliedmods.net/Sourcehook_Development#Getting_an_Interface_Instance):
```
The error and maxlen arguments must be named error and maxlen respectively, or else certain macros will fail
```
So this simply fixes that in the sample extension to avoid any possible confusion when using those macros.
=> Change `maxlength` to `maxlen` in sample extension

AMBuildScript, core/logic/AMBuilder, extensions/bintools/AMBuilder, extensions/clientprefs/AMBuilder, extensions/curl/AMBuilder, extensions/geoip/AMBuilder, extensions/mysql/AMBuilder, extensions/regex/AMBuilder, extensions/sqlite/AMBuilder, extensions/topmenus/AMBuilder, extensions/updater/AMBuilder, loader/AMBuilder
This simplifies non-sdk build scripts by removing their loops over SM.archs. Instead the top-level
build script will re-evaluate them for each architecture.
Aside from the top-level AMBuildScript, this is all unindenting.
=> Remove arch loops from build scripts.

extensions/cstrike/forwards.cpp, extensions/cstrike/natives.cpp
CS:GO added two parameters onto the end of TerminateRound, after inspecting their use I was unable to conclude exactly what they did, but passing zero seems to work as expected. 
One seems to be used as a loop condition, and the other possibly something to do with bot difficulty. I'm still unsure, but I don't think that's very important.
=> Fix CS_TerminateRound calls & detour

extensions/cstrike/natives.cpp
This is the beginning of fixing what's left to be done for the 10/3/18 CS:GO update that broke us. 
Essentially, this fixes an obvious OOB error I made, however does not completely fix issues that sourcemod is currently having.
@Drifter321 if you want to give this a shot, here's where I'm at. I'm quite stuck at the moment, though.
```sourcepawn
#include <cstrike>
{
CS_TerminateRound(0.0, CSRoundEnd_CTWin, true);
}
public Action CS_OnTerminateRound(float& delay, CSRoundEndReason& reason)
{
PrintToServer("%.2f | REASON: %d", delay, reason);
}
```
works currently OK, however default plugins seem to fail oddly, and I'm not sure of the cause although I wouldn't be surprised if it was just one of my mistakes. 
default plugins fail with this
```
Critical error …
```
=> Fix regression in vstk size

extensions/sdktools/extension.cpp, extensions/sdktools/extension.h, extensions/sdktools/trnatives.cpp, plugins/include/sdktools_trace.inc
Adds some more TR natives that expose more properties of the trace results. Here's a short summary of the new natives:
```
TR_GetStartPosition - Self explanatory, added this in just for completion since GetEndPosition exists.
TR_GetFractionLeftSolid - Similar to GetFraction, but returns the fraction of when the trace left a solid (assuming it started in a solid)
TR_GetDispFlags - Returns the displacement flags of a surface. See DISPSURF_FLAG_* for possible values.
TR_GetSurfaceName - Returns the name of the surface that was hit.
TR_GetSurfaceProps - Returns the surface properties index of the surface that was hit. Not sure if this is very useful alone since it might require other non-TR related functions to be exposed to get any real info from the index.
TR_GetSurfaceFlags - Returns the …
```
=> More TR natives

core/logic/smn_fakenatives.cpp
=> Improve CreateNative failure message

extensions/sdktools/vcaller.cpp
`SDKCall` has existing semantics that a `-1` retval indicates null, so use that and write an empty string to the buffer.
Consumers can tell the difference between `""` and `NULL` by checking if the return value is `0` or `-1`.
=> Handle NULLs in SDKCall string return (Fixes #874)

plugins/include/sourcemod.inc
This has been another constant source of confusion since the C99 ones were added to the strftime documentation we link.
It'd be nice to have a consistent implementation inside SM in the future.
=> Add a note about FormatTime platform dependence

core/logic/smn_maplists.cpp
This produces consistently better results, especially for games such as L4D(2).
=> Use natural sorting for map lists (Fixes #892)

core/logic/smn_gameconfigs.cpp, plugins/funcommands.sp, plugins/include/entity_prop_stocks.inc, plugins/include/sourcemod.inc
Wrap gamedata natives in a pretty methodmap and update stock plugins/includes to use it.
This fixes bad documentation on `GameConfGetAddress` and not closing the gameconfig file if handle creation fails as well.
=> Add GameData methodmap

extensions/sdkhooks/extension.cpp
This is an ancient bug in SDKHooks (I actually mailed PM about it before I knew better) where we don't reset the global hookids when we unhook functions. This results in double-frees and oddness when the last users of these forwards unload; and the same or new user comes into the fold using the forward again.
This fixes https://github.com/alliedmodders/sourcemod/issues/912
This is also untested.
=> SDKHooks: Reset global hookid when unhooking in SH.

extensions/cstrike/natives.cpp, gamedata/sm-cstrike.games/game.csgo.txt
So since this stupid sig keeps breaking... Here is a change to switch to grabbing a netprop address and using an offset to get the address of the clantag. Completely untested, will test if no one does prior later this week.
=> Switch CS:GO Clantag set/get to use netprops + offset over sig + offset.

core/logic/smn_maplists.cpp
When lookup of a more specialized entry in the maplists.cfg failed, it wouldn't fallback to the "default" section, but just try to parse the same section again.
A later fallback would try to parse the "mapcyclefile" again - which is the default redirection/value of the "default" section anyway - so this bug isn't visible unless the admin wanted a different default behavior.
=> Fix typo in fallback to "default" maplists section

core/logic/smn_console.cpp
Note: this was caught by triggering an assertion in the 1.9 exception handling code. We're not supposed to throw an error if the VM is already in an error state, and nothing cleared errors in between the two format operations.
=> Don't double-format in ReplyToCommand.

core/AMBuilder
Backport #764 to 1.9-dev, to fix build on updated versions of VS 2017. Reported via Discord.
=> Backport #764

core/HalfLife2.cpp
Mods using Source SDK 2013, and in theory, one day CS:S, DOD;S, and HL2:DM can implement the newer map lookup logic for Steam Workshop or any other dynamic map providers. Since they all share the same interface, we can support them all if they implement that interface version. Else, fall back to previous logic.
=> Unify map lookup logic across tf2esque engines. (fixes #927)

core/logic/FrameIterator.cpp
Before this patch, we'd check OOB before incrementing which makes no sense. We'll increment always this time, and change our OOB check to account for that.
Prior versions of the FrameIterator never worked, so we should probably cherry-pick this to 1.9
=> Prevent FrameIterator OOB Errors

plugins/include/regex.inc
Otherwise you'll get this error:
regex.inc(182) : error 001: expected token: ";", but found "<newline>"
[Example with latest sourcemod (1.10.6383) version](https://travis-ci.org/Bara/TroubleinTerroristTown/jobs/495529570#L640)
=> Add missing semicolon

plugins/basevotes.sp, plugins/basevotes/votemap.sp
I noticed on my CS:GO server that voting to change the map does not change it.
After reviewing the logs carefully, I realized that not full the mapname is taken.
Sorry for "my russian english".
Below is a log before and after this changes.
```
----------------Before:
L 02/03/2019 - 14:34:22: -------- Mapchange to workshop/524648589/mg_sonic_islands_v3_w --------
L 02/03/2019 - 14:34:53: [basevotes.smx] "Ҝℴţأķ<2><STEAM_1:1:58422681><>" initiated a map vote.
L 02/03/2019 - 14:34:54: [basevotes.smx] Changing map to workshop/141714364/mg_saw_rfix_ due to vote.
L 02/03/2019 - 14:34:59: [SM] Changed map to "workshop/141714364/mg_saw_rfix_"
-----------------------------------------------------↑ Not full mapname.
L 02/03/2019 - 14:35:18: SourceMod log file session started (file …
```
=> Fixed buffer size for workshop map.

plugins/mapchooser.sp
Sorry if this is too minor, but I noticed that "runoff" was spelled incorrectly.
=> Fix misspelling of "runoff" in mapchooser

plugins/sql-admin-manager.sp
Changes:
- Use the `sizeof()` function to declare the size of the for loops as opposed to hard-coding the value because it feels cleaner to do it that way.
- Dynamically pad the variables storing multiple values.
=> SQL Admin Manager refinements and standardisation

public/extensions/IBinTools.h
In #705 SourceMod received support for x64 binaries. The `IBinTools` interface was updated to call functions in 64bit binaries. The `PassInfo` struct's size was increased and the `Create[V]Call()` functions signatures changed, thus making the interface incompatible for consumers which were compiled against an earlier version.
`IBinTools::IsVersionCompatible` wasn't adjusted to that fact, so extensions compiled against pre SM 1.10 could request an `IBinTools` interface pointer, but crash when they try to use it.
This change makes requests to older interface versions invalid, thus letting `RequestInterface` return `NULL` for older extensions. It doesn't fix the backwards incompatibility, but at least makes the problem more blatant, so extensions can handle it themselves.
=> Block loading of incompatible IBinTools interface

extensions/cstrike/natives.cpp, extensions/cstrike/util_cstrike.cpp, extensions/sdktools/inputnatives.cpp, extensions/sdktools/outputnatives.cpp, extensions/tf2/natives.cpp, public/sm_argbuffer.h, public/sm_memwriter.h
Along with some type safety checks to ensure everything is kosher, this also technically fixes us relying on UB punning.
=> Add templated helper class to promote type-safety

extensions/cstrike/util_cstrike.cpp
This is a regression from #965 and fixes builds for CS:S.
The include was accidentally slipped under `#if SOURCE_ENGINE == SE_CSGO`
=> Fix CSS Builds

public/sm_argbuffer.h
We were serializing the `char*` itself into the arg buffer, and not it's actual contents. 
Instead of accepting the parameter as `char*`, we now enforce through references that what's actually passed is a `char[32]`
Special thanks to RandomReader from `#c++-general` on freenode for the help
=> Fix ArgBuffer String Serialization

core/logic/smn_sorting.cpp, plugins/include/adt_array.inc
Please correct me if this implementation is incorrect. Attempted to add Sort and SortCustom to ArrayList methodmap.
=> Add Sort and SortCustom to ArrayList methodmap

plugins/basevotes.sp, plugins/funvotes.sp
See https://github.com/alliedmodders/sourcemod/issues/1007
=> Fix wrong formating to "Vote Delay Minutes" when delay above 60s

.travis.yml
Travis-CI seems to have finally improved their environment so we should be okay to test this unique code-path now with CI.
https://github.com/alliedmodders/sourcemod/pull/992
=> NPOTB: Enable cstrike builds w/ Travis-CI.

AMBuildScript
GCC 9 was released earlier this month and I happened to have accidentially installed it on my new fedora machine. Turns out the addition of some new warnings prevented builds to pass.
This obviously doesn't fix the actual warnings the compiler is referring to. I'm more concerned about the `memset`ing that we're doing and I'll submit a patch in the future(TM) to address that directly to correct what it's warning about, but the other warning (`packed-not-aligned`) is found in the hl2sdk so there's not much we can do about it.
=> NPOTB: Fix GCC 9 Builds 

core/logic/CellArray.h, core/logic/ExtensionSys.cpp, core/logic/ShareSys.cpp, core/logic/stringutil.cpp, core/smn_entities.cpp, public/IExtensionSys.h
Ran the cppcheck static analyzer against /core/ to check if we were doing any ugliness that I didn't know about. Turns out there's a few situations where we were regressed.
First, and likely the most significant, was `CExtension::FindNextDependency`. This method must not have worked correctly for many many years. All operations were mistakenly done on a default-constructed iterator. 
Secondly, `realloc` can fail. By doing assignment directly on the result of `realloc` we miss the opportunity to check if the retval is null or not. If it *is* null, then our memory allocated previously is still valid and we've just successfully leaked it. For the case involving `InternalFormat`, an exception was added for realloc failures.
Finally, `1<<31` is undefined behavior as `1` is an int32. 
Also …
=> Fix Miscellaneous Regressions and UBs

core/smn_keyvalues.cpp, extensions/clientprefs/natives.cpp, plugins/include/clientprefs.inc
This PR adds a methodmap for clientprefs cookies without breaking changes, considering that the cookie Handle is not always the first param for clientprefs functions.
=> Added cookie methodmap (clientprefs)

core/HalfLife2.cpp, core/HalfLife2.h, core/logic_bridge.cpp
As reported in #1006, the matchmaking_ds binary is not found since our path to it is incorrect.
This changes our lookup to just use the binary name instead of including the path - similar to how we find tier0 and/or vstdlib to find symbols in those. Only tested on Windows, but that confirms that the binary is loaded by the time our lookup runs, so it should also be fine for dlopen.
=> Fix matchmaking_ds bin not being found for gamedata (#1006).

core/logic/PluginSys.cpp, plugins/funcommands/beacon.sp
Pad left "plugin id" with "zeros" based on the plugin count.
Related to the Feature Request #994
=> Pad left "plugin id" with "zeros" based on the plugin count.

extensions/tf2/natives.cpp, plugins/include/tf2.inc
See #713 
This PR adds 3rd param `TF2_IgnitePlayer` to allow set duration of fire, while default value kept as 10.0 so older plugins should not break.
However when i tested this, i found out fire duration is capped to 10.0 seconds, even when tempted to set higher than 10. I believe this is valve's shitty fix on infinite fire duration from some weapons, which is really unfortunate. May still be helpful to some plugins when setting fire less than 10 seconds.
Example code when testing this, setting yourself on fire with duration.
```
#include <tf2>
{
RegConsoleCmd("sm_fire", Command_Fire);
}
public Action Command_Fire(int iClient, int iArgs)
{
if (GetCmdArgs() == 0)
{
TF2_IgnitePlayer(iClient, iClient);
}
else
{
char sBuffer[4];
GetCmdArg(1, …
```
=> Update TF2_IgnitePlayer to support set duration of fire

AMBuildScript
Includes the following SourcePawn changes:
- PR#339 Fix various compilation problems
- PR#340 Restyle spcomp
- PR#344 Fix uninitialized variable guarding profiling scopes
- PR#346 Fix Travis Emscripten build
- PR#345 Simplify inline exit frames
=> Update SourcePawn to 093edef

plugins/include/regex.inc
https://steamuserimages-a.akamaihd.net/ugc/786360440444926021/3977E37BB5937C22C7C82A96DC503ED449F865B1/
Some methodmap documentation was a direct copypasta from the non-methodmap natives, mentioning a handle parameter which doesn't exist (since the "this" methodmap variable is the handle itself). A couple non-methodmap natives had the @ param documentation in the wrong order, with the handle coming second in the doc string.
I think I fixed everything in this file. Please review and let me know of any changes that should be made. Thanks.
(EDIT: that @ param accidentally pinged someone. Oops sorry!!!)
=> Fix regex.inc documentation errors

core/logic/smn_filesystem.cpp, plugins/include/files.inc
Here is a snippet from the current TF2 event I'm working on:
```
g_FlatFile.WriteLine("wave,%d,%d,%d,%d", Steam3, TimeStamp, MissionIndex, WaveNumber);
FlushFile(g_FlatFile);
```
I would like to be able to flush the file like this so that I can consistently use methodmaps on the file handle instead of flip flopping between legacy and new API:
```
g_FlatFile.WriteLine("wave,%d,%d,%d,%d", Steam3, TimeStamp, MissionIndex, WaveNumber);
g_FlatFile.Flush();
```
Here is a patch (one for smn_filesystem.cpp and one for files.inc) that adds the Flush method to the file methodmap. Please review and let me know if I accidentally broke something or violated any coding conventions. I don't have a C++ compiler so I wasn't able to test if this will break the buildbots or CI.
Thanks.
=> Add File.Flush methodmap

plugins/nominations.sp, translations/nominations.phrases.txt
This change checks the nomination against the map arraylist. If the nomination matches multiple results, those results are then added to a menu to allow the client to select available maps. The maps added to the menu go against the same checks as the normal nomination menu and wont allow nomination of disabled maps. ~~There is also a defined MATCHED_INDEXES_MAX of 7, which means there will only be one page of matched maps.~~ Update: Added convar sm_nominate_maxfound.
The main reason for this change is to allow for more flexibility of map nominations. In its current state, the plugin only attempts to nominate the very first match.
Example image of /nominate jump_b
Image demonstrating that disabled maps cannot be selected. 
Command used: /nominate jump_
I would also like feedback on the …
=> Create menu if multiple nom matches found

plugins/include/functions.inc
When i want to call `RequestFrame` without any data param, `RequestFrameCallback` still requires me to add pointless data param.
```
{
RequestFrame(OnFrame);
}
public void OnFrame(int pointless)	//pointless param
{
//do something
}
```
I want to allow plugin to be compiled without needing data param, making it look bit more nicer when not passing any data.
```
{
RequestFrame(OnFrame);
}
public void OnFrame()	//param not needed as RequestFrame not passing any data
{
//do something
}
```
=> Allow RequestFrameCallback not require data param

extensions/cstrike/extension.cpp, extensions/cstrike/extension.h, extensions/cstrike/timeleft.cpp
(I actually forgot what exactly the buggy behavior was)
=> cstrike: Fix wrong timeleft calculation

extensions/sdktools/trnatives.cpp, plugins/include/sdktools_trace.inc
Related to the issue #1080.
Add **TR_GetHitBoxIndex()** native to retrieve the member "hitbox" from the class "CGameTrace".
https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/public/gametrace.h#L73
=> Add TR_GetHitBoxIndex() native

.gitattributes
Just a little nit-pick I've always had, but never did anything about.
We just mark in-tree third-party code as vendored code, and assume `.h` file extensions are C++, this should cover 90% of the cases in this repo.
=> NPOTB: Correct GitHub's Linguist inaccuracies

plugins/basecommands/map.sp
From the SM Discord:
> 4:52 PM] HiGPS: Is there any plugin that helps with the workshop map names not working properly in TF2, they show ID's and not the map names in the admin menu , but works in the nominations menu
This copies the display name-related lines from the `LoadMapList` function in `basevotes/votemap.sp` to `basecommands/map.sp`.  It's otherwise left as-is &mdash; I'd have no issues changing the styling / hoisting the variable declaration to make it more consistent if desired.
=> Fix admin map chooser not using display names for menu

extensions/sdktools/vcallbuilder.cpp
PR #705 made some changes for 64-bit support that required callers to
provide a buffer for object storage, but only added the required code to
the non-virtual call builder, not the virtual call builder.
Copy it over to CreateValveVCall so that ValveParamToBinParam stops
writing to a null pointer.
Fixes #1059 (Hopefully.)
=> Fix virtual SDKCall with object params

core/PlayerManager.cpp
Fixes #1107 
Left out the check for player connection since it may be impossible for IVEngineServer::GetPlayerUserId to return -1 at the point in time we ask for it.
=> Add bounds check for userid reset on disconnect

plugins/include/cstrike.inc
Instead of KNIFE_CSS i would call it WEAPON_CLASSIC, like it [Valve](http://media.steampowered.com/apps/csgo/blog/images/cs20/knife13.png) does.
#1105
=> Add classic knife to CSWeaponID

tools/checkout-deps.ps1
.sh version has this bit:
```
if [ $ismac -eq 0 ]; then
sdks+=( orangebox blade episode1 bms )
if [ $iswin -eq 1 ]; then
sdks+=( darkm swarm bgt eye contagion )
fi
fi
```
Added these to the ps1 SDK list. If there is a better approach, please let me know.
=> Add windows supported SDKs to powershell checkout-deps

extensions/sdktools/gamerulesnatives.cpp
https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ServerNetworkProperty.cpp#L157
```C++
ServerClass* CServerNetworkProperty::GetServerClass()
{
if ( !m_pServerClass )
m_pServerClass = m_pOuter->GetServerClass();
return m_pServerClass;
}
```
m_pOuter can be NULL and then GetServerClass would crash
so check m_pOuter first with GetEntityHandle:
```C++
IHandleEntity *CServerNetworkProperty::GetEntityHandle( )
{
return m_pOuter;
}
```
https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/ServerNetworkProperty.cpp#L103
Using GameRules_SetProp would sometimes crash for us, after this fix it hasn't crashed for 2 weeks and it doesn't look wrong to check this either.
=> Fix rare crash bug in SDKTools GetGameRulesProxyEnt

plugins/include/files.inc
"rb" = binary file for *reading* (not writing, that would be "wb").
=> Correct OpenFile Documentation

core/logic/ExtensionSys.cpp
Checks the filename passed in via `LoadExternal` for remote extensions for same-file tests.
This fixes `FindExtensionByFile` not finding an existing remote extension in the case where the filepath is not equal to the filename (and subsequently loading it twice) and allows plugins to successfully load when specifying that name as a dependency.
=> Check short name for remote extensions

plugins/include/adt_stack.inc
`PopStackCell` works differently to `ArrayStack.Pop` with same (incorrect) return documentation.
`PopStackCell` uses 2nd param to store value of the stack popped, returning false/true if stack if empty or not.
`ArrayStack.Pop` returns value of the stack popped, throws an error if stack is empty.
Also fixed `ArrayStack.PopString` with `oaram` while i'm at it. I'm not so great at english, so please do tell me if there a better wording for return documentation, thanks.
=> Fix ArrayStack.Pop documentation

AMBuildScript, core/AMBuilder
Throw error at configure stage if using unsupported MSVC version rather than having less obvious errors thrown later by compiler.
With the recent argbuffer addition, we apparently no longer support Visual Studio 2013. I removed a couple of paths for it, and added an early check to make sure a supported version is being used. I think we should do the same for GCC and Clang as well, but I don't know what minimum versions we support.
=> Throw configuration error on unsupported compilers

plugins/clientprefs.sp
This was found by LuqS: https://discordapp.com/channels/335290997317697536/335290997317697536/655499997298688040
=> Fix typo in plugin description

extensions/mysql/extension.cpp
https://crash.limetech.org/stats/dbi.mysql.ext.%25/my_real_read
https://crash.limetech.org/stats/dbi.mysql.ext.%25/net_real_write
Both of these are caused by the VIO ptr ending up as null in the middle of reading/writing to a connection - I can't find any indication of a fix for this made to MySQL, so don't think it is a bug fix we're missing, but there are some musings around the internet that it could be caused by improper thread-safety initialisation.
`my_init` (what we had here) is called internally by `mysql_library_init` but I think would have still led to an automatic `mysql_library_init` call the first time `mysql_init` was called (which we can do on a thread in case of threaded connections), which is exactly the thread-safety issue called out by the MySQL docs, so hopefully doing …
=> Speculative fix for MySQL crashes

core/logic/AdminCache.cpp
Looks like a simple mistake. My SRCDS instance is got a infinite cycle and killed by WatchDog.
=> Mistake in CanAdminTarget()

core/PlayerManager.cpp
pass validated parameter to GetSteamId. Fixes #1157.
=> Fix GetSteamAccountID validation opt-out

extensions/sdktools/vsound.cpp, plugins/include/halflife.inc
After doing some testing with a debugger, I noticed that `engsound->IsSoundPrecached(waveName)` returns `true`, even though the sound is not precached. Because I don't have the patience to compile Sourcemod, I replaced the jnz instruction with nops and now sounds are successfully precached.
For this reason, I removed `IsSoundPrecached` from `PrecacheSoundScript` and `GetGameSoundParameters`
I think it'll be a good idea to add a note to [IsSoundPrecached](https://sm.alliedmods.net/new-api/halflife/IsSoundPrecached) warning that this function may not work correctly(always returning `true`)
Fixes issue #1170
=> Fix issue #1170

plugins/basecommands.sp
While testing a plugin I was creating, I needed to use `sm_rcon` to kick myself from the server console to ensure my console check was working as intended.
I found that when using `sm_rcon kick me`, I got this error:
```
L 12/10/2019 - 22:53:23: [SM] Exception reported: Client 1 is not connected
L 12/10/2019 - 22:53:23: [SM] Blaming: basecommands.smx
L 12/10/2019 - 22:53:23: [SM] Call stack trace:
L 12/10/2019 - 22:53:23: [SM]   [0] ReplyToCommand
L 12/10/2019 - 22:53:23: [SM]   [1] Line 401, D:\builds\build-sourcemod-msvc12\windows-1.10\build\plugins\basecommands.sp::Command_Rcon
```
So as the title states, this is an extreme edge case and does not apply when using `sm_rcon sm_kick`, but I figure a proper IsClientConnected check was in order to not throw an error in an odd case like …
=> Fix edge case basecommands plugin error

plugins/nominations.sp
When a map is nominated and the max nominations have been reached, the wrong text is returned if the map hasn't been nominated yet. Instead of printing the "Max Nominations" text, it prints out the "Map Already Nominated" text instead.
=> fix incorrect command reply in nominations

core/HalfLife2.cpp, core/HalfLife2.h
`CHalfLife2::FindMap` works around the missing `IVEngineServer::FindMap` function by using the command autocompletion feature of the `changelevel` command.
The function populates a `CUtlVector<CUtlString>` object with the auto completion results. The game allocates memory for the vector and strings and we try to free it. This crashes when the C Run-time library version differs, which can happen when compiling using a newer toolchain.
Fixes #910 like @psychonic suggested.
I've only tested this on CS:GO Windows. This allowed me to run my server with a self-compiled build of SourceMod.
=> Fix heap corruption in CUtlVector destructor

plugins/include/sdkhooks.inc
As example for the [new-api](http://sourcemod.net/new-api/sdkhooks/SDKHookCB) site: https://i.imgur.com/ZyLtnrr.png
This change should be more readable for new coders/programmers they use this site.
=> Fix empty api descriptions in sdhooks.inc

extensions/tf2/natives.cpp
PR #965 accidentally changed `TF2_MakeBleed` custom damage type from 34 (`TF_CUSTOM_BLEEDING`) to 32 (`TF_CUSTOM_SHOTGUN_REVENGE_CRIT`).
I don't think using damage custom 32 change anything gameplay wise, but does incorrectly report 32 in `player_death` event, SDKHooks `SDKHook_OnTakeDamage`, and whatever other places damage custom uses.
=> Fix TF2_MakeBleed using incorrect custom damage type

core/ConVarManager.cpp, core/ConVarManager.h
Test code:
```cpp
ConVar SV_CHEATS = FindConVar("SV_CHEATS");
ConVar sv_cheats = FindConVar("sv_cheats");
ConVar sV_cHeAtS = FindConVar("sV_cHeAtS");
LogMessage("'SV_CHEATS' = %i, 'sv_cheats' = %i, 'sV_cHeAtS' = %i", SV_CHEATS, sv_cheats, sV_cHeAtS);
}
```
Output: 
```
L 02/10/2020 - 09:04:54: [ConVarLeakTest.smx] 'SV_CHEATS' = 4718664, 'sv_cheats' = 4718664, 'sV_cHeAtS' = 4718664
```
=> Make ConVar cache case insensitive, fixes #1166

plugins/include/sdktools_functions.inc
Seems appropriate to me.
Now you'd be able to do something like:
```c#
float ang[3] = {-90.0, 0.0, 0.0};
TeleportEntity(client, .angles = ang);
```
With less taps on the keyboard.
=> Add default values to TeleportEntity

plugins/mapchooser.sp
This commit ranks previous maps from least to most recently played. The mapchooser would then exclude x number of most recently played maps instead of x number of previous maps.
=> Remove duplicates from previous map vote history

core/HalfLife2.cpp, core/smn_halflife.cpp, gamedata/core.games/common.games.txt
Raised limits for SayText and HintText protobuffs and also enabled SayText as a chat message in csgo. Was compiled and tested on win, that pr will allow a lot more characters in chat messages and hints and that will allow use of much more colored messages (in chat) and more html tags (in hints).
Not sure how known that thing is, but big thanks to [@Rostu13](https://github.com/Rostu13), as he told me about that.
=> Raised limits for csgo HintText and SayText protobuffs

extensions/sdktools/output.cpp, extensions/sdktools/output.h
from #sourcemod irc log 2017-03-03:
```
[15:02:04] <BotoX> so there is clearly something rong with sdktools_entoutput
[15:02:18] <BotoX> HookSingleEntityOutput sometimes doesn't fire
[15:02:29] <BotoX> and HookEntityOutput sometimes fires for the wrong thing
[15:08:02] <psychonic> I think at least the former has been known for a while, but no one has been able to work out the cause, largely due to the issue being very intermittent
[15:11:48] <asherkin> I've heard both of those - I thought they were fixed
[15:14:26] <BotoX> running latest master branch so guess not
[15:14:39] <BotoX> and yeah i wasn't able to reproduce in single player
[15:16:11] <asherkin> BotoX: try searching the tracker
[15:18:22] <psychonic> asherkin: i don't remember anything being fixed with those
[15:28:11] <Fyren> …
```
=> Fix HookEntityOutput/HookSingleEntityOutput bugs in sdktools.

core/PlayerManager.cpp, core/PlayerManager.h
Buffers up to 16k bytes of SVC_Print if buffer would overflow, then sends chunks every frame.
Sends up to 2048 bytes per frame and does not split messages.
Only tested on cstrike, works without any changes on plugins.
On client the order is still messed up sometimes because the client itself fucks up the order (also on console commands like find)
=> Avoid losing console messages.

plugins/include/console.inc
This is quite a common operation, it is all over our base plugins and examples on the wiki. I wrote a plugin for the first time in a very long time the other day that needed some commands and it was really weird not having this available by default.
Tested with the following test plugin:
```sourcepawn
{
RegConsoleCmd("sm_test", Cmd_Test);
}
Action Cmd_Test(int client, int args)
{
for (int i = 1; i <= args; ++i) {
char strVal[32];
GetCmdArg(i, strVal, sizeof(strVal));
int intVal = GetCmdArgInt(i);
int checkedIntVal;
bool checked = GetCmdArgIntEx(i, checkedIntVal);
ReplyToCommand(client, "'%s' %d %d (%s)",
strVal, intVal, checkedIntVal,
checked ? "valid" : "invalid");
}
return Plugin_Handled;
}
```
Input:
```
sm_test hello 9 99 999 9999 99999 999999 9999999 …
```
=> Add helper stocks for getting numerical command arguments

AMBuildScript
Looks like the default here changed when we upgraded the Linux build server.
This is causing issues when debugging crash dumps.
=> Restore the frame pointer on Linux

AMBuildScript, configure.py
Quite often I find myself only needing to build the SDK-independent code, which we have more and more of these days.
=> Add an option to build against no SDKs

core/HalfLife2.cpp, core/smn_halflife.cpp, gamedata/core.games/common.games.txt
Reverts alliedmodders/sourcemod#1118
CS:GO makes a beeping sound when `SayText` is used.
=> Revert "csgo: enable SayText + raise msg limits (#1118)"

plugins/basecomm.sp
e.g. the next version of Blade Symphony.
=> Fix basecomm failing to load on games without sv_alltalk

plugins/nominations.sp
Using the nominate command it is possible to spam global chat by alternating between two maps e.g.
`bind mwheeldown "sm_nominate de_dust2;sm_nominate de_mirage;"`
By replying to successful nominations instead of putting in global this issue is prevented as clients can only spam themselves.
=> Prevent clients from spamming global chat using sm_nominate

extensions/sdktools/vstringtable.cpp, plugins/include/sdktools_stringtables.inc
Replaced StringToLocalUTF8 with LocalToString and memcpy to make this binary-safe. Discussed this with @asherkin on Discord.
This probably won't hurt as it looks like the function was originally intended to be binary safe.
resolves #1230
=> Make GetStringTableData native binary-safe

core/logic/CDataPack.cpp
When a pack was cleared or destroyed the String and Raw types could cause memory leaks. This happens when "position" is sitting at the end of the vector and can never get past the "if (pos >= elements.length())" statement. This means there is a memory leak in any plugin that clears/destroys a pack with strings and doesn't set the position to length-1 or less beforehand.
=> Fixed memory leak

extensions/regex/extension.cpp
Matching a Regex against an empty string throws an exception:
```sourcepawn
Regex regex = new Regex(".*");
int matches = regex.Match("");
```
Which is caused by this check:
```cpp
size_t len = strlen(str);
if (offset >= len)
{
return pCtx->ThrowNativeError("Offset greater or equal than string length\n");
}
```
Because `offset` and `len` are both 0.
However, this check is redundant, because `pcre_exec()` already returns `PCRE_ERROR_BADOFFSET` if the offset is negative or greater than the passed length, and [RegexError](https://sourcemod.dev/#/regex/enumeration.RegexError) already supports this.
=> Fix matching Regex against an empty string

core/logic/CellArray.h
The allocation size was still updated to the bigger size even if memory allocation failed. Trying to write to the supposedly available new space would overflow the heap and crash.
=> Fix crash when ArrayList runs out of memory #1233

extensions/tf2/holiday.cpp, gamedata/sm-tf2.games.txt, plugins/include/tf2.inc
TF2 2020-05-01 update added a new holiday, soldier for a tribute to Rick May.
Right at the bottom of the holiday list, and tested in TF2 windows.
=> Add new TF2 Holiday Soldier

gamedata/core.games/common.games.txt
During the Split Day of Infamy to separate engine build #718 on 3 Nov 2017, it has been forgiven to add the engine doi on list. All funcs using datamap fails since like FindDataMapInfo etc
=> Fix GetDataDescMap not work on Day Of Infamy

plugins/include/sourcemod.inc
Since getting from and storing to addresses gives no regard to the type you throw at it, it makes sense to change these to `any`.
Would help with having to do some obnoxious tagging at the moment:
```cs
// Before
{
Address foo;
float bar = 12.0;
StoreToAddress(foo, view_as< int >(bar), NumberType_Int32);
g_flFooBar = view_as< float >(LoadFromAddress(foo, NumberType_Int32));
}
// After
{
Address foo;
float bar = 12.0;
StoreToAddress(foo, bar, NumberType_Int32);
g_flFooBar = LoadFromAddress(foo, NumberType_Int32);
}
```
=> Change int to any with Address Functions

plugins/adminhelp.sp
This change utilizes the passed param `args`. The `args` param exists, no need to call `GetCmdArgs()`.
=> Replace GetCmdArgs with args param

tools/checkout-deps.ps1, tools/checkout-deps.sh
There were two separate issues with the checkout-deps scripts on windows and linux.
Windows didn't use the hl2sdk repository mirror "hl2sdk-proxy-repo" when cloning the different engine branches into their own folders like `hl2sdk-csgo`, `hl2sdk-css`, ... but cloned from github.com every time. When rerunning the checkout-deps.ps1 script later it would fail to find the "hl2sdk-proxy-repo" folder and fail to update the sdks.
Linux did use the local mirror repository for the initial clone of the different game sdk branches, but used github.com for later updates of the game sdks instead of using the local mirror.
Fix both scripts to always use the local mirror.
Looks like the AppVeyor config has to be updated too if it doesn't use the checkout-deps.ps1 script. #969
=> Always use hl2sdk-proxy-repo in checkout-deps

core/logic/CDataPack.cpp, core/logic/CDataPack.h, core/logic/smn_datapacks.cpp, plugins/include/datapack.inc
I have not pen-tested this at all and only did a minimal functionality check with [this plugin](https://www.dropbox.com/s/uk3cn79lbnyv0f2/vip_locations.sp?dl=0) for proof of concept to handling vectors
With the pandemic going on I've been getting all my projects on the back burner out of the way, this being one of them
=> Add an Array variant to DataPack's Read/Write methods

core/concmd_cleaner.cpp, core/smn_console.cpp
Fixes a rare crash caused by GetCommandFlags() if there are some commands registered by plugins (Reg*Cmd()) which containing capitals. The same command ending up in the cache multiple times would explain the bug. (https://crash.limetech.org/stats/dc3d4e0530c48bb491d6b448c5a4d8a3)
=> Fix unnecessary ConCommand cache misses

AMBuildScript
It turns out this was already enabled on MSVC (due to /EHsc), but let's
enable it on other platforms as well.
Exception handling comes with a huge caveat: SourceMod and SourcePawn
are not exception safe. Not only do they predate usable STL (C++11),
they often predate C++03, and sometimes even C++ itself. There are many
places we do not use RAII, or where we accumulate state in a way that
cannot be interrupted.
By enabling exceptions, we are NOT inviting general try/catch. We are
still assuming that a `throw` anywhere within SourceMod will ultimately
result in a crash.
However, as we enable more and more STL, we are losing the ability to
gracefully handle constructor failures and malloc failures. So try-catch
is now enabled. It should only be used in the narrowest of
circumstances:
- When …
=> Enable exception handling in C++ code.

core/logic/PluginSys.cpp
Fixes #1289
Just like for `load` and `unload`, we should be notifying that the waiting plugin will be reloaded on the next frame.
=> Notify on frame-delayed plugin reloads

core/logic/ExtensionSys.cpp
Fixes #1273 
We needed to set `m_bFullyLoaded` in order to prevent `CExtensionManager::MarkAllLoaded` from calling `MarkAllLoaded` twice.
=> Prevent multiple calls to SDK_OnAllLoaded

core/UserMessages.cpp, core/pb_handle.h
When creating our own "owned and local" protobuf message in `StartProtobufMessage`, `m_FakeEngineBuffer` is used to track that message. In `EndMessage` the message is optionally converted to a "private" one with the right abi on osx and passed to the engine's `SendUserMessage`. On linux and windows the same message as in the `m_FakeEngineBuffer` is passed though without conversion. `engine->SendUserMessage` has a vtable hook which sets `m_FakeEngineBuffer` to the passed argument.
`m_FakeEngineBuffer` frees the message it previously held, since it's "owned" from `StartProtobufMessage`, but that's the same one that's passed in as argument so a use-after-free in the engine happens when the now-freed message pointer is forwarded to the real `SendUserMessage` in the engine.
The message created …
=> Fix use-after-free crash when creating custom user messages

core/HalfLife2.cpp, core/HalfLife2.h, core/smn_entities.cpp, gamedata/core.games/engine.ep1.txt
=> Add string_t SetEntPropString support for ep1 (fixes #1287)

plugins/basechat.sp
`sm_psay` is the only basechat command that requires quotes around a message with multiple words.
=> Do not require quotes around message in sm_psay

plugins/mapchooser.sp
This commit fixes a bug where if the value of `sm_mapvote_exclude` is reduced, the change may not take effect for an extended period of time. The size of the old map list is not updated when this happens.
=> mapchooser: Fix previous map exclusion bug

plugins/include/testing.inc
Adds a new stock function `AssertStrEq` to assert equality between two strings.
It's a minor convenience over `AssertTrue` since it prints the expected string without having to include it in the `text` argument.
=> Add stock AssertStrEq to testing include

plugins/mapchooser.sp
Adds option to persistently store the previous map vote history in a text file. The previous map ArrayList is repopulated after the configuration files are executed for the first time.
=> Add option for persistent previous map storage

plugins/include/entity.inc, plugins/include/files.inc
Nothing should stop you from using eg. a float array on these natives.
It gets kinda annoying to use `view_as<int>()`
=> Change unnecessary int[]'s to any[]

plugins/include/sourcemod.inc
`OnLibraryAdded` and `OnLibraryRemoved` are called whether or not an optional dependency exists
=> Update OnLibraryAdded and OnLibraryRemoved docs

core/logic/smn_adt_trie.cpp, plugins/include/adt_trie.inc, public/sm_trie_tpl.h
We implemented a clone for `ArrayList`, but `ArrayStack` and `StringMap` were left without one. This pull request adds deep-copy cloning to said structures. Construct generally looks like
```cpp
ArrayStack mystack = // something, lets assume it also has data
ArrayStack copy = mystack.Clone();
delete mystack;
delete copy;
```
Fixes #796
=> Add Clone() implementation for StringMap

.travis.yml
A recent regression in libpcre for x64 wasn't caught by our CI, to prevent regressions in x64 builds from slipping by we should probably be building both x86 and x64 for completeness-sake
~~Some builds will likely fail until #1320 lands and we rebase this~~
=> Add x64 builds to travis-ci

.travis.yml, appveyor.yml, tools/checkout-deps.sh
SourceMod doesn't support Source 1 Dota 2 anymore #496 and neither Source 2. Speed up CI by only cloning the hl2sdks that are tested.
This adds a `-s sdk1,sdk2` parameter to the checkout-deps.sh script similar to the `-SDKs` option of the powershell script to select specific sdks to update instead of all.
=> Remove cloning of Dota 2 SDK in CI

tools/checkout-deps.ps1, tools/checkout-deps.sh
- Checks for an active 'python'/'python3' command.
- Checks for an active pip installation in the detected Python installation, otherwise, it installs it via 'get-pip.py'
- Added fallback to 'py'.
Closes #1324 
See: alliedmodders/ambuild#68
=> Updated 'checkout-deps' to check for 'pip'/'pip3' prior to installing 'AMBuild'

plugins/include/dbi.inc
In attributes parameter `charset` is called as `characterset`
=> Fix parameter name in SQL_SetCharset()

core/HalfLife2.cpp, gamedata/core.games/common.games.txt
This was initially discussed in the SourceMod Discord; PR provides a way to get the actual offset of networked class members of type `CUtlVector` such as `CBaseFlex::m_AnimOverlay` and `CTFPlayer::m_hMyWearables`.
Tested working in TF2 with the following snippet:
```
int offs = FindSendPropInfo("CTFPlayer", "m_hMyWearables");
PrintToServer("CTFPlayer::m_hMyWearables = %04x", offs);
offs = FindSendPropInfo("CTFPlayer", "m_ConditionData");
PrintToServer("CTFPlayer::m_ConditionData = %04x", offs);
}
```
Not pull-ready yet; need recommendations on code style and how to deal with the `CSendPropExtra_UtlVector` gutted from `public/dt_utlvector_send.cpp`.
Heuristic per following message (the `lengthproxy` also holds the extradata, so I opted to use the parent table …
=> Add offset-reading capability for networked CUtlVector instances

extensions/sdkhooks/extension.cpp, extensions/sdkhooks/extension.h, plugins/include/sdkhooks.inc, public/extensions/ISDKHooks.h
As a much much much faster alternative to:
```C++
public void OnEntityCreated(int entity, const char[] classname)
{
SDKHook(entity, SDKHook_SpawnPost, OnEntitySpawned);
}
```
now simply use:
```C++
public void OnEntitySpawned(int entity, const char[] classname)
```
The first one causes substantial lag/delay on round change due to all entities being recreated (unhook & hook).
Some plugins need to hook certain entities right after they spawn and filter those by user supplied config files which use props like targetname, hammerid, etc.
The entity props are only available after Spawn() and can not be accessed in OnEntityCreated().
I'm finding it weird that this wasn't exported as a forward right away as it's very useful and straightforward to do.
=> Add OnEntitySpawned to SDKHooks.

core/MenuManager.cpp, core/MenuStyle_Base.cpp, core/MenuStyle_Base.h, core/MenuVoting.cpp, core/logic/smn_menus.cpp, plugins/include/menus.inc, public/IMenuManager.h
BUMPS IMenuManager VERSION
Example:
```
{
RegConsoleCmd("menu_test1", Menu_Test1);
}
public int MenuHandler1(Menu menu, MenuAction action, int param1, int param2)
{
/* If an option was selected, tell the client about the item. */
if (action == MenuAction_Select)
{
char info[32];
char disp[32];
bool found = menu.GetItem(param2, info, sizeof(info), _, disp, sizeof(disp), param1);
PrintToConsole(param1, "You selected item: %d (found? %d info: %s | disp: %s)", param2, found, info, disp);
}
/* If the menu was cancelled, print a message to the server about it. */
else if (action == MenuAction_Cancel)
{
PrintToServer("Client %d's menu was cancelled.  Reason: %d", param1, param2);
}
/* If the menu has ended, destroy it */
else if (action == …
```
=> Implement per-client randomized menus with MenuShufflePerClient native.

.gitignore, .travis.yml, AMBuildScript, configure.py, core/AMBuilder, core/logic/AMBuilder, core/sourcemod.cpp, extensions/bintools/AMBuilder, extensions/clientprefs/AMBuilder, extensions/cstrike/AMBuilder, extensions/curl/AMBuilder, extensions/curl/curl-src/lib/AMBuilder, extensions/geoip/AMBuilder, extensions/mysql/AMBuilder, extensions/regex/AMBuilder, extensions/sdkhooks/AMBuilder, extensions/sdktools/AMBuilder, extensions/sqlite/AMBuilder, extensions/tf2/AMBuilder, extensions/topmenus/AMBuilder, extensions/updater/AMBuilder, loader/AMBuilder, tools/buildbot/PackageScript, tools/buildbot/bootstrap.pl, versionlib/AMBuilder
This is a pretty big diff because SourceMod had lots of multi-arch
workarounds that can now go away. I've also changed 'x64' to 'x86_64' in
many places since this is how AMBuild normalizes it, and it's far too
late to pick the shorter string, so we might as well suck it up.
The --target-archs parameter has been replaced with --targets. It works
the same way.
The default behavior for SDK inclusion is now "present" instead of
"all" since this lowers the burden of storing many SDKs. Official builds
will still be made with --sdks=all.
Multi-arch builds on Windows now work. However, they will not work on our buildbot yet, we'll need to change how the environment is set up to make that work.
=> Update to AMBuild 2.2.

extensions/sdkhooks/extension.cpp, public/extensions/ISDKHooks.h
This is causing crashes with existing extensions using entity listeners.
Currently no one is asking for a C++ hook here, if it is desired it
needs to be done with proper versioning of the listener interface, which
is going to be a little bit more complicated without an initial hard
break.
https://forums.alliedmods.net/showpost.php?p=2715337&postcount=789
https://discordapp.com/channels/335290997317697536/335290997317697536/748101258186850334
This is a partial revert of #1078.
=> Remove OnEntitySpawned C++ listener

core/ConCmdManager.cpp
Fixes "Command Group" override type getting set wrong flags upon the creation of the command group override.
One way to test this broken behaviour is to:
1. Create an admin command with ADMFLAG_ROOT admin flags initially and assign it under a command group `MyTestGroup`.
- `RegAdminCmd("sm_testcommand", Command_Test, ADMFLAG_ROOT, "Description", "MyTestGroup");`
2. Create a command group override within `admin_overrides.cfg` - `"@MyTestGroup" ""`.
3. Make sure you do not have ROOT permissions, boot up the server and observe that you cannot access "sm_testcommand".
=> Fix "Command Group" override type admin flags

gamedata/sdkhooks.games/game.l4d2.txt, gamedata/sdktools.games/game.left4dead2.txt
Updates Gamedata for upcoming Left4Dead2 update, which is set to release on 2020/09/24.
There's a new vtable entry early in CBaseEntity that pushes everything else up. 
Verified that latest sourcemod 1.10 stable runs on windows srcds & loads all default plugins. Verified "!slay" works with these gamedata changes.
Did more extensive testing on Linux srcds with sourcemod 1.10 and ran into no issues.
Did not test MacOS but the additional vtable entry appears there as well.
=> Update L4D2 Gamedata for 2.2.0.0

tools/buildbot/bootstrap.pl
This should work around a bug explained by dvander below.
```
<dvander> the reason is that ambuild 2.2 uses the multiprocessing module which is extremely buggy on 2.7, and on windows it accidentally loads the database in every process
```
Launching configuration with python3 should solve this step.
=> Use Python 3.x for 1.10 Windows builds

tools/buildbot/startbuild.pl
A missing piece of the puzzle. In addition to the changes made on #1352, we also need to explicitly execute the py3.8 ambuild. 
Tested ok
=> NPOTB: Start builds with python 3.8 ambuild explicitly

extensions/sdktools/vhelpers.cpp
Fixes some quirks with `sm_dump_netprops_xml`. I ran into some problems parsing this a few months back.
Adds an main tree.
Netprops can commonly use `"` in their names (`"healing_array"` in TF2 for example), but xml supports using both single and double quotes in attribute values, so now it opts to put in single quotes.
Edit:
I've provided a [sample netprop dump for TF2](https://hatebin.com/oofbfrcmcu) along with a [basic Python script](https://hatebin.com/oofbfrcmcu) so you can compare the difference between them if you'd like. Script will fail with current command functionality.
=> Fix sm_dump_netprops_xml

tools/buildbot/PackageScript
Fixes #1344 
Just a small regression from #1336 - we need to keep sourcemod_mm inside of /bin/ where metamod:source expects it.
x64 builds should now load fine out of the box
=> NPOTB: Keep sourcemod loader bin in /bin/

core/logic/CDataPack.cpp, core/logic/CDataPack.h, core/logic/smn_datapacks.cpp
Killing CDataPack's cache has been something on my list for a while - I'm not exactly sure when this became so easy (probably once IDataPack died), but here we are.
Technically, before this patch, we'd hold on to datapacks forever and their memory was never freed, we'd just save them for reuse. I do not think we're concerned anymore with the cost of allocating and deallocating this memory as-needed, so I'm just removing some bloat here.
=> Kill CDataPack cache

core/logic/smn_gameconfigs.cpp, plugins/include/sourcemod.inc
Adds a method of acquiring a function address via its signature from a GameData handle. I find this most useful with DHook detours, especially the "half-made" ones (detours that use gamedata solely for its signature and not parameters or anything else) that can use this for more streamlined creation.
Would convert something like this
```cs
GameData conf = LoadGameConfigFile("tf2.condmgr");
Handle hook = DHookCreateDetour(Address_Null, CallConv_THISCALL, ReturnType_Void, ThisPointer_Address);
DHookSetFromConf(hook, conf, SDKLibrary_Server, "CTFPlayerShared::AddCond");
// ... Etc
delete conf;
```
to
```cs
GameData conf = LoadGameConfigFile("tf2.condmgr");
Address addr = conf.GetMemSig("CTFPlayerShared::AddCond");
Handle hook = DHookCreateDetour(addr, CallConv_THISCALL, ReturnType_Void, …
```
=> Add GameData.GetMemSig

extensions/sdktools/vcaller.cpp
Server will be crash with next code on windows
@asherkin answered this
https://canary.discordapp.com/channels/335290997317697536/335290997317697536/746316421134548993
#include <sdktools>
{
StartPrepSDKCall(SDKCall_Static);
PrepSDKCall_SetSignature(SDKLibrary_Engine, "@CreateInterface", 0);
PrepSDKCall_AddParameter(SDKType_String, SDKPass_Pointer);
PrepSDKCall_AddParameter(SDKType_PlainOldData, SDKPass_Pointer, VDECODE_FLAG_ALLOWNULL);
PrepSDKCall_SetReturnInfo(SDKType_PlainOldData, SDKPass_Plain);
Handle h= EndPrepSDKCall();
int IVModelRender = SDKCall(h, "VEngineModel016", 0);
PrintToServer("IVModelRender 0x%X", IVModelRender);
delete h;
}
This PR fixed it
=> Fix PrepSDKCall_SetSignature on Windows

gamedata/sdkhooks.games/game.zpanic.txt, gamedata/sdktools.games/game.zpanic.txt
Hello,
ZPS has recently been updated to version 3.1 which brought about changes to the gamedata files. Here is what was updated:
- Updated offsets for sdkools/sdkhooks (Windows and Linux)
- Updated "FindEntityByClassname" windows signature for sdktools.
I ran a few tests with several plugins to make sure of the changes and, so far, everything seems to be working. If there are any questions/concerns, please let me know.
=> [ZPS] Gamedata update for sdktools/sdkhooks

core/smn_entities.cpp
Stumbled across this on the forum, https://forums.alliedmods.net/showthread.php?t=327642.
> I don't know what I'm doing wrong here but when I dump the netprops it says that "m_szCrosshairCodes" is a string but when I try to get it through sourcemod it doesn't work.
> 
> ```
> char szCrosshair[64];
>     
> GetEntPropString(GetPlayerResourceEntity(), Prop_Send, "m_szCrosshairCodes", szCrosshair, sizeof(szCrosshair), client);
> 
> PrintToServer("Crosshair Code: %s", szCrosshair); 
> ```
> This is the error that happens:
> ```
> L 10/01/2020 - 18:28:23: [SM] Exception reported: SendProp m_szCrosshairCodes is not a string (6 != 4)
> L 10/01/2020 - 18:28:23: [SM] Blaming: bot_stuff.smx
> L 10/01/2020 - 18:28:23: [SM] Call stack trace:
> L 10/01/2020 - 18:28:23: [SM]   [0] GetEntPropString
> L …
```
=> Sendprop string fixes

plugins/basecomm/gag.sp
Lets say we have override the sm_unmute command and changed it to ADMFLAG_CUSTOM1.
Then create an admin, we gived our admin ADMFLAG_Chat flag, admin can't use sm_unmute command cause it doesnt have access to this command.
But if admin go into "!admin" menu then, he will able to run sm_unmute on "player command" menus
this vulnerability also affects mute,gag and silence commands
=> Improvements on !admin menu flags

AMBuildScript
None of the available usage options have any use for such a warning.
=> Remove verbose `hl2sdk-X not found` warning

plugins/basebans/ban.sp, plugins/basecommands/kick.sp, plugins/basecommands/who.sp
Let's say we have kick flag but don't have admin menu flag.
When we type !kick, menu opens with a back button, when we click back button, we go parent menu without admin menu flag
=> Fixed unauthorized menu usages

AMBuildScript
Another small regression from #1336 
Fixes #1343
I wasn't sure exactly how to format this, or how to get the platform from inside of this context - so instead of displaying platform we just show what build targets couldn't be found. I figure ignoring the platform here is fine
=> NPOTB: Fix no SDK target exception

plugins/include/clientprefs.inc
Just like the behavior of functions like CreateArray which return ArrayList, cookie functions should return Cookie.
=> Update cookie funcs to return Cookie methodmap

core/logic/smn_adt_trie.cpp, plugins/include/adt_trie.inc
Nothing fancy here, just a new native to check if a key exists in a trie.
It helps to avoid to create a dummy variable when using GetTrieXXX() to check a key existence.
Native name can be changed if it's not to your liking :-D.
=> Add new trie native: ContainsKey()

plugins/include/clients.inc
As coded in https://github.com/alliedmodders/sourcemod/blob/aae71612731eaa6771067a31f3a7ad34bdb0df28/core/logic/smn_players.cpp#L1405, its a "client not in game", not "client not connected".
=> Fix error description

plugins/include/menus.inc
Just noticed this when I was going through the includes, It's just a missing int for InsertMenuItem
=> Fix missed old syntax parameter in menus

core/NextMap.cpp, core/logic/PluginSys.cpp, extensions/cstrike/extension.cpp, extensions/sdktools/extension.cpp, extensions/sdktools/extension.h, extensions/sdktools/hooks.cpp, extensions/sdktools/voice.cpp, extensions/tf2/extension.cpp
Allows to e.g. reload sdktools during runtime without crashing. Useful for fast development cycles.
Tiny steps towards getting `ForceRestartAfterUpdate` to work reliably.
https://github.com/alliedmodders/sourcemod/blob/master/extensions/updater/extension.cpp#L209-L220
=> Cleanly remove all hooks on extension unload

gamedata/sm-cstrike.games/game.csgo.txt
Someone copied some control chars into the gamedata when updating signatures.
=> [CS:GO] Remove control chars from gamedata

plugins/include/dbi.inc
`SQL_MoreResults` does not exist. The note should refer to `SQL_FetchMoreResults` instead. This was found by Naleksuh and Addie: https://discord.com/channels/335290997317697536/335290997317697536/793685290509139988
=> Update note about non-existing SQL_MoreResults

plugins/sql-admin-manager.sp
This bug was found as part of justCTF 2020 in the PainterHell challenge by cypis. Thank you!
Admins with the root flag could inject their own queries towards the admin database connection.
The sql-admin-manager plugin is disabled by default.
=> Fix sql injection in sql-admin-manager plugin

.travis.yml, tools/checkout-deps.ps1, tools/checkout-deps.sh
We require Python 3 and don't want to accidentally use Python 2 if both are available.
Trying to fix travis builds.
=> Prefer python3 over python(2) in checkout-deps

core/logic/ExtensionSys.cpp, core/logic/smn_menus.cpp, core/logic/smn_sorting.cpp, core/sourcemod.cpp
=> Seed rand only once

core/logic/ExtensionSys.cpp, core/logic/PluginSys.cpp
Restrict loading of plugins to the `sourcemod/plugins` folder and require the `.smx` file extension.
Symlinks inside the `plugins` folder are fine. Apply the same path restriction to extensions as well.
This behavior was abused as part of justCTF 2020 in the PainterHell challenge by cypis. Thank you!
=> Harden plugin loading path requirements

plugins/basevotes.sp, plugins/basevotes/votemap.sp
Logging action is useful for servers’ owners with large number of admins. Actually, map votes and generic votes are not very verbose on what have been done. This request tries to improve the logging of those votes by adding maps names and question with answers in the log.
=> Improve logging on map/generic votes

core/logic/smn_players.cpp, plugins/include/commandfilters.inc
Add backwards compat stuff maybe? has Capability something ...
=> Added client id to MultiTargetFilter forward.

extensions/sdktools/vhelpers.cpp
There's an `sm_dump_netprops_xml` but not an `sm_dump_datamaps_xml` and since I went a bit nuts parsing a plain text file, I thought it would be useful to extend it into a parsable format.
This also adds the element offset for sub-class tables since I needed them for my exact purpose.
=> Add sm_dump_datamaps_xml

core/ConCmdManager.cpp, core/ConCmdManager.h
Fixes #1387 
When two separate plugins hook the same cmd and one of those plugins are unloaded (or reloaded), then the IPlugin reference is never updated on the `CmdInfo` object, therefore when we try to get the plugin handle afterwards we explode. This patch identifies plugins on the hook level as well, that way when the owning plugin is unloaded we can update the IPlugin reference to the next hook in line.
=> Update IPlugin reference on cmd hook removal

core/logic/ThreadSupport.cpp
Setting the Thread_AutoRelease flag (default when using IThreader::MakeThread) caused a use-after-free after running the thread body.
This fixes Accelerator on SourceMod 1.11 🥳
=> Fix crash when creating threads with Thread_AutoRelease

plugins/randomcycle.sp
currently, when loading randomcycle, it runs `Timer_RandomizeNextmap` twice, leading to odd behavior where the map gets changed twice after timelimit is reached. This fixes that issue by only allowing the timer to be run once per map.
=> fix issues when loading randomcycle from disabled folder

core/ConVarManager.cpp, plugins/include/convars.inc
So people passing handles to the extra data can close them, adds a new return value to check if this happened
=> Execute ConVarQueryFinished if client disconnects

core/logic/GameConfigs.cpp
I think swapping atoi for strtol correctly implements this? I haven't really read the sourcemod code before.
For issue [#1415](https://github.com/alliedmodders/sourcemod/issues/1415)
=> Allow hexadecimal and octal offsets

plugins/include/adt_trie.inc
Handle map parameter is not needed in this methodmap function.
=> Correct documentation in adt_trie.inc

plugins/include/clientprefs.inc
I added the following defines because there is almost no information about the max lengths of the cookie's name and description.
The only way place i found out the max lengths was inside the `CREATE TABLE` query inside the extension module.
(https://github.com/alliedmodders/sourcemod/blob/master/extensions/clientprefs/extension.cpp#L227-L334)
This way it will be easier to know the max lengths and also help avoiding a problem that happens when registering a cookie with a name longer than the max length.
=> Add defines for Cookie name and description max length

plugins/include/sdktools_functions.inc
Makes it a little bit clearer that `startEnt` isn't just an index to start searching from and that passing an invalid one can throw an error
=> Update FindEntityByClassname docs

core/logic/GameConfigs.cpp, core/logic/GameConfigs.h
Fixes #1381.
~~Currently marked as a draft since it's untested and there's still some fixed-size char arrays I need to look into under `AddressConf`.  Will test once those remaining things are looked at.~~ Tested in a TF2 server loaded up with a lot of gamedata.
=> Update CGameConfig members to use std::string instead of fixed-size char arrays

core/logic_bridge.cpp
In continuation of this problem - https://github.com/alliedmodders/sourcemod/pull/1028. It still exists (on linux). My option is to make the library find correct
This has been done before and it worked :) I restored it.
=> Fix matchmaking_ds for gamedata

extensions/sdktools/vsound.cpp
`IEngineSound::EmitSound` seems to be called with clients in the filter that might not be `IsInGame()` which can throw an error when using a `NormalSHook` and returning `Plugin_Changed` since all the clients will will be checked if `IsInGame()`.
Using `CBroadcastRecipientFilter` would add all players than can be grabbed with `UTIL_PlayerByIndex` and is probably cause of `EmitSound` having clients that are not `IsInGame()`.
This PR has been changed to remove clients from the `players` array that are not `IsInGame()`. Also a check for the callback-provided `size` variable has been added
<details>
<summary>previously</summary>
Removing the `IsInGame()` check should be fine since `EmitSound` eventually uses `CGameClient::IsActive()` to only send to active clients.
`EmitSound` -> …
=> NormalSHook erroring on non-IsInGame clients

tools/buildbot/package.pl
Apparently you can't unpack and uncompress in one go in Windows and tar -C doesn't affect the input file.
=> Fix unpacking of GeoLite2 database

configs/core.cfg, core/sourcemod.cpp
Adds a new option to core.cfg to configure the debug/profiling metadata written by the JIT.
Depends on alliedmodders/sourcepawn#533.
=> Expose SourcePawn JIT metadata config

extensions/sdkhooks/extension.cpp, plugins/include/sdkhooks.inc
To disable entirely the call of "**EntityX::Think()**", using the property "**m_nNextThinkTick**" is enough.
But sometimes I want to use the "**EntityX::Think()**" to do something else, i.e. to replace it with my own code.
In SDKHook_Think callbacks, the returned value need to be taken into account to do this.
=> Take into account the returned value in SDKHook_Think callbacks

core/logic/smn_core.cpp, plugins/include/sourcemod.inc
Closes #1375.
This adds a new optional parameter to `StoreToAddress`, allowing plugins to opt out of having SourceMod update page permissions every time it writes to memory.
Tested in TF2 with the following micro benchmark:
<details>
<summary>Micro benchmark source code:</summary>
```
#pragma semicolon 1
#include <profiler>
RegAdminCmd("test_memwrite", MemWrite, ADMFLAG_ROOT);
}
#define NUM_ITERATIONS (1 << 19)
public Action MemWrite(int client, int argc) {
if (!client) {
return Plugin_Handled;
}
int health = GetEntProp(client, Prop_Send, "m_iHealth");
int healthOffs = FindSendPropInfo("CTFPlayer", "m_iHealth");
Address pHealthOffs = view_as<Address>(view_as<int>(GetEntityAddress(client)) + healthOffs);
Profiler …
```
=> Add parameter to configure updating page permissions in StoreToAddress

extensions/sdktools/vnatives.cpp, plugins/include/sdktools_functions.inc
Some comments after #1507 was accepted addressed that `SetCollisionGroup` should be renamed to `SetEntityCollisionGroup` to align with other similar natives.
=> SetCollisionGroup -> SetEntityCollisionGroup

plugins/basetriggers.sp
This increases the buffer to store the map name to be consistent with the other calls to GetCurrentMap. Also `currentmap` now uses the map's display name similar how `nextmap` uses it.
=> Increase buffer size for map name & DisplayName

core/sourcemod.cpp, extensions/sdkhooks/extension.cpp, extensions/sdkhooks/extension.h, plugins/include/sdkhooks.inc, plugins/include/sourcemod.inc
Newer Source engine versions now use a dynamically allocated buffer for
the map entity lump, and some maps have over 16MB of entity data - far
larger than our 2MB limit.
There is no sane way we can currently handle this, so just remove the
functionality from the forward until a more comprehensive API can be
designed.
The change in behaviour to the OnLevelInit forward params isn't obvious
when compiling a plugin, deprecate it to make it a lot more obvious that
something has changed.
Some plugins rely just on the timing of OnLevelInit rather than doing
anything with the entity lump, for these plugins offer a new OnMapInit
forward that is implemented in core rather than sdkhooks. If / when we
offer a new entity lump manipulation API in the future this'll be the
forward where it can be used …
=> Remove entity lump manipulation from OnLevelInit

public/CDetour/detourhelpers.h
On Linux if a detour crossed a page boundary we would only change the
memory protection of the first page (as we were aligning the address as
required, but not taking into account the length).
I don't have an easy way to test this but it looks correct. `addr + len`
doesn't appear to need to be aligned though, so another option could be
to use `(addr - startPage) + length` as len.
Also fixed a non-zero offset being passed into CDetour's ApplyPatch
function - this is never done internally anywhere, but it doesn't hurt
to fix it.
Fixes #984
=> Handle detour patches across page boundaries

core/smn_entities.cpp
When variant support was added for props, the validation checks in the
float related functions weren't updated to allow them.
Tested with the plugin from the forum thread with a spawned
`math_counter`.
Fixes #1501
=> Fix reading/writing float variant-based props

extensions/cstrike/rulesfix.cpp, extensions/cstrike/rulesfix.h
These changes fix the malfunction of libraries working with the SteamWorks SDK. For example, https://github.com/KyleSanderson/SteamWorks
After changes #614
Co-Authored-By: @komashchenko
=> Fix broken libraries with the SteamWorks SDK (CS:GO)

core/smn_entities.cpp
When a netprop is an array the name resolves to the outer DataTable
array, which we then need to recurse into to find the actual prop.
For string_t props we need their sendprop info to call the proxy
function to get their real storage address, but when accessing an array
we were trying to read the prop off the outer DataTable prop, rather
than the real string_t prop. Fix this by using the pProp variable that
FIND_PROP_SEND helpfully provides for us.
Tested by writing/reading the `m_szCrosshairCodes` array, which got
changed to a string_t prop sometime since #1372.
Fixes #1484
=> Fix reading/writing string_t array netprops

core/ConVarManager.cpp, core/ConVarManager.h, core/smn_console.cpp, plugins/include/convars.inc
Similar to the recent work for commands, track and expose the creating
plugin for convars. The first plugin to register a given cvar becomes
the owner until that plugin is unloaded. If a plugin attempts to
register a convar that was already registered and the originally
registering plugin has been unloaded, that plugin becomes the owner.
This isn't quite as nice as the way commands shift "ownership" as
plugins are unloaded, but we don't have a sane data structure currently
to implement that, and it seemed like a lot of unnecessary work as there
shouldn't really be multiple plugins with conflicting cvars.
Closes #1492
=> Track the creating plugin for convars

core/ChatTriggers.cpp, core/ConCmdManager.cpp, core/ConCmdManager.h, public/sm_namehashset.h
SM internally maintained both a case-sensitive and a case-insensitive
lookup method for commands, where the case-sensitive hashmap was used as
a fast path, and case-insensitive iteration over a list used as the slow
path if a command was not found in the hashmap. But only command
dispatch handling used this dual path approach, chat triggers for
example only did a loopup in the hashmap.
Over the years Valve has made more and more of the command dispatch
logic case-insensitive to the point where all console commands are now
case-insensitive, so maintaining case sensitivity when using chat
triggers does not make a lot of sense. There are somewhat popular
plugins that attempt to "correct" this behaviour - but at least one is
having issues after the previous case-sensitivity fixes for commands …
=> Make all command lookup case-insensitive

core/vprof_tool.cpp, core/vprof_tool.h
Some engines are very sensitive to exactly when in a frame vprof is
enabled, the vprof commands use a special command registration method
to defer their execution to the start of the next frame. Instead of
starting/stopping vprof directly ourselves, use the built-in commands
to ensure that the timing is correct and the server does not crash.
Fixes #1162
=> Fix vprof crashing in some games

core/MenuStyle_Radio.cpp, gamedata/core.games/common.games.txt
Some games have implemented CHudMenu::SelectMenuItem to close the menu
even if an invalid slot has been selected, which causes us a problem as
we'll never get any notification from the client and we'll keep the menu
alive on our end indefinitely. For these games, pretend that every slot
is valid for selection so we're guaranteed to get a menuselect command.
We don't want to do this for every game as the common SelectMenuItem
implementation ignores invalid selections and keeps the menu open, which
is a much nicer user experience.
Fixes #1385
=> Detect invalid menu item selections in L4D-based games

core/TimerSys.cpp, core/TimerSys.h, core/sourcemod.cpp
This has been asked for and debated in some form since Valve introduced
hibernation into the Source engine. The changes here are based on quite
a deep dive into the engine's frame/think logic (mainly in CS:GO which
has "legacy" hibernation and TF2 which has modern "frameless" ticking)
and all seem to be sane.
I think I've managed to maintain all the oddities around time keeping,
and the simulated bool (even though we don't really use it for anything)
should have a sane value. There is a slight behaviour change for
anything needing exact timings as we're now run earlier in the frame
before gpGlobals are updated, this should generally be fine but it might
affect some plugins such as bhop timers that are trying to be extremely
precise (often more precise than the underlying data they're …
=> Switch internal SM concept of frames to use Think

plugins/include/mapchooser.inc
Macro `#if !defined REQUIRE_PLUGIN` on __pl_mapchooser_SetNTVOptional was missied in mapchooser.inc
=> Set macro on __pl_mapchooser_SetNTVOptional

core/logic/CDataPack.cpp
WriteCellArray and WriteFloatArray were allocating N+1 slots, but due to
a copy-paste error were writing N+2 slots. Much later in the process the
CRT would catch this and cause a crash - this was pretty painful to
debug but thankfully running SRCDS in CRT debug mode caught it much
sooner in CDataPack::RemoveItem.
Thanks to @dysphie for the initial report.
=> Fix out of bounds write in CDataPack::Write*Array

core/HalfLife2.cpp, core/smn_entities.cpp, plugins/include/entity.inc
FindSendPropInfo currently isn't very useful with array props, it'll
return the correct offset but the type will be unknown and the bit count
zero. Instead, populate type and num_bits with the underlying array type
info same as we'd handle it when reading/writing the prop. Closes #1258.
This also adds the preliminary support for Source's legacy / virtual
array props for issue #1386. They can now be looked up correctly with
FindSendPropInfo and it returns the correct type / size / offset.
=> Return array type info with FindSendPropInfo

extensions/sdktools/trnatives.cpp
When a custom TraceRay filter / EnumerateEntities enumerator callback
throws an exception we currently continue execution and then return
execution to the calling code as if there were no problems. This
currently causes a heap tracking issue in SourcePawn, but even ignoring
that it is likely the wrong behaviour and differs from our other
synchronous callbacks.
This change causes the exception to be caught, immediately terminates
the trace / enumeration, and propagates the exception state back to the
calling plugin correctly. The implementation here is based on how
SortCustom1D handles exceptions.
See also alliedmodders/sourcepawn#607. Thanks again to @dysphie for the report.
=> Catch exceptions from TraceRay filters/enumerators

core/PlayerManager.cpp
In #545 we started automatically fixing up invalid UTF8 characters
caused by truncated names from Steam, but since the dawn of time CPlayer
has preferred directly returning the engine's name pointer if we have
once available, so our corrected name is almost never used.
Lightly tested in CS:GO and TF2 with no ill effects. Fixes #1315
=> Always use our cached name value

core/smn_entities.cpp, extensions/sdktools/gamerulesnatives.cpp, plugins/include/sdktools_gamerules.inc
This rounds out the work started in #1548 to complete support for
reading the older SendPropArray type array netprops, along with bringing
SDKTools' GameRule netprop code in sync with core to add string array
support.
There aren't many SendPropArray type props around but this opens up a
few interesting opportunities for plugin developers, particularly in
L4D2 with manipulation of the EMS HUD.
Tested reading the `m_vCPPositions` array in TF2, and reading/writing
the `m_szScriptedHUDStringSet` EMS HUD netprop in L4D2. Closes #1386.
=> Support reading legacy sendprop arrays

extensions/sdkhooks/extension.cpp, extensions/sdkhooks/extension.h, plugins/include/sdkhooks.inc
`OnEntitySpawned` is 1.11 only, so this is fine given our API stability guarantees.
Unfortunately the forward name clashes with quite a few plugins using the same name for their SDKHook callback. Normally we'd just put up with this but there are difficult to solve binary compatibility issues where those plugins will get the callback double-called, and there is a separate issue where the forward isn't called for all entity spawns (unlike the SDKHook), so most plugins can't switch to the forward anyway.
Resolves #1558.
=> Remove OnEntitySpawned forward

gamedata/sdkhooks.games/engine.csgo.txt, gamedata/sdktools.games/engine.csgo.txt
Unsure why diff change acts weird for the sdkhooks gamedata, encoding and line endings should be the same. Tested both on linux and windows according to SMs discord.
=> Update gamedata after latest CSGO update (22/09/21)

extensions/tf2/criticals.cpp
`CritManager::Hook_CalcIsAttackCriticalHelpers()` is a pre-hook that calls the appropriate helper function, then passes the result over to plugins to determine whether the value should be changed.
The issue is that `MRES_IGNORED` is used to return after calling the helper function if the result is `Pl_Continue`, causing the helper function to be called a second time after the function, resulting in the server's crit calculations desyncing from the clients'.  This PR stores the original return value and supercedes so it only ever gets called once.
Tested on a fresh server with the below plugin to listen for crits (and to force the hook to be enabled).  Without the fix, a Soldier's rocket may have glow without the sound or vice-versa; with the fix applied, the rocket will have both or …
=> TF2Tools: Prevent CalcIsAttackCriticalHelper* from being called twice

extensions/sdktools/vnatives.cpp, gamedata/sdktools.games/game.left4dead2.txt
The method 'CCSPlayer::GiveNamedItem(char const*, int, CBaseEntity*)' does not work in game left4dead2, any given weapon or item immediately falls to the ground, besides, the code is missing a parameter to call this method (even with the added parameter does not give a weapon or item to hands). Another method 'CTerrorPlayer::GiveNamedItem(char const*, int, bool, CBaseEntity*)' works great, besides it makes it possible to give out all the items that exist in the game.
=> Fix 'GiveNamedItem' in the game left4dead2.

gamedata/sdktools.games/game.nmrih.txt
`GiveAmmo` on Windows is off by 1 and leads to a crash. Linux offsets don't need updating
=> Fix NMRiH 'GivePlayerAmmo' crash on Windows

bridge/include/CoreProvider.h, core/logic/GameConfigs.cpp, core/logic/sm_crc32.cpp, core/logic_bridge.cpp, core/provider.h
- Changes the CRC implementation to match what appears to be most other popular implementations.
- Fixes server bin name lookup, broken for most engines.
=> Fix up gamedata CRC functionality

gamedata/sdktools.games/game.nmrih.txt
Unfortunately the previous gamedata patch had a faulty offset that slipped thru testing, my bad. 
This fixes ForcePlayerSuicide crashing on Linux
=> Fix "ForcePlayerSuicide" crash in NMRiH

gamedata/sdkhooks.games/engine.ep2v.txt, gamedata/sdktools.games/game.tf.txt, gamedata/sm-tf2.games.txt
Update on 2021-11-16 broke things again due to the addition of 3 new virtual functions to `CBaseEntity`.
```
CBaseEntity::IsProjectileCollisionTarget() const
CBaseEntity::IsFuncLOD() const
CBaseEntity::IsBaseProjectile() const
```
Shift all virtual offsets over 86 up by 3.
=> Update Team Fortress 2 gamedata

core/logic/MemoryUtils.cpp, core/logic/MemoryUtils.h
Always perform signature searches on an unaltered copy of the binary. This avoids signature mismatches if the same function is detoured twice and thus the first bytes of the function were replaced by the detour. It is implemented by creating a copy of the current (hopefully unaltered) state of the library on first symbol or signature lookup through `IMemoryUtils` and using that copy to find matching signatures.
Now you're able to find signatures even if something else already messed with the bytes. Before this patch, code like this would fail to locate the signature again after the memory was altered (assuming both gamedata files are identical).
```sourcepawn
GameData gd = new GameData("test1.games");
Address testfunc = gd.GetMemSig("testfunc"); …
```
=> Cache copy of library on first symbol/signature lookup

extensions/sdkhooks/extension.cpp
Fixes #1650
As pointed by @asherkin over discord the use of `META_RESULT_OVERRIDE_RET` or `META_RESULT_ORIG_RET` within a non post hook is wrong. This PR fixes that.
I'm not super familiar with sourcehook, so my fix could be horribly wrong. If I'm wrong, at the very least this PR will kick off a discussion? I was also tempted to replace the `META_RESULT_ORIG_RET` line with an `SH_CALL` instead, but this would end to essentially turning the function into a post hook.
_Smallest PR in the small west ?_
=> Change ShouldCollide to a posthook

plugins/basevotes.sp, plugins/basevotes/voteban.sp, plugins/basevotes/votekick.sp, plugins/basevotes/votemap.sp
This should patch will revive our dead builders which would get stuck on a `_GNU_SOURCE` redefinition or eventually fail due to this shadowed variable.
=> Prevent enum shadowing & pin sourcemod for build fixes

tools/buildbot/package.pl
Delete package file after successful upload rather than eventually running out of space.
=> [Buildbot] Delete package after successful upload.

extensions/sdkhooks/natives.cpp
=> Fix crash in non-bypass-hooks DropWeapon implementation

plugins/include/adt_array.inc
[ArrayList.SetString](https://github.com/alliedmodders/sourcemod/blob/86363dd3ecf27d57ad1bfe01d63fee68b435291a/core/logic/smn_adt_array.cpp#L383) and [ArrayList.SetArray](https://github.com/alliedmodders/sourcemod/blob/86363dd3ecf27d57ad1bfe01d63fee68b435291a/core/logic/smn_adt_array.cpp#L416) both have int return types but their methodmap natives use void.
There might be others but I only found these 2.
=> Fix ArrayList return types

core/logic/smn_adt_stack.cpp, plugins/include/adt_stack.inc
Provide an ArrayStack.Clear method since this really has no reason not to exist.
Left out the non-methodmap native since I was told it wasn't needed.
I didn't write a test plugin since because ArrayStack just uses a CellArray under the hood, this _completely_ re-uses the code from ArrayList.Clear. I assume that's ok?
=> Add ArrayStack.Clear native

core/logic/smn_adt_array.cpp
If there isn't enough memory to resize the ArrayList to the startsize on construction, throw an error instead of ignoring the OOM.
Fixes #1551
=> Fix silent error on large ArrayList startsize

plugins/include/dhooks.inc, plugins/include/functions.inc, plugins/include/sourcemod.inc, public/IGameConfigs.h, public/IGameHelpers.h, public/asm/asm.c
- Modifies whitespace (change tabs to spaces for non initial indents, fix alignments, create consistency with rest of SM docs)
- Change `/*` to `/**` for consistency and to indicate comment doc
- Split long comments across multiple lines
- Removes incorrect `@noreturn` doc usages
- Add `@noreturn` and `@error` to Throw(Native)Error
- Fix typo (retunr -> return)
=> Update documentation for consistency

plugins/nextmap.sp
Black Mesa now ships with mapcycle.txt., so the check can be removed.
Tested and working.
https://github.com/alliedmodders/sourcemod/pull/331/commits/909598920ba28722f3612266b42416fc798a605c
=> Enable nextmap for Black Mesa

core/smn_entities.cpp
FindSendPropOffs is deprecated and FindSendPropInfo behaves correctly
here, but there are still a lot of old plugins using FindSendPropOffs.
One of the SendPropArray props broken by the changes here is
m_hViewModel which there are known plugins in the wild accessing.
Resolves #1701.
<details>
<summary>This shows the output of FindSendPropInfo and FindSendPropOffs for a SendPropArray prop, a SendPropArray3 prop, and a SendPropArray2 prop (and its separate inner prop manually looked up).</summary>
Code:
```sourcepawn
#include <sdktools>
DumpPropInfo("CBasePlayer", "m_hViewModel"); // SendPropArray
DumpPropInfo("CBasePlayer", "m_hMyWeapons"); // SendPropArray3
DumpPropInfo("CTeam", "\"player_array\""); // SendPropArray2
DumpPropInfo("CTeam", …
```
=> Fix FindSendPropOffs with SendPropArray props

extensions/sqlite/driver/SqResults.cpp, extensions/sqlite/driver/SqResults.h
The DB API requires FetchRow to be called before accessing any values
from a row, but the SQLite driver did not enforce that requirement and
alowed accessing the first row immediately. A plugin developer hit this
when developing against SQLite locally but using MySQL in production,
where the API misuse threw an error as expected.
Resolves #1691
=> Stop SQLite results being used before being fetched

plugins/include/clients.inc
I feel like this is sorely missing since I've had to define it in so many plugins I've written.
The maximum theoretical size of a 'valid' SteamID (according to the valve wiki) is 23 bytes including null `STEAM_255:1:2147483647`. 
The only exception that I know of is `STEAM_ID_STOP_IGNORING_RETVALS` which is 31\* bytes including null.
In the interest of keeping that error value meaningful, either:
- It should be changed to fit within 23 bytes, which could potentially break something for no reason.
- There should be only 1 constant for the size of a SteamID that not only fits every type of ID but also the error message.
=> Add MAX_STEAMID_LENGTH

plugins/include/string.inc
Noticed that these return byte/char count rather than cells. I replaced the return doc string with the one from [`Int64ToString`](https://github.com/alliedmodders/sourcemod/blob/f603b7aec3219e0db56882447b35a57afe4c6d8a/plugins/include/string.inc#L226-L227)
A small example for testing and the output I got
```
char buf[12];
int x = FormatEx(buf, sizeof(buf), "asdf");
int y = Format(buf, sizeof(buf), "jkl;ll1");
int z = strcopy(buf, sizeof(buf), "11111");
int a = IntToString(22222, buf, sizeof(buf));
int b = FloatToString(1.0533, buf, sizeof(buf));
PrintToServer("%d %d %d %d %d %s", x, y, z, a, b, buf);
```
`4 7 5 5 8 1.053300`
=> Correct some function docs that return char count

core/logic/smn_string.cpp
The `Int64ToString` method introduced in https://github.com/alliedmodders/sourcemod/commit/f603b7aec3219e0db56882447b35a57 does not currently operate as expected/produce the correct output for certain values. This PR adjusts the typecasts to ensure that the bitwise OR operation works as expected.
The following string inputs (fed through `StringToInt64` first) result in the following string outputs prior to this patch:
* in: -9999999999 / out: -1410065407
* in: 2286852952 / out: -2008114344
* in: 4294967295 / out: -1
While the second and third examples technically fit within 32 bits, because all ints in pawn are signed, the most significant bit is used for two's complement. This means that any value between the int32 max (2,147,483,647) and the uint32 max (4,294,967,295) must be stored …
=> Fix Int64ToString producing incorrect output

plugins/include/dhooks.inc
`DynamicHook.RemoveHook` fires the removal callback despite its documentation saying otherwise.
This was briefly discussed in the AM guild:
> [4:38 AM] Mikusch: Am I going crazy or is the documentation for DynamicHook.RemoveHook lying to me
> [4:42 AM] Mikusch: @Peace-Maker Is the documentation or implementation wrong?
> [9:00 AM] Peace-Maker: Looks like the documentation, but I didn't write that code @Dr!fter
> [10:27 AM] Dr!fter: Indeed documentation. Not sure which should be fixed. Probably docs?
> [11:19 AM] Peace-Maker: I think so too. Was there a reason the callback shouldn't be called when a hook gets removed by that native? I don't see one
> [11:20 AM] Dr!fter: Not that I can think of.
> [11:21 AM] Dr!fter: In fact it would reduce duplicate code since if you do something in the …
=> Remove incorrect note on DynamicHook.RemoveHook docs

plugins/funcommands/fire.sp, plugins/funcommands/gravity.sp, plugins/include/console.inc
Adding since there are stocks to handle int values but nothing for float.
=> Add GetCmdArgFloat(Ex) stocks

plugins/basevotes.sp, plugins/funvotes.sp
This patch allow ROOT flag to call votes even if a delay is set. Its nice to have the possibility to set a delay betweens votes to limit public votes. Generally, we do this when we have lots of admins. But as a ROOT flag this limit shall no be set.
=> Allow ROOT flag to call public votes

extensions/sdktools/vnatives.cpp, gamedata/sdkhooks.games/game.zpanic.txt, gamedata/sdktools.games/game.zpanic.txt, plugins/include/clients.inc
Adds support for the SDKHook Types: OnTakeDamage_Alive, GroundEntChanged, GetMaxHealth, Blocked and Reload.
Adds support for GivePlayerAmmo native.
I would have added them earlier but wasn't aware they were missing entirely.
=> ZPS: Add missing offsets

tools/checkout-deps.sh
If you just want to build an extension or SourceMod core and not the MySQL extension, don't download the large MySQL library archive.
=> Add -m flag to checkout-deps to avoid downloading MySQL

extensions/dhooks/natives.cpp, plugins/include/dhooks.inc
The param had to be a valid entity and wasn't allowed to be set to NULL. Behave similar to SetReturn which maps INVALID_ENT_REFERENCE (or -1) to NULL.
Fixes #1751
=> DHooks: Allow setting CBaseEntity* param to NULL #1751

extensions/sdktools/extension.cpp, extensions/sdktools/extension.h, extensions/sdktools/vglobals.cpp, extensions/sdktools/vglobals.h
As discussed in #1694, this PR fixes an issue where the gamerules pointer would not be cleared on level shutdown, leading to crashes when natives like `TF2_IsHolidayActive` try to access it before it's populated again.
=> Clear gamerules pointer on level shutdown

extensions/tf2/holiday.cpp, extensions/tf2/holiday.h
Fixes #1747
After a map change, the virtual hook on `IsHolidayActive` will be invalid due to the gamerules object being destroyed, but current code does not attempt to hook it again if a plugin using the `TF2_OnIsHolidayActive` forward is still loaded.
Always unhook on level change, and check for plugins using the forward only in `HolidayManager::OnPluginUnloaded`.
=> Fix TF2_OnIsHolidayActive forward not getting called after map change

extensions/sdktools/hooks.cpp, extensions/sdktools/hooks.h, plugins/include/sdktools_hooks.inc
As requested in this issue #1759, adds a OnPlayerRunCmdPre forward for use with certain plugins which want access to unmodified usercmds.
The name isn't ideal, but after a little discussion in the Discord, we've not been able to come up with anything better.
I'm also a little unsure if `hasUsercmdsPreFwds` and `hasUsercmdsFwds` are the correct formatting for the new varaibles.
I don't have an easy means to test this right now, so the changes are currently untested.
Closes #1759
=> Add a OnPlayerRunCmdPre forward

plugins/nominations.sp
This should fix nomination items appearing with workshop prefix in the results menu and when items are disabled.
Other solution to fix this is to **always** redraw the nomination items, lemme know if that's preferred.
This issue was found by @busheezy, thanks to him.
=> Fix formatting nomination items

plugins/include/timers.inc
- The typeset entry for `(Handle, Handle)` is already covered by `(Handle, any)`, so has no reason to be here.
- Modified default parameter of CreateTimer for consistency with other includes and because it isnt exclusively a Handle type.
=> Timer semantics & remove unnecessary typeset entry

plugins/include/sdktools_functions.inc
=> Add "DispatchKeyValueInt" stock

gamedata/sm-cstrike.games/game.csgo.txt
seems like https://github.com/alliedmodders/sourcemod/commit/f7cd28cfd36e73652172fe81c93892dba6d87a94 pr a wrong gamedata for win
=> fix WeaponPrice offset on windows

core/logic/Database.cpp, core/logic/Database.h, core/logic/DatabaseConfBuilder.cpp, core/logic/DatabaseConfBuilder.h, core/logic/smn_database.cpp
This patch `ke::RefPtr`'s the database configs in storage instead of storing raw `ConfDbInfo*`s. I'm not certain if the original form caused any problems, but in my recent review of this area I was very dissatisfied.
Also, the config lists have been converted to be value types instead of pointers. I'm not certain why I made these lists pointers, but this patch overall makes this section much safer.
untested
=> Lift raw pointers out of DatabaseConfBuilder

extensions/dhooks/natives.cpp
We always created a new vector object instead of changing the passed in vector directly instead. This works for the function being called using our changed values - but the caller doesn't see the changed values if it's passing a vector by reference.
Only create a new vector if there isn't one being passed in and set the values directly in the passed in vector otherwise.
=> DHooks: Fix changing of byref vector parameters

extensions/dhooks/natives.cpp, extensions/dhooks/signatures.cpp, extensions/dhooks/vhook.h
The passflags are only supported by SourceHook for virtual hooks and are ignored for detours with DynamicDetours. This caused confusion, so throw an error when trying to set e.g. the `DHookPass_ByRef` flag on detour arguments.
=> DHooks: Error on argument passflags for detours

.gitmodules
If the full commit history isn't needed, this is probably free speed up for checkout.
=> .gitmodules: Make submodules shallow

extensions/sqlite/sqlite-source/sqlite3.h
Bring in the changes of the last four years of SQLite development. I didn't update to 3.39.0 right away, since it was released only 4 days ago and didn't have time to cool off yet.
Fixes #1728
Fixes #1592
=> Update SQLite library to 3.38.5

extensions/sdktools/vcaller.cpp
Caught this from TF2 update where some serverside ents are no longer networked. This is supposedly missed when support for non-networked ents was added.
Quick-tested this in TF2 windows.
=> Add support for SDKCall returning non-networked entity

plugins/nominations.sp
This reverts a change introduced in https://github.com/alliedmodders/sourcemod/commit/b8fd7db58d34c9ee5c0b9f2a6cea844f9d978fdb where `sm_nominate` can no longer be used from console to bring up the map menu. I don't see a reason for this existing (correct me if I'm wrong) and it's a slight annoyance for people who use binds or console a lot
=> Allow using sm_nominate without args from console

extensions/sdktools/vcaller.cpp, extensions/sdktools/vdecoder.h, plugins/include/sdktools.inc
Similar to https://github.com/alliedmodders/sourcemod/pull/1612 :)
I think this will be useful when used in plugins, where a pointer engine is needed. It will be convenient to use for vtable offsets to make it easier to call the necessary functions.
=> Exposed SDKCall_Engine call type to use CVEngineServer methods

core/PlayerManager.cpp, core/PlayerManager.h, core/logic/smn_lang.cpp, plugins/include/lang.inc, public/IPlayerHelpers.h
It seems reasonable that while there are functions to change a client's language, there should also be function to restore it back--both with the natives and also internally.
My use case for this is I was making a language selection menu and had to implement this logic manually.
In fact, every plugin that modifies the client's language would have to do so (particularly during OnPluginEnd) to be correctly written.
It makes sense then that a correct implementation is built in natively instead.
I'm not entirely sure that I'm supposed to set it inside PlayerManager::HandleConVarQuery(), but it looks like that's just an async way of getting the client's language for certain games, so I did.
Tested with the following code
```sourcepawn
{ …
```
=> Add GetClientOriginalLanguage

plugins/include/float.inc
lack of return type to the forward is breaking sptools.
=> completing operator% forward

bridge/include/CoreProvider.h, core/logic/GameConfigs.cpp, core/logic_bridge.cpp
Similar to https://github.com/alliedmodders/sourcemod/pull/1787, as https://github.com/alliedmodders/sourcemod/pull/1626 seems to be frozen at the moment.
This is necessary for a plugin modifying some vscript VM behaviour.
=> Allow gamedata to use vscript binary

gamedata/sm-cstrike.games/game.csgo.txt
Fixes `CS_GetTeamScore` crashing, untested on Windows.
Missed them in #1842 due to the CheckRestartRound/CheckWinLimit naming shenanigans.
=> Correct missed team offsets in CheckRestartRound

extensions/dhooks/DynamicHooks/hook.cpp
This fixes wrong stack memory alignment, because stack already have 4 bytes of return address at this moment in both cases: pre and post calls of hook handler.
Cherry pick in 1.11 if it needed.
Found with crash after local recompiling of SM 1.11. After dhooks jit code stack was wrongly aligned and crashed on `movdqa` instruction. 
https://crash.limetech.org/inzoqhjqfcrl
=> Fix DHooks jit code stack memory alignment

AMBuildScript
PVKII changes require at least MM:S 1.12 to build SM.
=> Bump minimum MM:S version for build to 1.12

.github/workflows/ci.yml, .github/workflows/scripting.yml
While we don't commonly have PRs against release branches, it seems like we should have CI runs when we do. It also seems useful to have the scripting archive for them.
I'm not 100% this syntax is correct but there isn't a super easy way to test it without just doing it.
=> Enable CI on release branches

core/logic/GameConfigs.cpp
The extended gameconfig format reads the master gameconf file twice, once each for the base engine and actual engine.  The file list isn't checked for duplicates, so 'common.games.txt' is loaded in twice, resulting in any 'common' file values potentially overriding values listed under '#default' in other files due to `bShouldBeReadingDefault`.  This happens in the case when matching game versions by CRC (such as public game branches).
This PR ensures each unique file is only traversed once.
Required for #1857.
=> Ensure gameconfig file uniqueness when reading master.games

plugins/adminhelp.sp
Allows using `FCVAR_HIDDEN` to block commands from appearing in `sm_help` and `sm_searchcmd` which helps with creating alias to commands without filling up the list with those aliases.
For example:
```sourcepawn
RegAdminCmd("sm_setmyperk", MyCommand, ADMFLAG_CHEATS);
RegAdminCmd("sm_setmyperks", MyCommand, ADMFLAG_CHEATS, _, FCVAR_HIDDEN);
RegConsoleCmd("ff2_boss", MyCommand);
RegConsoleCmd("ff2boss", MyCommand, _, FCVAR_HIDDEN);
```
=> Block Hidden Commands from Help Command

core/ChatTriggers.cpp, core/ChatTriggers.h, core/smn_console.cpp, plugins/include/console.inc
The main utility of being able to know what the chat triggers are is if you want to display to clients how to type commands.
e.g. `Welcome to the server! Type !rules for the server rules.`
Or for chat processing, I guess.
Although I've never even encountered a server that has changed the chat triggers--so it's usually fine for plugins to just assume that `!` and `/` are correct--it's still allowed to be changed, and currently the only way to get the actual chat triggers is processing the `core.cfg` file manually.
Tested with the following code:
```sourcepawn
{
char buffer[32];
int written;
written = GetPublicChatTriggers(buffer, sizeof(buffer));
PrintToServer("Public Triggers: '%s', written=%i", buffer, written);
written = …
```
=> Add natives to get chat trigger strings

extensions/sdktools/trnatives.cpp, plugins/include/sdktools_trace.inc
This is a pretty useful introduction that allows to use trace types such as TRACE_WORLD_ONLY, which allows to ignore the SpatialPartition algorithm, thereby reducing the call time of trace functions in some cases up to ~2 times.
=> Add custom sdktools trace types

core/logic/smn_textparse.cpp, plugins/include/textparse.inc
Resolves #1686
Tested with the code below.
*(TL;DR - Exact same output as ParseFile)*
sourcemod/configs/parsetest.cfg
```keyvalues
"Root"
{
"key1" "value1"
"key2" "value2"
"section1"
{
"key3" "value3"
"section2"
{
"key4" "value4"
}
}
}
```
parsetest.sp
```sourcepawn
char NO_NEWLINES[] = ""
... "\"Root\""
... "{"
... "    \"key1\" \"value1\""
... "    \"key2\" \"value2\""
... ""
... "    \"section1\""
... "    {"
... "        \"key3\" \"value3\""
... "        \"section2\""
... "        {"
... "            \"key4\" \"value4\""
... "        }"
... "    }"
... "}";
char WITH_NEWLINES[] = ""
... "\"Root\"\n"
... "{\n"
... "    \"key1\" \"value1\"\n"
... "    \"key2\" \"value2\"\n"
... "\n"
... "    \"section1\"\n"
... "    {\n"
... "        \"key3\" \"value3\"\n"
... " …
```
=> Add SMCParser.ParseString

extensions/sdkhooks/extension.cpp
The returned result of the last callback in the list was used instead of the highest value. This differs from the behavior of the other hooks.
The `GetMaxHealth` hook has an outparam. I've changed the return value handling to only return the changed value if `Pl_Changed` was the highest value a plugin wanted. If some plugin returned `Pl_Handled` it returns the original value. This is similar to the `TraceAttack` hook handling.
Fixes #1870
=> Fix SDKHook_[Use|Spawn|GetMaxHealth] callback result value handling

core/smn_console.cpp, plugins/adminhelp.sp, plugins/include/console.inc
Allow to access the convar flags `FCVAR_*` value from the iterator using a `ConVarFlags` property.
The `CommandIterator.Flags` property should have been called `AdminFlags`, but it's too late to change that now.
This was brought up in #1831.
=> Add CommandIterator.ConVarFlags property

core/logic/LumpManager.cpp
On NMRiH and possibly other games that use the Maphack system, entries that are modified using that system are rendered with tab characters stripped out - see `CNMRiHMapHackManager::GetEntDataString`.
That results in there being no separators at all between keys and values, as Maphack receives the serialized string from Entity Lump Manager, which uses tabs as its key / value separator.
This crash only occurs if `GetMapHackManager()->HasEntData()` is set to true, so to my understanding it would not crash on removals of entire entities, and it would not crash on maps that do not use Maphack at all.
This commit changes the key / value separator character to use spaces instead.
Fixes #1833.
=> entitylump: Output separator as spaces instead of tabs

plugins/include/halflife.inc
Add clarification to documentation for HUD messages and engine dialogs with regard to game support. The existing docs for HUD message are very out of date and not helpful.
=> Add clarification to documentation for HUD messages and engine dialogs

plugins/basechat.sp
This saves me from having to find/create a test plugin when checking for what games support this, has very low maintenance burden, and just may actually be useful for someone other than me.
"d" was chosen for the prefix over the more intuitive "h" since hint messages use that.
=> Add "sm_dsay" command to basechat for sending HUD messages

core/smn_hudtext.cpp
RE: https://github.com/alliedmodders/sourcemod/pull/1889#issuecomment-1358648671
> I was missing the SetHudTextParams call. Fixed now. I'm also going to add a check that could have caught this case and thrown an error.
These checks are far from perfect since one plugin can mask the error in another, but I still believe this is a net improvement.
=> Throw error in ShowHudText or ShowSyncHudText if HudText params not yet set

core/logic/smn_maplists.cpp
```
if (!libsys->FileTime(pMapList->path, FileTime_LastChange, &last_time)
|| last_time > pMapList->last_modified_time)
{
/* Reparse */
FileHandle_t fp;
```
Here the `pMapList->path` is not a real path, so `libsys->FileTime` will always return false so that the map file will be always reparsed.
=> Fix ReadMapList ignoring file's last modified time

core/MenuStyle_Radio.cpp, core/smn_hudtext.cpp
`StartProtobufMessage` can sometimes return a null pointer but the check for null pointer is only implemented in 7 out of 9 occurences in the repository, causing the crashes below.
https://crash.limetech.org/lf4n2nhxysdr
https://crash.limetech.org/k5iw7z2mfxe7
I am not sure how the function can return null pointer in these crashes though, I am fairly certain there was no hook that happened there.
=> Add missing null pointer check to protobuf messages

plugins/include/entity_prop_stocks.inc
This PR closes #1770 
Instead of assuming the prop name given in core gamedata is a networked property. We will instead assume it's the datamap equivalent, and is on the same offset, plus visible on every single entity as it is a CBaseEntity datamap, unlike the netprop which is only visible if the deriving class decided to have it networked.
To maintain the behaviour the old native had (mainly firing a network update, since it used `Prop_Send`) we notify the game the entity changed in order to fire a network update. And if the entity isn't networked we do nothing.
This will allow for a wider range of entity support. Granted plugins could just do `SetEntProp(entity, Prop_Data, "m_iHealth", amount)`. But Sourcemod aims at being strongly backwards compatible, therefore it is safe to say this …
=> Fix `SetEntityHealth` to support 'any' entities

core/logic_bridge.cpp, extensions/sdkhooks/AMBuilder, extensions/sdkhooks/extension.cpp, extensions/sdktools/AMBuilder, plugins/reservedslots.sp, tools/buildbot/PackageScript
The necessary interfaces are stubbed out, so the extensions can load.
This is another step towards runtime tests in CI.
=> Get sdktools and sdkhooks/dhooks to load on hl2sdk-mock

public/asm/asm.c, public/asm/asm.h
Fixes:
* `G:\sm\sourcemod\public\asm\asm.c(133): warning C4013: 'memcpy' undefined; assuming extern returning int`
* `G:\sm\sourcemod\public\asm\asm.c(106): warning C4018: '<': signed/unsigned mismatch`
=> Fix asm.c compiler warnings on Windows

core/smn_entities.cpp, plugins/include/entity.inc
Closes #1805.
Implements the ability to read / write handles located at arbitrary locations.
The native names `LoadEntityFromHandleAddress` and `StoreEntityToHandleAddress` are wordy.  Feel free to suggest alternatives.
Tested and confirmed working in TF2 with the following plugin (dumps the entity and item definition indices of each wearable on the player):
```
#pragma semicolon 1
RegConsoleCmd("sm_wearables", ListWearables);
}
Action ListWearables(int client, int argc) {
int offs_CTFPlayer_hMyWearables = FindSendPropInfo("CTFPlayer", "m_hMyWearables");
// CTFPlayer::m_hMyWearables is a CUtlVector<CHandle>
int count = GetEntData(client, offs_CTFPlayer_hMyWearables + 0x0C);
Address pData = …
```
=> Implement raw entity handle accessors

configs/core.cfg, core/MenuManager.cpp, core/MenuManager.h, core/MenuStyle_Base.cpp, core/MenuStyle_Radio.h, gamedata/core.games/common.games.txt
This change moves the specification of sound files for menu actions from core config to gamedata, allowing for different default sounds to be chosen per game, similar to what is done in funcommands for sounds and materials. This is necessary as more and more games ship without some of the stock HL2 resources.
In practice, I've never seen these changed in the core config, but utilizing the custom gamedata folder, it will still be possible to change the defaults.
=> Move menu sound selection from core config to gamedata

extensions/sdktools/tempents.cpp, extensions/sdktools/tempents.h, extensions/sdktools/tenatives.cpp, plugins/include/sdktools_tempents.inc
TF2 now has at least one tempent property that utilizes entity handles. It's possible that some other games already did as well. These new natives function similarly to both the GetEntPropEnt/SetEntPropEnt natives and the other TE_Read*/TE_Write* natives.
=> Add TE_WriteEnt and TE_ReadEnt natives to SDKTools

plugins/basecommands/map.sp
Print the full map name in LogAction instead of the args.
Exemple : !map de_
**Before:** 
`.Rushaway<150><[U:1:44340774]><> changed map to de_`
**After:**
`.Rushaway<150><[U:1:44340774]><> changed map to de_dust2`
=> fix: Print full map name in Log instead of args

plugins/include/sdkhooks.inc
Adds a little note to `SDKHook` and `SDKHookEx` hinting at the automatic unhook behavior here
https://github.com/alliedmodders/sourcemod/blob/d5a26adc493d2dfe1919ab1ff619bfb0d404ee84/extensions/sdkhooks/extension.cpp#L1847
=> Add note about automatic unhook

extensions/sqlite/AMBuilder
I'd like to use `POW` in sqlite please... (and also have this in 1.11) (also I didn't test this but this this should:tm: work)
=> Enable math functions in sqlite

core/logic/GameConfigs.cpp, core/logic/GameConfigs.h
This change updates the new GameConfig library lookup logic to better preserve the binary search path order in cases where multiple copies of a named binary live in distinct search path directories.
Fixes #1912
=> Fix gamedata library search order in some cases (fixes #1912).

extensions/sdktools/vnatives.cpp
This change adds passing of two additional parameters that Military Conflict: Vietnam has on CBaseAnimating::Ignite and children, fixing a crash that occurs when calling the IgniteEntity native.
=> Fix crash with IgniteEntity on MCV

plugins/include/timers.inc
Why not allow void-return timers when majority of uses will be non repeating timers? 😉 
If used with repeating timer by accident, the timer just won't stop.
This imitates event hooks where both Action/void returns are allowed.
=> Allow void return type in timer callbacks

core/logic/smn_float.cpp, plugins/include/float.inc
[alliedmodders/sourcepawn/#764](https://github.com/alliedmodders/sourcepawn/pull/764) added the float modulo operator but it was still unsupported in SourceMod until now.
This PR adds the required native and updates the include.
Test plugin:
```sourcepawn
#include <float>
{
float fMod1 = 7.0 % 5.0;
float fMod2 = 8 % 5.0;
float fMod3 = 9.0 % 5;
PrintToServer("%0.f, %0.f, %0.f", fMod1, fMod2, fMod3);
}
```
=> Add support for float modulo operator

.github/workflows/ci.yml
The Ubuntu 18.04 runner image is deprecated and will be unsupported on 2023/04/01. It appears Ubuntu 20.04 has a package for clang-8, so just do the switch.
https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/
=> Update clang-8 CI run to Ubuntu 20.04

plugins/nominations.sp, translations/nominations.phrases.txt
New English text is “Map ‘%s’ is not in the nominations pool.”
Split off from #588 due to the pending discussion on how i18n requests will work under the new setup.
=> Change the message displayed when a map isn’t in the nominations maplist

extensions/cstrike/natives.cpp, plugins/include/cstrike.inc
Some events, mainly the "dm_bonus_weapon_start" event, pass the loadout slot of the weapon that is now the bonus weapon, rather than an item index or a weapon id.
We are already creating a map of this in the cstrike extension, this native simply returns another member from that mapped value.
Let me know if I have missed anything, do I also need to update the .inc file in the tests folder?
=> CStrike Ext: Add native to retrieve loadout slot of weapon

core/HalfLife2.cpp, core/HalfLife2.h
Implements the `HasEntProp` optimization suggested by asherkin in the discord (caching missed lookups).
I tried to make any changes as non-disruptive as possible because I barely know what I'm doing, so it could probably be optimized further.
Testing shows it to be roughly 2-3x faster:
```
100 (* 6) iterations without fix:
[HasEntProp] Average Time:1.230063ms
[HasEntProp] Average Time:1.186231ms
[HasEntProp] Average Time:1.137192ms
Average = (3.553486ms / 3) = 1.18449533ms
100 (* 6) iterations with fix:
[HasEntProp] Average Time:0.383327ms
[HasEntProp] Average Time:0.375259ms
[HasEntProp] Average Time:0.443078ms
Average = (1.201664ms / 3) = 0.4005546ms
```
Using the following code, specifically `sm_hasentprop2` (which is probably not a good test):
The props used are either common, less …
=> Improve HasEntProp performance

extensions/dhooks/DynamicHooks/hook.cpp
Fix #1959 
Pretty much everything is explained in the related issue.
=> [DHooks] Fix `NaN` return when superceding pre-detour

plugins/include/sdktools.inc
This adds the information that if the return value is a string then SDKCall will return the number of bytes written. See [here](https://github.com/alliedmodders/sourcemod/blob/master/extensions/sdktools/vcaller.cpp#L507)
I'm not entirely sure if the description given is clear enough or if it may cause confusion.
I'm open for suggestions.
=> Update SDKCall return information

translations/lv/nominations.phrases.txt
Added missing translation + Can't Nominate Current Map translation was changed because The sentence in Latvian doesn't sound good + the chosen word wasn't the best option in this sentence.
=> missing translation added + fix

translations/lv/rockthevote.phrases.txt
I removed the word Aptauja since in this context it isn't the right word to use https://tezaurs.lv/aptauja:1 and changed it to this word https://tezaurs.lv/balso%C5%A1ana:1 
Example: I was asked  by a stranger on the street to participate in the "Aptaujā" 
Example 2: I went to the biggest shopping mall in Latvia to participate in the "Balsošānā", the year's best actor.
=> translations updated

translations/pt/adminhelp.phrases.txt, translations/pt/adminmenu.phrases.txt, translations/pt/antiflood.phrases.txt, translations/pt/basebans.phrases.txt, translations/pt/basecomm.phrases.txt, translations/pt/basetriggers.phrases.txt, translations/pt/basevotes.phrases.txt, translations/pt/clientprefs.phrases.txt, translations/pt/common.phrases.txt, translations/pt/core.phrases.txt, translations/pt/funcommands.phrases.txt, translations/pt/funvotes.phrases.txt, translations/pt/mapchooser.phrases.txt, translations/pt/nextmap.phrases.txt, translations/pt/nominations.phrases.txt, translations/pt/playercommands.phrases.txt, translations/pt/plugin.basecommands.txt, translations/pt/reservedslots.phrases.txt, translations/pt/rockthevote.phrases.txt, translations/pt/sounds.phrases.txt, translations/pt/sqladmins.phrases.txt
https://github.com/orgs/alliedmodders/projects/1/views/1?pane=issue&itemId=24307179
=> Update Brazilian Phrases

extensions/cstrike/rulesfix.cpp, gamedata/sm-cstrike.games/game.csgo.txt
Fixes #1814, supersedes #1815.
Implements the suggestion from https://github.com/alliedmodders/sourcemod/pull/1459#pullrequestreview-638382759, and increases the MTU to 65000 (what was used in the old plugin).
=> A2S_Rules fix: Move MTU patch value to gamedata

plugins/include/clientprefs.inc
Current implementation does not account for large negative numbers (`-2147483648`)
=> Fix Cookie.GetInt/SetInt buffer size

extensions/regex/CRegEx.cpp
subject is created with strdup which should be freed with C free and not C++ delete
=> Fix mismatched memory release in regex clearmatch

core/NextMap.cpp, plugins/nextmap.sp
This seems to work well, but it requires a change to the nextmap plugin as well as the implementation in core - which will be a pain for users as they almost never update the base plugins on upgrade. If the old plugin is used against a newer core version the `sm_nextmap` cvar will never get re-populated after map change, so SM will stop controlling the map cycle.
Fixes #1429
=> Clear sm_nextmap so we don't get stuck in a loop

gamedata/sm-tf2.games.txt
The 2023-07-26 Team Fortress 2 update changed the signature for `CTFPlayerShared::StunPlayer`. Found by @artvin01 and verified by me to be correct.
=> TF2: Update StunPlayer signature

plugins/include/tf2.inc
A new condition 130 was added with the 2023-07-26 Team Fortress 2 update. Internally named `TF_COND_IMMUNE_TO_PUSHBACK` and can be found via string search in the latest game binary. Used in `CTFBotMainAction::Update`.
=> TF2: Add TFCond_ImmuneToPushback condition

plugins/include/clients.inc, public/IPlayerHelpers.h
https://github.com/alliedmodders/sourcemod/pull/2025
=> [1.12] update maxplayers define for 07-25-23 tf2 update

extensions/sdktools/hooks.cpp, extensions/sdktools/hooks.h
This fixes https://github.com/alliedmodders/sourcemod/issues/2031
Tested on Debian 11 and works fine with and without replay enabled. I would like this fix to also be backported to 1.11 (stable) if possible.
Thanks.
=> Replay workaround fix

.github/dependabot.yml
Keep the actions we use up to date automatically. This avoids us having to worry about deprecation warnings of old action versions.
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
=> Update Github Actions using dependabot

AMBuildScript
Military Conflict: Vietnam recently dropped 32-bit Windows support in favor of 64-bit. Linux support was also added at some point (also 64-bit).
See also: https://github.com/alliedmodders/metamod-source/pull/115
=> Update MCV platform support

core/logic/smn_adt_stack.cpp, plugins/include/adt_stack.inc
ArrayStack can be useful at times, but the lack of functions makes it pretty limiting. This PR adds new natives for peeking at the top value of the stack without actually removing it, as well as a property to fetch the amount of elements in the stack.
Adds the following natives:
`ArrayStack.Top`
`ArrayStack.TopString`
`ArrayStack.TopArray`
And a property:
`ArrayStack.Length`
=> Add more functions to ArrayStack

plugins/include/sdktools_sound.inc
This fixes the values of sound flags since everything past SND_CHANGEPITCH was wrong. 
https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/public/soundflags.h#L115C18-L115C18
This also adds three other flags from SDK2013 which are SND_IGNORE_PHONEMES, SND_IGNORE_NAME, and SND_DO_NOT_OVERWRITE_EXISTING_ON_CHANNEL.
=> Fix sound flags enumeration

plugins/basebans.sp
If the admin types a chat trigger for a command while BaseBans is waiting for them to type a ban reason, don't treat that message as the ban reason.
This change fixes a problem where an admin decides to cancel their ban with `sm_abortban`, by invoking it via a chat trigger (`!abortban`, `/abortban`, etc), but ends up accidentally banning the player with the ban reason `!abortban` (or by attempting to access any other command via a chat trigger while the basebans chat listener was expecting to receive the ban reason).
Admin decides to cancel the ban, point of view:
It feels like substituting the "sm_command" with the "!command" chat trigger should work here. However:
The unfortunate player point of view (banned with reason "!abortban"):
You can attempt to ban yourself to test this …
=> Ignore chat triggers for interactive ban reason

translations/jp/playercommands.phrases.txt, translations/jp/plugin.basecommands.txt, translations/jp/rockthevote.phrases.txt
This fix is to revert most of #2042.
First of all, honorific expressions such as "禁止されました" are unnecessary in this case, and "蹴れました" is also a strange expression. Secondly, there is no need to replace "BAN" with "禁止" or "キック" with "蹴(れ)", for 99.9% of Japanese readers can understand "BAN" and "キック" as they are, because "BAN" and "キック" are already part of the Japanese language. (Citation: https://e-words.jp/w/BAN.html) Finally, the space between the name seems unnecessary unless it is wrapped in double quotation marks, which is also to make it consistent with other translations.
=> Fix Japanese translations

plugins/basetriggers.sp
Dystopia has a built-in command called nextmap which breaks due to the Sourcemod nextmap command. This modification is intended to restore Dystopia compatibility.
=> Update basetriggers.sp for Dystopia compatibility

gamedata/sdkhooks.games/game.dystopia.txt, gamedata/sdkhooks.games/master.games.txt
Fix #2070 
Add the offsets for `OnTakeDamage` and `OnTakeDamage_Alive` for the game Dystopia, for Linux and Windows platforms. This change adds game support for the `SDKHook_OnTakeDamage`, and its variants.
=> Update gamedata for Dystopia

public/smsdk_ext.cpp, public/smsdk_ext.h
`CreateInterface_MMS` was created 15 years ago. But `smsdk_ext.cpp` was never updated to have that change, and has continued to rely on the old function `CreateInterface` for 16 years.
On this aspect alone, I think this warrants an update.
However if this isn't enough to warrant the change. It should be noted that tier1 library the various SM extensions compile against, has its own definition of  `CreateInterface` which can clash with smsdkext's `CreateInterface` and cause linkage issues. So rather than cause headaches for sm extensions authors like myself lol, let's just axe this old function.
`METAMOD_PLUGIN *SDK_OnMetamodCreateInterface(const MetamodVersionInfo *mvi, const MetamodLoaderInfo *mli)`
Which exposes to the extension the two structs passed by metamod. As well as allowing …
=> Deprecate CreateInterface

plugins/include/functions.inc, plugins/include/menus.inc
`void` NativeCall prototype can be used for simple natives which don't return any value.
`void` MenuHandler can be used for basic menu handlers that don't return modified item styles and don't redraw menu items.
This is done to silence compiler warnings 209 (`function has explicit 'int' tag but does not return a value`) and 242 (`function "FuncName" should return an explicit value`).
=> Add void function prototypes to NativeCall and MenuHandler

gamedata/core.games/common.games.txt, gamedata/sdkhooks.games/game.pf2.txt, gamedata/sdkhooks.games/master.games.txt, gamedata/sdktools.games/game.pf2.txt, gamedata/sdktools.games/master.games.txt
- Updated `common.games.txt`
- Updated `master.games.txt`
- Added `sdkhooks.game/game.pf2.txt`
- Added `sdktools.games/game.pf2.txt`
We intend to implement Datatables in the same way as TF2C.
=> Add gamedata for Pre-Fortress 2

gamedata/sdktools.games/game.tf2classic.txt
In the sdktools tf2classic gamedata, the Linux offset for "CBaseEntity::Teleport" is off by 1, which causes teleports to not function properly (the `TeleportEntity()` function was seemingly doing nothing). Adjusting the value from "111" to the correct value of "110" fixes the issue.
Extra info:
- OS: Ubuntu Server 22.04.3 LTS
- Game: Team Fortress 2 Classic
- Metamod:Source Version: 1.11.0-dev+1153
- SourceMod Version: 1.11.0.6952
=> Fix teleportation offsets for tf2classic

tools/checkout-deps.ps1, tools/checkout-deps.sh
**Only tested on Windows (tools/checkout-deps.ps1).**
This just modifies both `tools/checkout-deps` files so that they both install the `alliedmodders/hl2sdk-mock` repository, so that SourceMod can compile successfully with AMBuild, considering the recent hl2sdk-manifests submodule addition.
This is from my (currently) extremely limited understanding of how SourceMod works internally (I just made a fork to modify a few things with the SourcePawn virtual machine out of plain interest), so if I misunderstood anything - apologies!
=> Update checkout-deps files to install hl2sdk-mock

gamedata/sdktools.games/engine.ep2valve.txt
Crash reported by @Malifox over discord, here's the updated gamedata. Once again a situation where the vtable size increase shifted everything, and ptr size increased.
Since this is the second time this happened, sorry about that, I've scanned other gamedata files for similar situation. And except for core's gamedata which was corrected, sdktools's gamedata should be the only other place we have gamedata offsets that aren't vtable offsets ? So hopefully this is the last time I've to make a PR like this.
=> Fix sdktools gamedata

gamedata/sdktools.games/game.neotokyo.txt
Add "SetOwnerEntity" gamedata for the game Neotokyo.
This adds game support for natives `SetOwnerEntity`, and `SetEntityCollisionGroup`.
=> Neotokyo: Add "SetOwnerEntity" gamedata

bridge/include/IFileSystemBridge.h, core/logic/smn_filesystem.cpp, core/logic_bridge.cpp, plugins/include/files.inc
Addresses https://github.com/alliedmodders/sourcemod/issues/1578
Use the engine's method for valve files, and a simple seek/tell for system files.
Test plugin:
```sourcepawn
#pragma semicolon 1
public Plugin myinfo =
{
name = "File Size Test",
author = "Peak",
description = "meow",
version = SOURCEMOD_VERSION,
url = "http://www.sourcemod.net/"
};
{
RegServerCmd("sm_fst", Command_FileSizeTest);
}
public Action Command_FileSizeTest(int args)
{
//Test existing
int existing = FileSize("addons/sourcemod/plugins/fsztest.smx");
int existingGame = FileSize("addons/sourcemod/plugins/fsztest.smx", true);
PrintToServer("Existing Native: %d, Existing Game: %d", existing, existingGame);
//Test native
File nf = …
```
=> Implement File.Size

core/smn_console.cpp
This fixes the issue with recursive `ServerCommandEx` in old engine (pre-Nuclear Dawn). The issue was that if `ServerCommandEx` is called recursively, `sm_conhook_start` and `sm_conhook_stop` will be added to the console buffer again. When that happens, it will set `g_OriginalSpewOutputFunc` to `SourcemodSpewOutputFunc` because the earlier call set the spew func to `SourcemodSpewOutputFunc`, and then when a line is printed, `SourcemodSpewOutputFunc` will call `SourcemodSpewOutputFunc` indefinitely until the stack overflows (in debug) or you get bored (in release). This patch fixes that by checking if we're already catching spew before adding `sm_conhook_start`/`stop` again.
=> Prevent recursion in sm_ServerCommandEx (fixes #967)

gamedata/sdktools.games/game.tf.txt, gamedata/sm-tf2.games.txt
This fixes the following x32 Windows signatures that were changed in the recent TF2 update:
- SetInWaitingForPlayers
- Regenerate
- SetPowerplayEnabled
- StunPlayer
- MakeBleed
- FireOutput
- CanPlayerTeleport
I've tested all of them and can confirm that the gamedata is correct and the functions work as intended.
=> x32 Windows Gamedata Fixes for 4/18/2024 TF2 Update

extensions/sdkhooks/extension.h
Fixes #2132 SDKHooks crashing after recent BlackMesa update.
Tested on Linux.
Thanks goes to futureunseen and Josh Hubi from Crowbar for tracking it down.
=> [BMS] Fix SDKHooks IEntityListener

core/PlayerManager.cpp
References https://github.com/alliedmodders/sourcemod/commit/8a10f4b7a20d4cff1268ea5130a01bf9b81ab854
References https://github.com/alliedmodders/sourcemod/commit/90ca9d7a47e053c06e48d0bc90afb58cc4ebd28b
This PR fixes `IsClientSourceTV` in L4D2 when a custom `tv_name` is used. Specifically a non `SourceTV` `tv_name` was incorrectly resulting in the bot not being considered the SourceTV bot.
The first commit makes this specific distinction for L4D2 - that the bot is spawned as `SourceTV` even if `tv_name` has a different value. The second commit makes L4D2 also compare the bot name with `tv_name` even though this is not applicable.
Credit for finding the cause of this issue goes to @asherkin . Tested with [SourceTV Support](https://github.com/shqke/sourcetvsupport) and …
=> Fix IsClientSourceTV in L4D2

extensions/bintools/jit_call_x64.cpp, extensions/sdktools/AMBuilder, extensions/sdktools/variant-t.cpp, extensions/sdktools/variant-t.h
Fixes AcceptEntityInput by using the struct definition instead of messy pointer math.
I could not add variant_t.cpp from the sdk because including cbase.h causes a large number of compile errors so I just pasted the 1 method into the sdktools file. If anyone wants to play around with making it work, you can uncomment the file include in the AMBuildScript file in the sdktools folder.
Includes a fix to bintools from malifox which is supposedly related, but I have no idea what it does to be honest.
https://github.com/alliedmodders/sourcemod/pull/2119
I only tested and confirmed this works on Linux and only on int and string variants.
=> AcceptEntityInput 64bit fix

extensions/bintools/jit_call_x64.cpp, extensions/sdktools/output.cpp, extensions/sdktools/outputnatives.cpp
This fixes `AcceptEntityInput`, `FireEntityOutput`, and entity output hooks to work on Windows 64-bit. This also fixes a crash associated with using the `TF2_DisguisePlayer` native.
This was tested on a TF2 Windows 64-bit server with a custom build of SourceMod built using [this version of the SDK](https://github.com/TF2-DMB/hl2sdk-tf2/pull/3) (though alliedmodders/hl2sdk#198 might work too). I didn't test on other games running on 64-bit at this time but hopefully should follow the same rules.
- **Compared to x86, passing a structure by value is no longer separated across the stack.** Instead, [if a structure is not of size 1, 2, 4, or 8, it will be passed by reference](https://learn.microsoft.com/en-us/cpp/build/x64-calling-convention?view=msvc-170#parameter-passing). The `FireOutput` …
=> Fix passing variant_t parameters + fix codegen stack on Win64

core/logic/smn_filesystem.cpp
`RenameFile` on linux uses `rename()` which will replace the destination file if it exists. `MoveFileA` doesn't replace so this is swapping it with `MoveFileExA`+`MOVEFILE_REPLACE_EXISTING` which will replace the destination.
=> make RenameFile() on Windows also replace the file

core/PlayerManager.cpp, plugins/include/clients.inc
Adds the OnServerHibernationUpdate forward. OnServerHibernationUpdate_Post() isn't possible to implement because there would be no place for it to be called from after SV_Frame stops executing.
Link to Discord discussion:
https://discord.com/channels/335290997317697536/335290997317697536/1236880595448233995
=> Add OnServerHibernationUpdate forward (closes #1483)

AMBuildScript
Requires alliedmodders/safetyhook#2 to land (hopefully), in which case we need to also update the submodule. This supplement your PR#2163 @Headline it's not meant to replace it. (I'm targetting your safetyhook-mirror branch)
=> Change the method of compiling safetyhook

core/logic/smn_filesystem.cpp
Issue mentioned to Asherkin or Psychonic.
Long story short, if a metamod plugin happens to be detouring some game functions that SM unfortunately calls while initialising, and decides to have the console print something. It will trigger `FileFileNatives::LogPrint`, however by that point `g_pLogHook` has not yet been initialised, it's still a nullptr. This of course ends up with a nullpointer crash.
Let's ~~add a member property that tracks whether or not we've been initialised.~~ nullcheck `g_pLogHook`
=> Fix rare crash with logs

extensions/sdktools/vdecoder.cpp
Corrects the check for the VDECODE_FLAG_ALLOWNOTINGAME flag
if you specify this flag, the check `player->IsInGame()` will run anyway if `player->IsConnected()` = true
=> fix VDECODE_FLAG_ALLOWNOTINGAME flag

core/HalfLife2.cpp, core/HalfLife2.h, core/smn_entities.cpp, extensions/cstrike/natives.cpp, extensions/sdkhooks/extension.cpp, extensions/sdkhooks/natives.cpp, extensions/sdktools/gamerulesnatives.cpp, extensions/sdktools/teamnatives.cpp, extensions/sdktools/vglobals.cpp, extensions/sdktools/vnatives.cpp, extensions/tf2/criticals.cpp, extensions/tf2/extension.cpp, public/IGameHelpers.h
This fixes #1902 and potential crash in other natives.
Well, the scope of this PR mainly boils down to
`CBaseEdict::GetNetworkable` & `IServerUnknown::GetNetworkable` (CBaseEntity::GetNetworkable)
The former, is the edict that gives a pointer (that might or might not be valid) of the attached entity's networkable
The latter, is the entity/unknown that gives a pointer (that is always valid) of the attached entity's networkable
The PR is mostly a speculative a fix for PR #1902 but everything points towards an unproperly setup Networkable's vtable. Which is strange, because Sourcemod retrives the networkable interface of any entity in a lot of places.
https://github.com/alliedmodders/sourcemod/search?q=GetNetworkable
But the key difference with all of them, and the gamerules native (as well …
=> Reconcile the concept of Edict & Networkable across the codebase

plugins/include/sorting.inc, plugins/testsuite/mock/test_sorting.sp
The error reported in https://github.com/alliedmodders/sourcemod/issues/2145 has been fixed in https://github.com/alliedmodders/sourcepawn/commit/9594f99766f9326f336a0307e1887e1317f18b48. 
This PR just updates the submodule to the latest remote commit ( I have not personally compiled & tested it ).
=> Update sourcepawn submodule

extensions/sdktools/hooks.cpp, extensions/sdktools/vhelpers.cpp
Found some more pointer arithmetic in sdktools assuming 32bits.
=> Fix more sdktools crash on 64 bits

plugins/include/tf2_stocks.inc
Latest sourcepawn submodule update brought in [#sourcepawn/938](https://github.com/alliedmodders/sourcepawn/pull/938), which now causes `TF2_SetPlayerClass` to throw a warning.
=> Fix unused parameter warning in TF2_SetPlayerClass

gamedata/sdkhooks.games/engine.ep2v.txt
GetMaxHealth in this file has the Windows 64 bit signature wrong using the Linux 32 bit/64 bit signature resulting in crashes.
=> Update gamedata engine.ep2v.txt for 64 bits

AMBuildScript, public/sample_ext/AMBuildScript, public/sample_ext/AMBuilder, public/sample_ext/PackageScript, public/sample_ext/configure.py, public/sample_ext_nosdk/AMBuildScript, public/sample_ext_nosdk/AMBuilder, public/sample_ext_nosdk/PackageScript, public/sample_ext_nosdk/configure.py
This PR aims to modernize the AMBuildScripts of the sample extensions. Bringing them closer to SM own AMBuildScript and adding support for compiling 64 bits extensions.
The build script is based on SM own build script. It was updated to use the HL2SDK manifests and allow compiling for multiple archs. Minimum AMBuild version increased to 2.2.
Two new arguments added to configure.py.
- --hl2sdk-manifest-path : Path to the HL2SDK manifests, this is optional if the manifests already exists in the project root. Otherwise a copy of the manifests is created on the project root folder.
- --targets : Overrides target build arch.
The build script was updated to allow compiling for multiple archs. Minimum AMBuild version increased to 2.2.
One new argument added to configure.py.
- --targets : …
=> Modernize Sample Extensions's AMBuildScript

extensions/tf2/teleporter.cpp, gamedata/sm-tf2.games.txt
- Changed signature call of `CanPlayerTeleport` for linux/linux64 to current used name
- Applied fix at detour class `CanPlayerBeTeleported` to use standard parameter proceedings for linux
Fixes issue #2140 
Fix tested on:
- Linux Mint 21.3, built in Ubuntu 20.04, working properly
- Windows 10, working properly
=> - Fixes for OnPlayerTeleport hook for linux and linux64 systems

extensions/sqlite/sqlite-source/sqlite3.h
Supersedes #2191
Updates the SQLite library used in the bundled SQLite extension from 3.38.5 to 3.47.0
https://www.sqlite.org/changes.html
=> Update SQLite to 3.47.0

extensions/geoip/data-pool.c, extensions/geoip/data-pool.h, extensions/geoip/maxminddb-compat-util.h, extensions/geoip/maxminddb.c, extensions/geoip/maxminddb.h, extensions/geoip/maxminddb_config.h, extensions/mysql/AMBuilder, tools/checkout-deps.sh
Suggestion to use MySQL 5.7 as default for `checkout-deps.sh` on Linux. Will be useful after merging this PR: https://github.com/alliedmodders/sourcemod/pull/2189
In addition, an update to the libmaxminddb library.
=> Update libmaxminddb and MySQL 5.7

gamedata/sdkhooks.games/engine.ep2v.txt, gamedata/sdktools.games/game.hl2mp.txt
This PR updates the gamedata files of SDKTools and SDKHooks for Half-Life 2 Deathmatch.
Offsets obtained via Asherkin's vtable dumper using the Linux binary from the beta branch of the dedicated server.
I'm also removing the gamedata for mac since Sourcemod no longer supports it.
=> Update Half-Life 2: Deathmatch Gamedata

gamedata/sdktools.games/game.hl2mp.txt
Tested working on latest HL2:DM Linux DS using SM 1.12.0.7169 via the following test code:
```
#include <sdktools>
Handle Call_CommitSuicide;
{
RegConsoleCmd("sm_suicide", Command_Suicide);
StartPrepSDKCall(SDKCall_Player);
PrepSDKCall_SetVirtual(446);
PrepSDKCall_AddParameter(SDKType_Bool, SDKPass_Plain);
PrepSDKCall_AddParameter(SDKType_Bool, SDKPass_Plain);
Call_CommitSuicide = EndPrepSDKCall();
if(Call_CommitSuicide == INVALID_HANDLE)
{
SetFailState("Failed to setup CommitSuicide call");
}
}
public Action Command_Suicide(int client, int args)
{
if(IsClientInGame(client))
{
SDKCall(Call_CommitSuicide, client, false, false);
}
return Plugin_Handled;
}
```
=> Fix incorrect offset for CommitSuicide

extensions/tf2/teleporter.cpp, gamedata/sm-tf2.games.txt
Merge #2214 failed due to pointer misalignment which was fixed in safetyhook and a [revision commit](https://github.com/alliedmodders/sourcemod/commit/4004471d8dde9ae3523cc61cb98b954dee545a41) was made, making the process of hooking work normally again.
Tests were made on Linux with bare MM+SM installations, MM+SM+many dummy plugins using different hooks and both mock and production servers , and no recurring crashes were reported.
Tests were also made on Windows, both with MM+SM installations and MM+SM+dummy hook plugins.
Pull request fixes issue #2140.
=> Fixes for OnPlayerTeleport hook for linux and linux64 systems

extensions/tf2/teleporter.cpp, gamedata/sm-tf2.games.txt
Followup of Pull Request #2234, I made a mistake and forgot to make Sourcemod start using the new registry for the teleportation check.
Already tested and it's working flawlessly.
Sorry :grimacing: This is the last pull request for the current issue, I swear.
=> Correction for sourcemod use the new teleportation check gamedata registry from now on.

gamedata/core.games/common.games.txt
Radio menus such as those created with `sm_vote` don't show up in the game, but the game seems to support them once the keys in `common.games.txt` are updated. Similarly HUD messages seem to work fine in maps with the `game_text` entity.
=> Add support for radio menu and HUD message for Dystopia

.github/workflows/ci.yml, AMBuildScript, extensions/mysql/AMBuilder, tools/checkout-deps.sh
Dynamically link the CRT for the MySQL extension to be able to use libmysqlclient builds past the 5.5.54 release. This requires the [VC runtime](https://www.microsoft.com/en-us/download/details.aspx?id=48145) to be installed now while we previously linked them statically.
This allows to use the new `caching_sha2_password` default password encryption scheme from MySQL 8+ from Windows SRCDS too.
The build slaves need updating too if we want this.
Fixes #2231
```
dumpbin /dependents dbi.mysql.ext.dll
Microsoft (R) COFF/PE Dumper Version 14.37.32824.0
Copyright (C) Microsoft Corporation.  All rights reserved.
Dump of file dbi.mysql.ext.dll
File Type: DLL
Image has the following dependencies:
WSOCK32.dll
Secur32.dll
WS2_32.dll
KERNEL32.dll
ADVAPI32.dll
Summary
2BB000 .data
1D000 .rdata
7000 …
```
=> Bump MySQL to 5.7.44 on Windows too

configs/core.cfg, core/sourcemod.cpp
Allow extensions to register a debug break handler in the SourcePawn VM using `smutils->GetScriptingEngine()->SetDebugBreakHandler(callback)`.
Enable line debugging support in the VM before any plugin is loaded through a core.cfg option. This is required for potential debuggers to work.
=> Add "EnableLineDebugging" core.cfg option

bridge/include/CoreProvider.h, core/logic_bridge.cpp, core/provider.h
=> fix: Allow entity references for clients with L and N format specifiers

AMBuildScript
AMTL was made for c++14 and we're using 17 on sm - we'll have to compile with this flag until amtl replaces std::bind. AMTL is currently in-between versions at the moment
=> Add -Wno-deprecated-declarations

core/logic/sprintf.cpp
Fix #2221
When left-aligned and a `minimum width` is specified, if the `minimum width` is set to less than the number of characters required by the parameter, the output buffer will be filled with `Pads`.
=> Fix formatting error

extensions/dhooks/DynamicHooks/hook.cpp
PR #2205 introduced a regression on detours for unconventional calling functions.
This does not help (I've to avoid saying 'close') #2212 as it's a different issue, however it's in that same thread that the present regression was reported. Thanks to @jensewe for spotting the issue, and thanks to @FortyTwoFortyTwo for case-testing this.
=> Fix dhooks regression

core/HalfLife2.cpp
Affects `GetClientAuthId`, `BanClient`, `BanIdentity`, `RemoveBan`, generally any time an Auth ID is being validated.
This PR simply makes getting the "sv_lan" ConVar a 1 time static operation. Prior behavior could call FindVar() for every call of the affected functions. psychonic mentioned possibly using `ConVarRef` instead of `ConVar*`, but that it may not be available for ep1. That does indeed seem to be the case from my quick look through.
For those that enjoy seeing performance numbers, I'll summarize a couple of discord posts of using `GetClientAuthId()` and `GetClientName()` to compare profiled times at 1,000 loops on aging server hardware(Intel Xeon Gold 6242R).
Before:
```
GetClientName: 0.0219999998 ms, avg: 0.0000220000 ms
AuthId_Steam2: 40.1949996948 ms, avg: 0.0401949994 ms …
```
=> Significantly improve performance of functions that check IsLANServer()

core/HalfLife2.cpp, core/HalfLife2.h, core/logic_bridge.cpp
=> Fix regression in DescribePlayer (%N / %L) for players not yet having entities

extensions/cstrike/util_cstrike.cpp, extensions/sdktools/gamerulesnatives.cpp, extensions/sdktools/teamnatives.cpp, extensions/sdktools/variant-t.cpp
As of #2253 plugins/extensions might reload sdktools gamedata, which turns all the strings globally stored into garbage.
For example :
https://github.com/alliedmodders/sourcemod/blob/f6737a4760e4bd6226f327f0e08ec5d8c7f6a4e4/extensions/sdktools/gamerulesnatives.cpp#L40
I've scoured the codebase for the usage of `GetKeyValue` and implemented a string copy of the returned value if it happens to be stored into a global variable. Verdict is that only sdktools and cstrike extension seem affected, hopefully that's all the instances of this issue.
Also closes #2193
=> Fix storing garbage strings

.github/workflows/ci.yml, AMBuildScript, core/HalfLife2.cpp, core/logic/GameConfigs.cpp, core/logic/MemoryUtils.cpp, core/logic/PseudoAddrManager.cpp, core/logic/common_logic.cpp, core/logic/common_logic.h, core/logic/smn_core.cpp, core/logic/smn_gameconfigs.cpp, core/smn_entities.cpp, core/sourcemod.cpp, extensions/bintools/CallMaker.cpp, extensions/cstrike/itemdef-hash.h, extensions/dhooks/DynamicHooks/registers.cpp, extensions/dhooks/util.cpp, extensions/dhooks/vhook.cpp, extensions/dhooks/vhook.h, extensions/sdkhooks/takedamageinfohack.cpp, extensions/sdktools/hooks.cpp, extensions/sdktools/output.cpp, extensions/sdktools/outputnatives.cpp, extensions/sdktools/tempents.cpp, extensions/sdktools/vcaller.cpp, extensions/sdktools/vglobals.cpp, public/sm_platform.h
Same as alliedmodders/hl2sdk-manifests#9
Special note, the define `PLATFORM_X86` is now used by valve to refer to both x86 and x86_64. It holds either 32 or 64 value.
So instead of potentially conflicting with whatever valve decides to do with its preprocessor variable, let's just make sure our variable well distinct.
=> Tentative compilation fix for css + tf2

plugins/admin-sql-threaded.sp
Related to [#2148](https://github.com/alliedmodders/sourcemod/issues/2148):
* Added columns from the SELECT clause that were missing from the GROUP BY clause on line 529 that was causing the query to fail.
* Increased query buffer size on line 513 from 512 to 544 to accommodate the extra characters needed.
=> Fixed missing columns in GROUP BY statement in admin-sql-threaded

gamedata/sm-tf2.games.txt
https://crash.limetech.org/gvjiwehomlvu
`RemoveDisguise` still have crash issue after #2273. I have already tested this and confirmed that there are no issues.
=> RemoveDisguise GameData fix

gamedata/sm-cstrike.games/game.css.txt
And with this, this should be all the gamedata for CSS updated
One thing to note, `SetModelFromClass` got inlined on windows and I don't think there's any sane way of fixing it. So I'm purposefully leaving the native broken by removing the signature rather than risking matching random invalid subroutines, it will continue to function as normal on linux.
=> Fix cstrike ext gamedata for css

gamedata/sdkhooks.games/game.pvkii.txt
Fix EntityListeners for SDKHooks and SDKTools Gamedata for PVKII (Increased edict limit to 8,192 since 0.5.1.2)
It fix https://github.com/alliedmodders/sourcemod/issues/2200
=> Fix EntityListeners for SDKHooks and SDKTools Gamedata for PVKII

extensions/dhooks/DynamicHooks/hook.cpp
(I was using [this](https://github.com/xen-000/SuppressViewpunch/pull/2) to test the crash)
=> Fix a Windows64 crash when unloading a plugin that DHooked something

gamedata/sm-cstrike.games/game.css.txt
Looked signatures for cs:s 64bit windows, made little change in gamedata file structure as well.
Maybe fix issue #2287
sorry for github hassle
=> Fix cstrike ext gamedata for css 64bit #2287

gamedata/sdkhooks.games/engine.ep2v.txt
According this forum post
https://forums.alliedmods.net/showpost.php?p=2835080&postcount=2
...and I encounter in same problem while doing plugin for DOD:S game, SDKHooks "Touch" did not work.
And seems hl2mp and cstrike have very same offsets in "EndTouch" "StartTouch" so this should be correct for "Touch".
- I have tested on Windows, srcds.exe and srcds_win64.exe
=> Update engine.ep2v.txt - DOD:S Touch offset

gamedata/sdkhooks.games/engine.ep2v.txt
Updates the SDKHook's `SetTransmit` for HL2:DM.
Fixes #2303
=> Fix Incorrect SetTransmit Offset for HL2DM

core/logic/DebugReporter.cpp, core/logic/smn_core.cpp, core/smn_entities.cpp, extensions/clientprefs/cookie.cpp, extensions/clientprefs/menus.cpp, extensions/clientprefs/natives.cpp, extensions/sdktools/vcaller.cpp
Fix for #2305 
On at least linux-x64, our usage of `%x` for formatting a ClientPrefs menu data pointer to string was leading to a truncated pointer being included. This fixes that, the same issue in some less impactful places, and tidies up a couple of other warnings in ClientPrefs.
=> Fix ClientPrefs pointer string formatting

core/HalfLife2.cpp
This PR fixes a crash caused by passing a bad reference value to `CHalfLife2::ReferenceToIndex`.
Example crash: https://crash.limetech.org/xyv66kz6dkvd
```
#pragma semicolon 1
const int ENTREF_MASK = (1 << 31);
public void OnMapStart()
{
int ref = 9000 | ENTREF_MASK;
int index = EntRefToEntIndex(ref);
PrintToServer("%i", index);
}
```
=> Fix NULL Crash on ReferenceToIndex

gamedata/core.games/common.games.txt
The various radio menus are broken in Day of Infamy on current sourcemod versions due to the same engine issue being present as is in csgo/insurgency.
=> Limit RadioMenuMaxPageItems for doi as well

extensions/tf2/holiday.cpp, gamedata/sm-tf2.games.txt, plugins/include/tf2.inc
Valve has updated this holiday this year to use 2025 dates (2025-07-16 to 2025-09-16) so semi-relevant to add
https://github.com/SteamDatabase/GameTracking-TF2/commit/53251b5cdf6e051b34e42211d87a4670e10ce1b5#diff-ec0ad6965eb1aa76e7d13d323684e84757d3eaf714b05e24fffb5c9c55bb3215L5376
2024 dates at https://github.com/ValveSoftware/source-sdk-2013/blob/68c8b82fdcb41b8ad5abde9fe1f0654254217b8e/src/game/shared/econ/econ_holidays.cpp#L334
Evidence from https://github.com/SteamDatabase/GameTracking-TF2/blob/786fe2cb84b0fe335e46465cc369ef32124584f5/tf/bin/server_strings.txt indicates that the same dates as 2024 were used in 2023 when this event was first made.
=> Add TFHoliday_Summer

extensions/sdktools/variant-t.cpp
from AM discord:
https://discord.com/channels/335290997317697536/335290997317697536/1422743151851995277
> I have an issue with SetVariantString because I'm trying to call the vscript function TakeDamageEx with a formatted string that's over 128 bytes, but I can't because the buffer that's used for it is 128 bytes. Is it necessary to limit the size to be that small? Could it be raised? The SetString function takes a string_t so I don't think it needs to be this small. I need to call EntIndexToHScript a bunch, which is the reason I'm going over the 128 limit.
=> Incrase SetVariantString string limit
