plugins/include/menus.inc

Credit to "Peace_Maker" for finding out.

Add missing semicolon.

---

core/logic/smn_adt_stack.cpp

Looks like this was just a typo.

Fix signed/unsigned compare warning in smn_adt_stack.

---

extensions/sdkhooks/extension.cpp

This ever being allowed seems like an oversight.

Don't allow plugins to block LevelInit (wtf).

---

core/sm_srvcmds.cpp

Make handle dump location relative to gamedir to match other sm_dump commands.

---

extensions/sdktools/vsound.cpp
plugins/include/sdktools_sound.inc

This is my first pull request in a while, hopefully I did it correctly.
Please see the following for notes: https://bugs.alliedmods.net/show_bug.cgi?id=6297

Improvements for NormalSHook functionality

---

sourcepawn/jit/engine2.cpp
sourcepawn/jit/engine2.h
sourcepawn/jit/sp_vm_basecontext.cpp
sourcepawn/jit/sp_vm_basecontext.h
sourcepawn/jit/sp_vm_engine.cpp
sourcepawn/jit/sp_vm_engine.h
sourcepawn/jit/sp_vm_function.cpp
sourcepawn/jit/sp_vm_function.h

Just make old code conform to the new local style (two-space indents and compact bracing).

Modernize sourcepawn/jit style.

---

sourcepawn/jit/AMBuilder
sourcepawn/jit/dll_exports.cpp

Build the debug spshell as part of AMBuild.

---

sourcepawn/compiler/AMBuilder
sourcepawn/compiler/sc.h
sourcepawn/compiler/sc2.cpp
sourcepawn/compiler/sc3.cpp
sourcepawn/compiler/sc4.cpp
sourcepawn/compiler/sc5-in.scp
sourcepawn/compiler/sc5.cpp
sourcepawn/compiler/sc6.cpp
sourcepawn/compiler/sc7-in.scp
sourcepawn/compiler/sc7.cpp
sourcepawn/compiler/scexpand.cpp
sourcepawn/compiler/sclist.cpp
sourcepawn/include/smx/smx-v1-opcodes.h
sourcepawn/jit/file-utils.cpp
sourcepawn/jit/stack-frames.cpp
sourcepawn/jit/stack-frames.h

My testing involved starting a server and diffing the assembly for mapchooser!

Signed comparison warning fixes.

---

sourcepawn/compiler/sc1.cpp

See https://bugs.alliedmods.net/show_bug.cgi?id=3729 and https://bugs.alliedmods.net/show_bug.cgi?id=6307.

Reapply ancient patch to allow spaces in spcomp options.

---

plugins/include/sdktools_tempents.inc

Add helper stock to mimic PVS and PAS recipient filters for tempents in
the SDK.

Add TE_SendToAllInRange

---

plugins/include/adminmenu.inc
plugins/include/basecomm.inc
plugins/include/clientprefs.inc
plugins/include/tf2.inc

I believe that this is all of the remaining ones.
@dvander

Add explicit return types to forwards missing them.

---

plugins/include/regex.inc

Makes compiler happy with regex.inc now

Fixed regex.inc

---

plugins/admin-sql-threaded.sp
plugins/basebans/ban.sp
plugins/basevotes/votemap.sp
plugins/funcommands/beacon.sp
plugins/funcommands/blind.sp
plugins/funcommands/drug.sp
plugins/funcommands/fire.sp
plugins/funcommands/gravity.sp
plugins/funcommands/ice.sp
plugins/funcommands/noclip.sp
plugins/funcommands/timebomb.sp
plugins/funvotes.sp
plugins/include/helpers.inc
plugins/nextmap.sp
plugins/nominations.sp
plugins/playercommands/slap.sp
plugins/playercommands/slay.sp
plugins/rockthevote.sp

Fix some buffer sizes in shipped plugins

---

extensions/sdktools/vhelpers.cpp

Date stamp tweaks in dump commands.

Dumps datestamps

---

core/smn_entities.cpp

Fix bIsStringIndex not being initialized in SetEntPropString for non-index SendProps.

---

gamedata/sm-tf2.games.txt

For an update that may or may not ever happen.
@VoiDeD @psychonic

Update TF2 gamedata

---

core/MenuStyle_Base.h
core/logic/ProfileTools.h
core/logic/smn_adt_trie.cpp
core/logic/smn_filesystem.cpp
core/vprof_tool.h

Drops GCC 4.6 and MSVC 2012 support.

Update to the latest AMTL version.

---

core/logic/DebugReporter.cpp
core/logic/ExtensionSys.cpp
core/logic/GameConfigs.cpp
core/logic/HandleSys.cpp
core/logic/Logger.cpp
core/logic/PhraseCollection.cpp
core/logic/PluginSys.cpp
core/logic/ProfileTools.cpp
core/logic/TextParsers.cpp
core/logic/Translator.cpp
core/logic/intercom.h
core/logic/smn_banning.cpp
core/logic/smn_lang.cpp
core/logic/smn_string.cpp
core/logic_bridge.cpp
core/sm_stringutil.cpp

This is in AMTL now so there's no point to pass it around via internal API.

Remove Format/FormatArgs from the core/logic bridge.

---

core/smn_entities.cpp

For [bug 6409](https://bugs.alliedmods.net/show_bug.cgi?id=6409)
See commit notes.

Fix quirks with Get/SetEntPropString on string_t arrays in datadesc

---

core/sourcemm_api.cpp

This fixes some quirks from PR #398 being done a bit too haphazardly.

Shim for TF2-branch games to find latest, non-shimmed engine iface. 2

---

tools/buildbot/package.pl

If we're to eventually change to a rolling release model, one of the first steps is to start having translations and updated GeoIP data included in our automatic builds. This addes that.
It's added at the BuildBot packaging step (after AMBuild has finished) both because it was easier, and to not affect time that manual builds take.
One thing that is not accounted for is versioning of translations. That will require further editing of the translator site and can be done at a later time since it won't currently cause an issue. (The only edit done to the site for this was adding the language id to the comment after each line in languages.cfg).

Add translation files and updated GeoIP data to snapshots (bug 5728)

---

extensions/sdktools/extension.cpp
extensions/sdktools/extension.h
extensions/sdktools/hooks.cpp
extensions/sdktools/hooks.h
plugins/include/sdktools_hooks.inc

I've ported this from a pretty dated bug on BZ, not even sure if it still builds...

Add File Transfer hooks to SDKTools.

---

core/smn_halflife.cpp
plugins/include/halflife.inc

https://github.com/alliedmodders/sourcemod/pull/396

Change FindMap to take a const char* for searching instead of char*.

---

tools/gdc-psyfork/Makefile
tools/gdc-psyfork/gdc.cpp

This fixes the makefile to work with  central (and the split of sourcepawn) I also added a bit more info to the printing of byte checks.

Fix Makefile, and add info for byte checks.

---

gamedata/sdkhooks.games/engine.ep2v.txt
gamedata/sdkhooks.games/game.cstrike.txt
gamedata/sdktools.games/game.cstrike.txt
gamedata/sdktools.games/game.dod.txt
gamedata/sdktools.games/game.hl2mp.txt

Updated gamedata for CS:S, DoD:S, and HL2:DM.

---

plugins/include/tf2.inc

Invasion/Passtime/Mannpower conds

Update TFCond enum

---

tools/buildbot/package.pl

This gives something for people scripting to look at rather than scraping our download pages. It will also make it easier for us to implement a static link that always gets the latest version of a branch.

Upload sourcemod-latest-<os> text file when packaging.

---

core/logic/DebugReporter.cpp
extensions/sdkhooks/extension.cpp
extensions/sdktools/vsound.cpp

I didn't find anywhere else that should use BPE instead of TNE, but maybe I missed them.

Update SP and use BlamePluginError in sdkhooks.

---

tools/ida_scripts/vtable_dump.py

This should fix the vtable dump script to work with dota's x64 bins.

Add x64 support to IDA vtable dump script

---

tools/ida_scripts/vtable_dump.py

A small fix to work with multiple versions of IDA x86 & x64

Update IDA vtable dump script

---

extensions/sdktools/output.cpp
extensions/sdktools/output.h
plugins/include/sdktools_entoutput.inc

https://bugs.alliedmods.net/show_bug.cgi?id=5515
It seems like this bug/patch has been forgotten, so I opened a pull request.
This is just Peace-Maker patch, where I updated the changes in the include file to the new syntax.
Kristian

Allow plugins to suppress entity outputs (fix 5515).

---

public/sample_ext/AMBuildScript

Basically, I've taken the recent changes to the AMBuildScript for SourceMod and applied them to the sample_ext AMBuildScript.
While I haven't tested everything completely on a complicated project, the sample_ext project builds just fine with it against all current SDKs available on Windows and Linux.

Update sample_ext's AMBuildScript

---

public/sample_ext/Makefile

I needed to do these changes in order to compile the sample extension.

Fix compilation of sample extension

---

extensions/sdktools/hooks.cpp

This works around a TF Replay SourceHook crash that Johns was seeing when using 1.8.
SourceHook is not thread-safe at the time of this writing.
As TF is the only game that has fully implemented replay (the changes from the CS:S beta branch (appid 260) were thrown away during the Steam| conversion, other games never had the feature), this should minimize the footprint significantly.

Only hook IBaseFileSystem::FileExists if we're also hooking INetChannel

---

extensions/sdktools/extension.cpp
extensions/sdktools/hooks.cpp
extensions/sdktools/hooks.h

It will crash. See PR #493 for details.
@KyleSanderson

Don't enable FileExists hook (SendFile forward) on TF2 servers with Replay

---

core/logic/smn_float.cpp

See alliedmodders/sourcepawn#66.

Remove half-up rounding.

---

plugins/include/banning.inc

Typo in OnRemoveBan documentation

Typo in OnRemoveBan documentation

---

core/PlayerManager.cpp

Steam supports player names up to 32 UTF-8 characters, excluding the NULL terminator. The Source Engine supports either 32 or 128 bytes for a name (depending on version), including the NULL terminator.
In all cases, this can lead to the engine copy of the name ending in the middle of a character due to the truncation. When this occurs, rather than passing this copy of the name to the GetClientName native and the %N format specifier, let's fix our stored copy.

Strip invalid UTF-8 char from end of player names.

---

core/PlayerManager.cpp

Completely speculative CS:GO fix, 50/50, 60/40.
Using Travis to check for breakage.

GetPlayerNetworkIDString isn't alone anymore, we have friends.

---

plugins/basevotes.sp

Basevotes convars are missing from sourcemod.cfg and there is no config file for this plugin, so I added AutoExecConfig.

Updated basevotes

---

plugins/funvotes.sp

Funvotes convars are missing from sourcemod.cfg and there is no config file for this plugin, so I added AutoExecConfig.

Updated funvotes

---

plugins/include/string.inc

Fixed description for CharToLower and CharToUpper

---

extensions/sqlite/AMBuilder
extensions/sqlite/driver/SqDriver.cpp

As requested here, https://forums.alliedmods.net/showthread.php?t=265261
Tested with:
```
public OnPluginStart()
{
RegServerCmd("sqlite_memtest", sqlite_memtest);
}
public Action sqlite_memtest(int argc)
{
char error[1024];
Database hi = SQLite_UseDatabase(":memory:", error, sizeof(error));  
if (hi == INVALID_HANDLE)
{
PrintToServer("Failed: %s", error);
}
else
{
PrintToServer("Success!");
}
return Plugin_Handled;
}
```

Add support for more SQLite database open options.

---

plugins/basechat.sp

Replaced with the fixed methodmap!
Thanks psychonic.

Use methodmap .Style instead of GetMaxPageItems. (sm_msay patch)

---

AMBuildScript
core/ConsoleDetours.cpp
core/CoreConfig.cpp
core/NextMap.cpp
core/PlayerManager.cpp
core/logic_bridge.cpp
core/smn_halflife.cpp
core/sourcemm_api.cpp
core/sourcemm_api.h
extensions/sdkhooks/extension.h
extensions/sdktools/extension.cpp
loader/loader.cpp

These are the only engine versions that are using the legacy MM:S API. Now all use the same.
See also: https://github.com/alliedmodders/metamod-source/pull/29

Use newer MM:S api for Ep1/Original engine.

---

tools/gdc-psyfork/gdc.cpp

Copy & Pasted from @peace-maker

Fix GDC's Linux sigscanning

---

core/HalfLife2.cpp
extensions/sdktools/extension.cpp
extensions/sdktools/extension.h
extensions/sdktools/gamerulesnatives.cpp

This fixes #504 
This PR will close if AND when https://github.com/Bara20/sourcemod/pull/2 is merged

Add 2 CSGO gamerules netprops to CSGO blocklist if FollowCSGOServerGuidelines is enabled.

---

plugins/rockthevote.sp

The reason of update is described here https://forums.alliedmods.net/showthread.php?p=2499471

rockthevote.sp - RoundToFloor() -> RoundToCeil()

---

gamedata/core.games/common.games.txt

https://forums.alliedmods.net/showthread.php?t=295215

HUD is now supported on CSGO

---

plugins/include/console.inc

We have PrintToChatAll, PrintToCenterAll, but not a PrintToConsoleAll. Might as well be consistent...

Add PrintToConsoleAll

---

extensions/sdktools/hooks.cpp
extensions/sdktools/hooks.h
plugins/include/sdktools_hooks.inc

Allow plugins to catch the values that are actually used by the game
after some eventual changes by other plugins.
This is useful for a plugin like BotMimic 👍

Add OnPlayerRunCmdPost forward

---

plugins/basechat.sp

Correct setting of the exit button depending on the game

Fix sm_msay (Correct setting of the exit button depending on the game)

---

core/smn_halflife.cpp
plugins/include/halflife.inc

my first pr be nice pelipoika requested it

add native to get gpGlobals->frametime

---

extensions/sdkhooks/extension.cpp
extensions/sdkhooks/extension.h

Cache created entities by reference instead of index in SDKHooks

---

AMBuildScript

Update to latest SourcePawn

---

translations/nominations.phrases.txt

I honestly didn't mind it at all, but a bunch of butt-hurt girl gamers kept complaining in my servers as if I'm the one responsible for it.

Removed gender from nominations.phrases.txt

---

gamedata/sdkhooks.games/engine.csgo.txt

I've just tested some of them.
- Weapon_Drop
- Reload
I'm testing Weapon_CanUse in few minutes

Fix some CS:GO gamedata

---

core/sourcemm_api.cpp

Remove replicated flag from sourcemod_version

Remove replicated flag from sourcemod_version

---

plugins/basevotes.sp
plugins/funvotes.sp
plugins/mapchooser.sp

Remove excess assignment to null after delete

---

plugins/basevotes.sp
plugins/basevotes/voteban.sp
plugins/basevotes/votekick.sp
plugins/funvotes.sp
plugins/funvotes/voteburn.sp
plugins/funvotes/voteslay.sp

Checks the target userid at the end of the vote and ignores the actions if userid is invalid instead of throwing exceptions.
Fixes #641.

[basevotes / funvotes] Ignore vote actions if target is no longer available

---

core/logic/CDataPack.cpp

Pretty sure the code here was just wrong, see https://forums.alliedmods.net/showthread.php?t=301390.

Allow seeking to end of datapack

---

extensions/sdktools/hooks.cpp

Issue reported by Peace-Maker in issue #645.

Fix OnPlayerRunCmd crashing with invalid CUserCmd ptr (Issue #645).

---

core/logic/AMBuilder
core/logic/FrameIterator.cpp
core/logic/FrameIterator.h
core/logic/smn_core.cpp
plugins/include/sourcemod.inc

I decided to redact these changes from the LogStackTrace pull request since these are unrelated.
If we decide to add a stack frame iterator for sourcemod plugins, this is what that implementation would look like. Comments & criticisms are welcome.

Create FrameIterator type

---

core/HalfLife2.cpp
core/smn_halflife.cpp

This should fix some issues windows users may experience should a reserved windows device name sneaks up

Block reserved device names on windows

---

plugins/include/usermessages.inc

If anything here is wrong let me know
Thanks to Kruzya for bringing this up in the sm discord

Add forgotten `const` to parameters

---

plugins/nominations.sp

@Powerlord noticed that.
https://forums.alliedmods.net/showthread.php?t=304715

Fix description of nominations convars

---

core/AMBuilder

All we needed to do was bump the version, no changes were required.
This fixes #761

Use msvc 2015 lib with 2017 (#764)

---

AMBuildScript
tools/checkout-deps.sh

@peace-maker Your wildest dream come true.

Use MySQL 5.5 for MySQL extension.

---

plugins/include/sdktools_sound.inc

The folder is actually "sound" and not "sounds"

"sound" folder instead "sounds"

---

.github/CONTRIBUTING.md

Fixed some grammar and word choice issues. I have to write a lot of prose like this for my MvM contests and campaigns, so I gave this a good proofread, since I noticed some issues when reading it before making my first pull request.
That said, please do look over it and see if I missed any issues or (worse) introduced a mistake myself. Let me know if any changes need to be made or reverted.
Thanks.

Fix English Style

---

plugins/include/files.inc

For reference the implementation is here: https://github.com/alliedmodders/sourcemod/blob/master/core/logic/smn_filesystem.cpp#L725
Let me know if I should change the comment or something else. Thanks.

Add CreateDirectory return value documentation

---

plugins/include/files.inc

Not sure how long this has existed for, but seems like something I'd write.
🍻

Fix grammar error in File docs

---

plugins/admin-sql-threaded.sp
plugins/adminmenu/dynamicmenu.sp
plugins/antiflood.sp
plugins/basebans.sp
plugins/basebans/ban.sp
plugins/basecomm.sp
plugins/basecomm/gag.sp
plugins/basecomm/natives.sp

This brings in enum struct support.

Inauguration of SourcePawn enum structs

---

plugins/include/tf2_stocks.inc

Adds in `TF_CUSTOM_AXTINGUISHER_BOOSTED`, [seen here in the binary](https://cdn.discordapp.com/attachments/335291251937116167/558420271426699264/unknown.png).

Add new custom kill identifier

---

extensions/cstrike/forwards.cpp
extensions/cstrike/natives.cpp

Updated in 4/30/2019 csgo update

Remove unneeded paramter in CS_DropWeapon 1.10

---

plugins/include/adt_array.inc

Modified indention for uniformity

Fixed indent

---

extensions/cstrike/natives.cpp
extensions/sdktools/outputnatives.cpp
extensions/tf2/natives.cpp

Just some little observations, I will look up for more in other files whenever I can

PassType typo fixup

---

licenses/LICENSE.txt

Removed outdated License Info

---

licenses/LICENSE.txt

Fix quote mismatch

---

AMBuildScript

This turns on the new expression parser by default.

Update SourcePawn to master.

---

plugins/include/dbi.inc

Fixes #1033 
Must've been left out

Return `Driver` instead of `Handle` to for newdecl

---

plugins/include/cstrike.inc

I'm still not sure about the name "Util", but it's a more general name  (Valve call this "boost" in his "items_game.txt") and we don't know if valve adds more items/weapons to this slot.
Let me know, if anyone has other suggestions about this name.

Add slot define for healthshot/shield and tablet

---

plugins/include/halflife.inc
plugins/include/sdktools_tempents.inc

- TE_SendToAllInRange()
- GetClientsInRange()

Fix some arguments missing "const" keyword in the includes

---

plugins/include/datapack.inc

Also fixup a couple descriptions in the methodmap

Fix documentation on DataPack methods

---

gamedata/sdkhooks.games/engine.contagion.txt
gamedata/sdktools.games/engine.contagion.txt

Requested and tested in https://forums.alliedmods.net/showthread.php?t=321041 by UeberDaniel.

Update Contagion gamedata

---

extensions/regex/CRegEx.cpp
extensions/regex/CRegEx.h
extensions/regex/extension.cpp
plugins/include/regex.inc

* Prevented to triple and double call `strlen`.
* More informative message on `if (offset >= len)`.
* Add missing parametr in navite `MatchRegex`.
P.S. I'm have little exp in c++, sorry if something wrong.

Regex Little Changes

---

plugins/include/timers.inc

Comment wording is incoherent.

Fix wording of IsServerProcessing comment.

---

core/PlayerManager.cpp
core/PlayerManager.h

don't merge yet - linux build slave may be full. mac issues from https://github.com/alliedmodders/sourcemod/pull/1071

DarkM: build-fix for engine msg caching

---

gamedata/sdkhooks.games/engine.csgo.txt

Update csgo "Reload" offset

---

plugins/funcommands/blind.sp
plugins/funcommands/ice.sp
plugins/sql-admin-manager.sp
plugins/testsuite/cstrike-test.sp
plugins/testsuite/entpropelements.sp
plugins/testsuite/tf2-test.sp

Nice bit of clean up here. Only made sure it compiles.

Use GetCmdArgInt(Ex) in base plugins

---

gamedata/core.games/common.games.txt
gamedata/sdkhooks.games/game.bms.txt
gamedata/sdktools.games/game.bms.txt

This should be all the necessary game data, although I have not personally tested these.
Resolves: https://forums.alliedmods.net/showthread.php?t=320911

fix(gamedata): black mesa

---

gamedata/sdkhooks.games/engine.contagion.txt
gamedata/sdktools.games/engine.contagion.txt

Updates vtable offsets after Patch 2.1.2.2 again. #1171

Update Contagion gamedata again

---

gamedata/sdkhooks.games/game.pvkii.txt

* Update Function Offsets For PVKII 0.4.2.2
-Updates offsets for Linux/Win/Mac

Update Function Offsets For PVKII 0.4.2.2 (SDK Hooks)

---

gamedata/sdktools.games/game.pvkii.txt

* Update Function Offsets For PVKII 0.4.2.2
-Updates offsets for Linux/Win/Mac
-Update func sig FireOutput for Linux/Win/Mac

 Update Function Offsets For PVKII 0.4.2.2 (SDK Tools)

---

core/TimerSys.cpp

Black Mesa is particular and use timelimit in seconds instead of minutes

Fix timelimit not correct for Black Mesa

---

plugins/nextmap.sp

This change notifies the player to check their console for output. Also changes made to clean up code style.

Add cmdreplysource check to notify player and misc formatting

---

core/logic/Database.cpp
core/logic/Database.h
core/logic/ThreadSupport.cpp
core/logic/ThreadSupport.h
extensions/clientprefs/extension.cpp
extensions/clientprefs/extension.h
extensions/mysql/mysql/MyDatabase.cpp
extensions/mysql/mysql/MyDatabase.h
extensions/mysql/mysql/MyDriver.cpp
extensions/mysql/mysql/MyDriver.h
extensions/sqlite/driver/SqDatabase.cpp
extensions/sqlite/driver/SqDatabase.h
extensions/sqlite/driver/SqDriver.cpp
extensions/sqlite/driver/SqDriver.h

This also rewrites the work loop for threaded queries. It has been
simplified significantly.

Replace all uses of AMTL threads with STL threads.

---

core/CoreConfig.cpp
core/MenuStyle_Base.cpp
core/MenuStyle_Base.h
core/logic/GameConfigs.cpp
core/logic/PluginSys.cpp
core/logic/frame_tasks.cpp
core/logic/smn_adt_trie.cpp
core/logic/smn_database.cpp
public/ReentrantList.h
public/sm_stringhashmap.h

I apparently missed a bunch. This bumps up AMTL as well.

Replace more Move/Forward with STL variants.

---

plugins/include/tf2_stocks.inc

See https://github.com/alliedmodders/sourcepawn/pull/445

Fix TFResourceNames using array based enum struct

---

extensions/sdktools/vcaller.cpp

`LoadFromAddress` and `StoreToAddress` throws error when `null` or below `VALID_MINIMUM_MEMORY_ADDRESS` is passed, but `SDKCall` with `this` as raw address does not have one. Throw error and prevent crash from doing so.

Throw error when invalid address passed to SDKCall raw ptr

---

core/logic/smn_adt_stack.cpp
plugins/include/adt_stack.inc

Provide ArrayStack.Clone method.
Tested with [this script](https://gist.github.com/TheByKotik/d84d2fbe80581df600def7d2e1b4477d).

Provide ArrayStack.Clone method

---

.travis.yml
pushbuild.txt

This one's on me from eons ago. I messed up some spacing for cache. The rest is just stuff that's changed overtime that's irrelevant now.

travis-ci: address warnings / info.

---

extensions/sdkhooks/takedamageinfohack.cpp
extensions/sdkhooks/takedamageinfohack.h

https://github.com/alliedmodders/hl2sdk/pull/77

Correct SDKHooks_TakeDamage native

---

AMBuildScript
core/AMBuilder
extensions/regex/AMBuilder
plugins/AMBuilder
tools/buildbot/Versioning

Remove use of the Dep API.

---

core/logic/smn_console.cpp

Add SetGlobalTarget to PrintToConsole

---

public/sample_ext/AMBuildScript

I have optimizaied the spelling

Correct spelling in sample_ext build script

---

extensions/cstrike/rulesfix.cpp

If lookup of the patch location failed, don't turn on responding to A2S_Rules queries. Otherwise we'll see the log getting spammed with too large packet sizes again. #1447

A2S_Rules fix: Only change host_rules_show if patching was successful

---

core/MenuStyle_Base.cpp
core/MenuStyle_Radio.cpp

Fixed a compilation error
```
error: use of undeclared identifier 'g_Logger'
```

core: Fix not working MENU_DEBUG

---

gamedata/sdkhooks.games/engine.ep2v.txt
gamedata/sdktools.games/game.tf.txt
gamedata/sm-tf2.games.txt

TF2 update on 22/06/2021 broke a lot of SM gamedata
Thanks to @Scags for looking up the signature for `MakeBleed`

Update Team Fortress 2 gamedata

---

plugins/basetriggers.sp

The entire setup is sketchy but I am not going to rework it all at the moment to something like ReplyToCommand.
This also allows server to call 'ff' if it wants to.

Update basetriggers ShowFriendlyFire to use the same chat text visibility system as ShowTimeLeft

---

core/logic/FrameIterator.h

Fix crash in FrameIterator.

---

plugins/adminmenu/dynamicmenu.sp
plugins/basebans/ban.sp
plugins/basechat.sp
plugins/basecomm/gag.sp
plugins/basecommands/execcfg.sp
plugins/basecommands/kick.sp
plugins/basecommands/map.sp
plugins/basecommands/who.sp
plugins/basetriggers.sp
plugins/basevotes/voteban.sp
plugins/basevotes/votekick.sp
plugins/basevotes/votemap.sp
plugins/funcommands.sp
plugins/funcommands/beacon.sp
plugins/funcommands/blind.sp
plugins/funcommands/drug.sp
plugins/funcommands/fire.sp
plugins/funcommands/gravity.sp
plugins/funcommands/ice.sp
plugins/funcommands/noclip.sp
plugins/funcommands/timebomb.sp
plugins/funvotes/voteburn.sp
plugins/funvotes/voteslay.sp
plugins/mapchooser.sp
plugins/playercommands/rename.sp
plugins/playercommands/slap.sp
plugins/playercommands/slay.sp
plugins/rockthevote.sp

For optional build support with the new SourcePawn 1.12 branch

Add missing return values to plugins

---

core/smn_entities.cpp

Fix crash in `FindSendPropInfo()`

---

AMBuildScript
appveyor.yml
core/logic_bridge.cpp
extensions/sdkhooks/AMBuilder
loader/loader.cpp
tools/checkout-deps.ps1
tools/checkout-deps.sh

sdkhooks does not build in this SDK, so it's disabled. sdktools builds but does not load due to missing stubs.

Add support for hl2sdk-mock.

---

gamedata/sdkhooks.games/game.nmrih.txt
gamedata/sdktools.games/game.nmrih.txt

Correct offsets and signatures that were changed in the [1.12.0 update ](https://steamcommunity.com/games/224260/announcements/detail/3105788446465908770)

Update gamedata for NMRiH 1.12

---

AMBuildScript
configure.py

Add support for ASAN.

---

core/logic/sprintf.cpp

Fixes #1594 per @dvander instructions and self tests

Fix translation buffers not terminating at last cell

---

core/logic/smn_menus.cpp

Fix GetMenuExitBackButton always returning false

---

extensions/cstrike/rulesfix.cpp

See https://github.com/alliedmodders/sourcemod/pull/1662 and https://github.com/alliedmodders/sourcemod/pull/1667
At the time of the implementation of the "RulesFix" module in the CStrike extension, there was very poor forward and backward compatibility with the SteamWorks interfaces in the version of the SW SDK used by CS:GO (1.39a). Because of that, the "flat" C API for it was used. However, it turns out that this also has poor backward compatibility.
Since then, the SW C++ API has gained much better backward compatibility and pins the interface version at compile time, per library. And all interface versions do continue to be available internally in the Steam client. Now we can simplify this code while also fixing the current problem with it not finding the function.
This requires …

Use SteamWorks C++ API in CStrike RulesFix, for better interface compatibility

---

gamedata/sdktools.games/game.nmrih.txt

- Add "GetAttachment" offset
- Add "SetOwnerEntity" offset
- Add "LookupAttachment" signature

Add NMRiH support for new collision and attachment natives

---

plugins/adminhelp.sp

`ReadCommandIterator` 
->
```
CmdIter.GetName(Name, sizeof(Name));
Flags = CmdIter.Flags;
CmdIter.GetDescription(Desc, sizeof(Desc));
```

adminhelp.sp -> Switch to the new CommandIterator()

---

plugins/basevotes.sp

My little arguments:
1. Hardcoded strings is not a good idea.
2. In some cases it is really looks amiss (in my language).

Remove hardcoded a question mark

---

gamedata/sdkhooks.games/game.zpanic.txt
gamedata/sdktools.games/game.zpanic.txt

ZPS Version 3.2 released today and these are the updated offsets / signatures.

ZPS: Update Offsets & Signatures for 3.2

---

plugins/basevotes.sp
plugins/funvotes.sp

I think no need to create a function for each expression, especially if single use.

Inline one-expression single-use functions

---

gamedata/funcommands.games.txt

Spectators = Yellow
Pirates = Red
Vikings = Green
Knights = Blue

Added PVKII game with related team colors (beacon)

---

extensions/sdktools/vnatives.cpp
gamedata/sdkhooks.games/game.zpanic.txt
gamedata/sdktools.games/game.zpanic.txt
plugins/include/clients.inc

This should be merged after #1719

ZPS Update offsets for 3.2.4

---

gamedata/sdktools.games/game.bms.txt
gamedata/sdktools.games/game.hl2mp.txt

Adds Black Mesa, HL2DM gamedata for #1653 and #1620.

Add recent gamedata for BMS, HL2DM

---

plugins/adminhelp.sp

Change variable naming style to camel case for consistensy.

Change variable naming style in adminhelp.sp

---

plugins/include/clientprefs.inc

Clientprefs helpers for integers and strings

---

gamedata/core.games/common.games.txt

This is one small thing I missed when making 'pvkii' its own engine branch.

Make sure 'pvkii' gets 'GetDataDescMap' offset

---

plugins/basecommands/cancelvote.sp
plugins/basevotes.sp

feat(plugins): log missing actions

---

core/PlayerManager.cpp

Resolves #1611. Allegedly #1071 allows this to work.

Return the full list of exts/plugins with "sm exts/plugins"

---

bridge/include/LogicProvider.h
core/logic/AMBuilder
core/logic/LumpManager.cpp
core/logic/LumpManager.h
core/logic/common_logic.cpp
core/logic/smn_entitylump.cpp
core/logic/smn_entitylump.h
core/sourcemod.cpp
core/sourcemod.h
plugins/include/entitylump.inc
plugins/include/sourcemod.inc
plugins/testsuite/entitylumptest.sp
tools/entlumpparser/AMBuildScript
tools/entlumpparser/AMBuilder
tools/entlumpparser/configure.py
tools/entlumpparser/console_main.cpp

Backport entity lump functionality to 1.11

---

core/logic/LumpManager.cpp

entitylump: Backport separator fix into 1.11

---

extensions/sdkhooks/natives.cpp

Fix incorrect behaviour in SDKHooks_DropWeapon's "bypassHooks" parameter

---

gamedata/sdktools.games/engine.mcv.txt

CommitSuicide and Ignite seem to have shifted at some point and would crash the server when called

Update Military Conflict: Vietnam gamedata

---

tools/ghidra_scripts/makesig.py

For parity with the IDA script, since Ghidra is free.
Having this in the repo also lets it be more easily maintained if ever necessary.
All credit to nosoop who gave permission to add this from [his own repo.](https://github.com/nosoop/ghidra_scripts)

Add Ghidra MakeSig script

---

gamedata/sdktools.games/game.nucleardawn.txt

Adds the LookupAttachment signature for Nuclear Dawn

Add LookupAttachment signature for ND

---

.github/workflows/translations.yml
tools/language_check/requirements.txt

Try to get the translations action to run.

Fix translations workflow

---

translations/es/basetriggers.phrases.txt
translations/es/nominations.phrases.txt
translations/es/rockthevote.phrases.txt

First time contributing, please if I did something wrong correct me 🙂
Fixes this: https://github.com/orgs/alliedmodders/projects/1/views/1?pane=issue&itemId=24307209

Added missing and incomplete phrases to Spanish language

---

translations/es/basetriggers.phrases.txt
translations/es/nominations.phrases.txt
translations/es/rockthevote.phrases.txt

https://github.com/alliedmodders/sourcemod/pull/1964

spanish fixups

---

translations/de/basetriggers.phrases.txt
translations/de/common.phrases.txt
translations/de/nominations.phrases.txt
translations/de/plugin.basecommands.txt

Update the german translation with all new phrases.
https://github.com/orgs/alliedmodders/projects/1/views/1?pane=issue&itemId=24307188

Add missing german phrases

---

translations/las/adminhelp.phrases.txt
translations/las/basebans.phrases.txt
translations/las/basetriggers.phrases.txt
translations/las/clientprefs.phrases.txt
translations/las/common.phrases.txt
translations/las/core.phrases.txt
translations/las/funcommands.phrases.txt
translations/las/mapchooser.phrases.txt
translations/las/nextmap.phrases.txt
translations/las/nominations.phrases.txt
translations/las/playercommands.phrases.txt
translations/las/plugin.basecommands.txt
translations/las/rockthevote.phrases.txt
translations/las/sqladmins.phrases.txt

Update latam translations.
https://github.com/orgs/alliedmodders/projects/1/views/1?pane=issue&itemId=24307195

Add missing latam phrases

---

.github/workflows/translations_sanitycheck.yml
tools/language_check/sanity_check.py

This adds a basic smoke test for changes to the translation files. The pull request should be blocked on basic typos breaking the SMC file.

Add sanity check for syntax errors in translations

---

translations/fr/basetriggers.phrases.txt
translations/fr/common.phrases.txt
translations/fr/nominations.phrases.txt
translations/fr/plugin.basecommands.txt
translations/fr/rockthevote.phrases.txt

https://github.com/orgs/alliedmodders/projects/1/views/1?pane=issue&itemId=24307187

fix: Baguette (french) translations

---

translations/fi/basetriggers.phrases.txt
translations/fi/nominations.phrases.txt
translations/fi/rockthevote.phrases.txt

Fixes to Finnish translations according to: https://github.com/orgs/alliedmodders/projects/1/views/1?pane=issue&itemId=24307186
Credits to "rapu chan" and "mäyrä77" for helping with translations.

Add missing Finnish translations

---

translations/sk/nominations.phrases.txt

Update Slovak nominations.phrases.txt

---

translations/sk/basetriggers.phrases.txt

Update Slovak basetriggers.phrases.txt

---

.github/workflows/mocktest.yml
plugins/include/testing.inc
plugins/testsuite/mock/test_sorting.sp

Use [hl2sdk-mock](https://github.com/alliedmodders/hl2sdk-mock) to load SourceMod in a mock srcds and run plugins. This allows for end-to-end tests of the native API without requiring to spin up a whole game server. Only x86_64 right now until hl2sdk-mock runs on x86 again :D
This only tests the sorting.inc API similar to the existing test plugin in the plugins/testsuite folder. Tests fail if the srcds output contains "FAIL", which might be a little fragile.
The testing infrastructure can be expanded and more tests added over time. The existing tests in the [plugins/testsuite](https://github.com/alliedmodders/sourcemod/tree/master/plugins/testsuite) folder can't be used as is, but could serve as a starting point to convert to using the `testing.inc` pattern.
Ultimately something like …

Run basic native tests using hl2sdk-mock in CI

---

plugins/include/float.inc

Reverts alliedmodders/sourcemod#2011 until https://github.com/alliedmodders/sourcepawn/issues/890 is resolved

Revert "Update sourcepawn"

---

translations/jp/playercommands.phrases.txt
translations/jp/plugin.basecommands.txt
translations/jp/rockthevote.phrases.txt

Japanese translation corrections.

Japanese translations

---

core/NextMap.h

Increase lastMap buffer

---

tools/checkout-deps.ps1
tools/checkout-deps.sh

add --recursive for missing submodules (particulary for MM witch use submodule for hl2sdk-manifests)

Fix missing submodules

---

.github/workflows/scripting.yml
AMBuildScript
tools/buildbot/PackageHelpers

This also enables universal spcomp binaries with arm64 support.

Fix macOS scripting SDK build.

---

gamedata/core.games/common.games.txt
gamedata/sdkhooks.games/game.tf2classic.txt
gamedata/sdkhooks.games/master.games.txt
gamedata/sdktools.games/game.tf2classic.txt
gamedata/sdktools.games/master.games.txt

* add gamedata skeleton for tf2classic
* Update game.tf2classic.txt
* Update game.tf2classic.txt
---------
Co-authored-by: azzy <67557558+azzyr@users.noreply.github.com>
(cherry picked from commit 5c971fd51b6a91e29e67af5d0a8b55f3d6f6709d)

add gamedata for tf2classic (#2088)

---

gamedata/core.games/engine.ep1.txt
gamedata/core.games/game.gmod9.txt
gamedata/core.games/master.games.txt
gamedata/sdkhooks.games/game.gmod9.txt
gamedata/sdkhooks.games/master.games.txt
gamedata/sdktools.games/engine.ep1.txt
gamedata/sdktools.games/game.gmod9.txt
gamedata/sdktools.games/master.games.txt

Add gmod9 gamedata.

---

translations/cze/basetriggers.phrases.txt
translations/cze/nominations.phrases.txt

Complete Czech translatations. [See Project page](https://github.com/orgs/alliedmodders/projects/1/views/1?layout=table&pane=issue&itemId=24307183&sortedBy%5Bdirection%5D=asc&sortedBy%5BcolumnId%5D=Status)

i18n: Czech Translations

---

core/logic/smn_filesystem.cpp
plugins/include/files.inc

Add GetFilePermissions

---

translations/vi/adminhelp.phrases.txt
translations/vi/basetriggers.phrases.txt
translations/vi/nominations.phrases.txt

This translation was made by friends who live in Vietenam and who are in language university, so they do not come from a translator website.
https://github.com/orgs/alliedmodders/projects/1/views/1?pane=issue&itemId=24307070

fix(i18n): Vietnamese translations

---

pushbuild.txt

Master branch was done in #2209.

Rebuild for hl2sdk-tf2 changes.

---

gamedata/sdkhooks.games/game.synergy.txt
gamedata/sdktools.games/game.synergy.txt

Update Synergy offsets and signatures for latest Synergy. There are still updates happening, so these may become incorrect in the coming weeks.
Resolves: https://github.com/alliedmodders/sourcemod/issues/2225

Update SDKTools & SDKHooks Gamedata for Synergy

---

core/logic/GameConfigs.cpp
core/logic/smn_gameconfigs.cpp

Fixes #2250 
Implements both fixes discussed.

Attempt reparse on stat failures and return BAD_HANDLE on error

---

gamedata/sdkhooks.games/engine.ep2v.txt
gamedata/sm-tf2.games.txt

RemoveDisguise & Spawn were reported as wrong, those should now be the correct offsets and signature. I've also made another pass on the entire sdkhooks/sdktools gamedata for css, and found one more wrong offset in ShouldCollide, this hopefully indicates the rest of the gamedata is valid.

Gamedata fix

---

gamedata/sdkhooks.games/engine.ep2v.txt
gamedata/sdktools.games/game.dod.txt

Offsets taken from Asherkin's vtable dumper using the Linux binary from the dedicated server.
Most offsets were tested on Windows x86_64 and are functional.
One issue: `CommitSuicide` isn't working. I can't figure out why.

Update Day of Defeat: Source SDKHooks and SDKTools Gamedata

---

gamedata/sdktools.games/game.cstrike.txt

Well that's a little embarrassing... Sorry for that copy/paste blunder!
#2284 revealed the issue

Fix sdktools css gamedata

---

gamedata/sdktools.games/game.hl2mp.txt

Adds missing offsets for x86-64 HL2DM's SDKTools gamedata.

Update HL2DM x86-64 SDKTools Gamedata

---

gamedata/sm-tf2.games.txt

More things
Windows x64 signature didn't change

Update StunPlayer signature

---

pushbuild.txt

Needed to trigger builders, doesn't seem like the submodule update did the trick

Push build for safetyhook submodule update

---

gamedata/sdktools.games/game.dystopia.txt

Updated sdktools gamedata offsets for Dystopia

Updated sdktools gamedata offsets for Dystopia

---

gamedata/core.games/common.games.txt
gamedata/sdkhooks.games/game.treason.txt
gamedata/sdkhooks.games/master.games.txt
gamedata/sdktools.games/game.treason.txt
gamedata/sdktools.games/master.games.txt

First time working with sourcemod, let me know if I missed anything or put something in the wrong file!
Treason doesn't have a Linux build and I pulled this info from PDBs, being the main programmer for the game.

Added Treason gamedata
